#!/bin/sh
# copy this file to .git/hooks and make it executable. for everything you commit from now on the version information will be written to the variables_fff+ file

if git rev-parse --verify HEAD 2>/dev/null >/dev/null; then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for f in `git diff-index --name-only $against|grep -vE '\.gif|\.txt|\.md|\.patch|\.mk|LICENCE|\.index|\.html|\.bin' ` ; do
  if [ -f $f ]; then
    sh -n $f
    if [ $? -gt 0 ]; then
      echo "The script \"$f\" contains errors, please fix them before commit."
      exit 1
    fi
  fi
done

unixtime=$(($( date +%s ) / 3600))
filename="openwrt-addons/etc/variables_fff+"

echo "FFF_PLUS_VERSION=\"$unixtime\"	# $( date +%d%b%Y-%H:%M )">$filename
echo "FFF_VERSION=\"2.0.0\"		# openWrt based">>$filename
