#!/bin/sh
[ -n "$( uci get system.@weblogin[0].enabled )" ] && exit	# fixme! respect MAC|HOSTNAME for USERNAME/PASSWORD

. /tmp/loader

MODE="${1:-unset}"
MAC="${2:-00:00:00:00:00:00}"
IP="${3:-127.0.0.1}"
HOST="${4:-unset}"

DEV="$( _net ip2dev $IP )"

case $DEV in
	 $WANDEV) TYPE="wan" ;;
	 $LANDEV) TYPE="lan" ;;
	$WIFIDEV) TYPE="wifi" ;;
	  $LODEV) TYPE="loopback" ;;
	       *) TYPE="unknown" ;;
esac

_log do dhcp_$MODE daemon info "'$MAC' is from '$DEV' = ${TYPE}-DEV"

case $MODE in
	add|old)
		case "$( uci get system.@profile[0].name )" in
				  ffsundi_mesh)
		  				[ "$TYPE" != "lan" ] && {
		  					_log do dhcp_$MODE daemon info "'$MAC' is not from lan, exit"
		  					exit
		  				}
					     ;; 
			weimarnetz_standard_ap)
						_log do dhcp_$MODE daemon info "this profile is always auto-unsplashed"
					     ;;
		      weimarnetz_standard_mesh)
      						[ "$TYPE" != "lan" ] && {
      							_log do dhcp_$MODE daemon info "'$MAC' is not from lan, exit"
      							exit
      						}
      			 		     ;;
	          	     		     *)
	          	     		     	_log do dhcp_$MODE daemon debug "no action with this profile"
	          	     		     	exit
					     ;;
		esac

		if _pfilter user_probe "$MAC" ; then
			_log do dhcp_$MODE daemon info "'$MAC' already shaped"

			if _pfilter user_probe_splash $MAC ; then
			
				_log do dhcp_$MODE daemon info "'$MAC' gets a redirect, unsplashing"
				_pfilter user_splash_control nosplash $MAC $IP
			else
				_log do dhcp_$MODE daemon info "'$MAC' is already freed"
			fi
		else
			_log do dhcp_$MODE daemon info "'$MAC' yet unknown, from DEV/IF:'$DEV'/'$DNSMASQ_INTERFACE' ID:'$DNSMASQ_CLIENT_ID' VENDOR:'$DNSMASQ_VENDOR_CLASS'"
		
			if _pfilter user_ruleset_activate $MAC $IP ; then
			
				_log do dhcp_$MODE daemon info "'$MAC' (fast) activated"
			else
				_log do dhcp_$MODE daemon info "'$MAC' is getting (slowly) established"
				_pfilter user_add $MAC $IP
				_log do dhcp_$MODE daemon info "'$MAC' ready"
			fi                  
		fi
	;;
	del)
		_log do dhcp_$MODE daemon info "'$MAC' lease deleted - end_of_life: '$(grep $MAC /var/run/dhcp.leases | cut -d' ' -f1)' now: '$(_system date unixtime)'"
	;;
esac

