#!/bin/sh

. /etc/functions_base_fff+ && func_need log pfilter netparam

MODE="${1:-unset}"
MAC="${2:-00:00:00:00:00:00}"
IP="${3:-127.0.0.1}"
HOST="${4:-unset}"

DEV="$( ip -oneline route get $IP | sed -n 's/^.* dev \([a-zA-Z0-9@\.]*\)[^a-z]*src .*/\1/p' )"

case $DEV in
	 $WANDEV) TYPE="wan" ;;
	 $LANDEV) TYPE="lan" ;;
	$WIFIDEV) TYPE="wifi" ;;
	  $LODEV) TYPE="loopback" ;;
	       *) TYPE="unknown" ;;
esac

func_log dhcp_$MODE daemon info "'$MAC' is from '$DEV' = ${TYPE}-DEV"

case $MODE in
	add|old)
		case "$(nvram get fff_profile)" in
				  ffsundi_mesh)
		  				[ "$TYPE" != "lan" ] && {
		  					func_log dhcp_$MODE daemon info "'$MAC' is not from lan, exit"
		  					exit
		  				}
					     ;; 
			weimarnetz_standard_ap)
						func_log dhcp_$MODE daemon info "this profile is always auto-unsplashed"
					     ;;
		      weimarnetz_standard_mesh)
      						[ "$TYPE" != "lan" ] && {
      							func_log dhcp_$MODE daemon info "'$MAC' is not from lan, exit"
      							exit
      						}
      			 		     ;;
	          	     		     *)
	          	     		     	func_log dhcp_$MODE daemon debug "no action with this profile"
	          	     		     	exit
					     ;;
		esac

		func_need old vars_old
		
		if func_pfilter_is_usermac "$MAC" ; then
			func_log dhcp_$MODE daemon info "'$MAC' already shaped"

			if func_pfilter_is_redirected $MAC ; then
			
				func_log dhcp_$MODE daemon info "'$MAC' gets a redirect, unsplashing"
				fkt_control_redirect_for_user_with_mac_and_ip nosplash $MAC $IP
			else
				func_log dhcp_$MODE daemon info "'$MAC' is already freed"
			fi
		else
			func_log dhcp_$MODE daemon info "'$MAC' yet unknown, from '$DEV',ID:'$DNSMASQ_CLIENT_ID',CLASS:'$DNSMASQ_VENDOR_CLASS',IF:'$DNSMASQ_INTERFACE'"
		
			if func_activate_reserved_user_chain $MAC $IP ; then
			
				func_log dhcp_$MODE daemon info "'$MAC' (fast) activated"
			else
				func_log dhcp_$MODE daemon info "'$MAC' is getting (slowly) established"
				fkt_add_user_with_mac_and_ip $MAC $IP
				func_log dhcp_$MODE daemon info "'$MAC' ready"
			fi                  
		fi
	;;
	del)
		func_log dhcp_$MODE daemon info "'$MAC' lease deleted - end_of_life: '$(grep $MAC /var/run/dhcp.leases | cut -d' ' -f1)' now: '$(date +%s)'"
	;;
esac

