#!/bin/sh /etc/rc.common

START=11

boot()
{
	local file="/www/REBOOT_COUNTER"
	local i

        if [ -e "$file" ]; then
                read -r i <"$file"
                i=$(( i + 1 ))
                echo $i >"$file"
        else
                echo 1 >"$file"
        fi

	show_kmods()
	{
		echo "### [START] loaded kmodules"
		cat '/proc/modules'
		echo "### [READY] loaded kmodules"
	}

	show_kmods >'/dev/console'
}
