#!/bin/sh /etc/rc.common

START=99

boot()
{
	. /tmp/loader
	rm '/tmp/BOOT' '/tmp/DEBUG'

	_http robotstxt_generate

	# this removes interface 'tunl0@NONE'
	rmmod ipip

	{
		echo 'cron.upgrade_packages'
		echo "rm '$TMPDIR/scheduler_keep_running'"
		echo '_log remote ready_booting'
	} >>$SCHEDULER
}
