#!/bin/sh /etc/rc.common

START=99

boot()
{
	. /tmp/loader
	rm '/tmp/BOOT' '/tmp/DEBUG'

	_http robotstxt_generate
	echo >>$SCHEDULER 'cron.upgrade_packages'
	echo >>$SCHEDULER "rm '$TMPDIR/scheduler_keep_running'"
}
