#!/bin/sh /etc/rc.common

START=99

boot()
{
	. /tmp/loader
	rm '/tmp/BOOT' '/tmp/DEBUG'

	echo >>$SCHEDULER 'cron.upgrade_packages'

	# FIXME! only work after a real crash?
#	bool_true 'system.@system[0].avoid_autoreboot' && {
#		_log it first_run daemon sms 'startup'
#	}
}
