#!/bin/sh /etc/rc.common

START=00

boot()
{
        touch /tmp/BOOT
        touch /tmp/DEBUG
        /etc/kalua_init

	[ -e "/etc/config/wireless" ] || return 0

	. /tmp/loader
	case "$HARDWARE" in
		"Buffalo WHR-HP-G54")
			case "$( uci get wireless.radio0.rxantenna )-$( uci get wireless.radio0.txantenna )" in
				"1-1")
				;;
				*)
					uci set wireless.radio0.rxantenna=1
					uci set wireless.radio0.txantenna=1
					uci commit wireless
				;;
			esac
		;;
	esac
}
