#!/bin/sh /etc/rc.common

START=41

boot()
{
	. /tmp/loader
	_netparam check
	/etc/init.d/S43ethers_fff+ start

	case "$HARDWARE" in
		"Linksys WRT54G/GS/GL"|"Buffalo WHR-HP-G54"|"Dell TrueMobile 2300")
			[ -e "/etc/modules.d/19-usb-brcm47xx" ] && {
				rm "/etc/modules.d/19-usb-brcm47xx" "/etc/modules.d/50-usb-ohci" "/etc/modules.d/20-usb-core"
				_system crashreboot 'kmodules_tidyup'
			}
		;;
	esac
}
