#!/bin/sh /etc/rc.common

START=00

boot()
{
	for ENTRY in "vm.panic_on_oom=1" "kernel.panic_on_oops=1" "kernel.panic=1"; do {
		grep -q ^"$ENTRY" "/etc/sysctl.conf" || {
			echo "$ENTRY" >>"/etc/sysctl.conf"
		}
	} done

	case "$( uname -r )" in
		"3.3.8")
			[ -e "/etc/modules.d/45-ipt-nathelper" ] && { DIRTY=1; rm "/etc/modules.d/45-ipt-nathelper"; }
			[ -e "/etc/modules.d/43-ipt-nat-extra" ] && { DIRTY=1; rm "/etc/modules.d/43-ipt-nat-extra"; }
			[ "$DIRTY" = 1 ] && reboot
		;;
	esac

        touch /tmp/BOOT
        touch /tmp/DEBUG
        /etc/kalua_init

	[ -e "/etc/config/wireless" ] || return 0

	. /tmp/loader
	case "$HARDWARE" in
		"Buffalo WHR-HP-G54")
			case "$( uci get wireless.radio0.rxantenna )-$( uci get wireless.radio0.txantenna )" in
				"1-1")
				;;
				*)
					uci set wireless.radio0.rxantenna=1
					uci set wireless.radio0.txantenna=1
					uci commit wireless
				;;
			esac
		;;
		"Linksys WRT54G:GS:GL")
			case "$( uci get wireless.radio0.rxantenna )-$( uci get wireless.radio0.txantenna )" in
				"0-0")
				;;
				*)
					uci set wireless.radio0.rxantenna=0
					uci set wireless.radio0.txantenna=0
					uci commit wireless
				;;
			esac
		;;
	esac
}
