#!/bin/sh /etc/rc.common

START=45

. /tmp/loader

start() {
	_netfilter start

	for I in 0 1 2 3; do {							# max 4 wifidevs
		IP="$( _net dev2ip wlan${I} )"					# ip of root-interface
		for IFNAME in wlan${I}-1 wlan${I}-2 wlan${I}-3; do {		# iterate over child VIFs
			iwconfig $IFNAME 2>/dev/null | grep -q $IFNAME && {	# ifname exists?
				[ -z "$( _net dev2ip $IFNAME )" ] && {		# has ip?
					ip address add $IP dev $IFNAME		# set ip!
				}
			}
		} done
	} done
}

stop() {
	_netfilter stop
}
