#!/bin/sh /etc/rc.common

START=45

. /tmp/loader

start() {
	_netfilter start

	[ $OPENWRT_REV -ge 39050 ] && return 0

	for I in 0 1 2 3; do {							# max 4 wifidevs
		IP="$( _net dev2ip "wlan${I}" )"				# ip of root-interface
		for IFNAME in wlan${I}-1 wlan${I}-2 wlan${I}-3; do {		# iterate over child VIFs
			_net dev_is_valid "$IFNAME" && {
				[ -z "$( _net dev2ip "$IFNAME" )" ] && {	# and has no ip!
					[ -n "$IP" ] && {
						_log it apply_missing_ip daemon alert "adding $IP to $IFNAME"
						ip address add $IP dev $IFNAME	# no! -> set ip!
					}
				}
			}
		} done
	} done
}

stop() {
	_netfilter stop remember_over_reboot
}
