#!/bin/sh
. /tmp/loader

# todo:
# with/without OLSR on all interfaces? or specific interfaces?

ifname2mtu()
{
	ip link show dev "${1:-nonexistent_$2}" |
	 sed -n 's/^.* mtu \([0-9]*\).*/\1/p;q'
}

netparam_for_uci_devices ()
{
	local NAME IFNAME ADDRESS NETMASK MTU BROADCAST NETWORK PREFIX HOSTNAME CONFIG_PROFILE

	for DEVICE in loopback wlan lan wan ; do {

		case $DEVICE in
			loopback) NAME="LO" ;;
			wlan)	  NAME="WIFI" ;;
			lan)	  NAME="LAN" ;;
			wan)	  NAME="WAN" ;;
		esac

		IFNAME="$(  uci -q get network.$DEVICE.ifname  )"

		# make sure, that hybrid interfaces use the adhoc-interface for 'testing', otherwise the first interface
		[ "$DEVICE" = "wlan" ] && {
			if [ -e "/sbin/ifstatus" ]; then
				if   fgrep -q "wlanadhoc" "/etc/config/wireless"; then
					IFNAME="$( ifstatus "wlanadhoc" | fgrep '"device":' | cut -d'"' -f4 )"
					DEVICE="wlanadhoc"
				elif fgrep -q "wlan" "/etc/config/wireless"; then
					IFNAME="$( ifstatus "wlan" | fgrep '"device":' | cut -d'"' -f4 )"
				fi
			elif [ -e "/etc/config/wireless" ]; then
				IFNAME="wlan0"
			fi
		}

		ADDRESS="$( uci -q get network.$DEVICE.ipaddr  )"
		NETMASK="$( uci -q get network.$DEVICE.netmask )"
		MTU="$( ifname2mtu "$IFNAME" "$DEVICE" )"

		case "$( uci get network.$DEVICE.proto )" in
			dhcp)
				ADDRESS="$( _net dev2ip $IFNAME )"
				NETMASK="$( _net dev2ip $IFNAME mask )"
			;;
			pppoe)							# fixme! should also work for pppoe-lan etc.
				IFNAME="pppoe-wan"
				ADDRESS="$( _net dev2ip $IFNAME )"
				NETMASK="$( _net dev2ip $IFNAME mask )"
				MTU="$( ifname2mtu "$IFNAME" "$DEVICE" )"
			;;
		esac

		case "$DEVICE" in
			wlan)
				[ "$( uci get wireless.radio0.disabled )" = 1 ] && {
					IFNAME=; ADDRESS=; NETMASK=
				}
			;;
		esac

		echo "${NAME}DEV=$( _sanitizer do "$IFNAME" firstword )"
		echo "${NAME}MTU=$MTU"
		echo "${NAME}ADR=$ADDRESS"
		echo "${NAME}MSK=$NETMASK"

		BROADCAST=;NETWORK=;PREFIX=
		[ -n "$MTU" ] && eval $( ipcalc.sh $ADDRESS $NETMASK )

		echo "${NAME}BRC=$BROADCAST"
		echo "${NAME}NET=$NETWORK"
		echo "${NAME}PRE=$PREFIX"
		echo "${NAME}OLSR="
	} done

	list_wifi_devs()
	{
		local network_name list_wifi_names
		list_wifi_names="$( sed -n 's/^.*network\(.*\)/\1/p' /etc/config/wireless )"

		for network_name in $list_wifi_names; do {
			# 'wlanadhoc' -> wlanadhoc
			network_name="$( _sanitizer do "$network_name" alphanumspacedot )"
			# JSON: "device": "wlan0",
			ifstatus "$network_name" | grep '"device":' | cut -d':' -f2 | cut -d'"' -f2
		} done
	}

	echo "WIFI_DEVS='$( for IFNAME in $( list_wifi_devs ); do echo -n "$IFNAME "; done )'"

	[ -e "/tmp/dmesg.boot" ] || . /usr/sbin/cron.check_klog
	fgrep -sq "phy0: failed to initialize PHY" "/tmp/dmesg.boot" && {
		echo "WIFIDEV=	# failed to initialize PHY"
	}
}

_build()
{
	local FUNC="build"
	local FILE="/tmp/NETPARAM"

	_log do $FUNC daemon debug "building '$FILE' for an uci-device"
	netparam_for_uci_devices >$FILE
}

HASH_OLD="$( _file hash /tmp/NETPARAM )"
_build
HASH_NEW="$( _file hash /tmp/NETPARAM )"

[ "$HASH_OLD" = "$HASH_NEW" ] || {
	/etc/kalua_init			# this includes a static version of NETPARAM
}					# fixme! hook when 'ifup wan' gets an dhcp-lease
