#!/bin/sh
[ -e '/tmp/ENDBOOT' ] || exit 1

. /tmp/loader				# this script runs ~ every 15 minutes
[ -n "$LOWMEM" ] && killall rcS		# only needed for old routers

_watch wifi_mode || _log sleep let_wifi_settle_down 180 step 5

# REMOVE!
case "$CONFIG_PROFILE" in
	boltenhagendh*)
		[ "$( uci -q get olsrd.@Interface[0].speed )" = '20' ] || {
			grep -sq 'sven-ola' '/etc/init.d/olsrd' '/lib/functions/olsrd.sh' && {
				uci set olsrd.@Interface[0].speed='20'
				_olsr daemon restart 'new speed'
			}
		}
	;;
esac

_firmware upgrade_is_needed && {
	if _wifi watch_phy_problems; then
		echo >$SCHEDULER_IMPORTANT '_firmware check_forced_upgrade'
	else
		_system reboot_safe "update needed, but phy_problems: rebooting before firmware update"
	fi
}

# fixme! move to apply_profile
if $IPT -t mangle -nL shaper | grep -q ^'ACCEPT' ; then
	[ -e "/etc/init.d/netfilter" ] && {
		/etc/init.d/netfilter enabled || {
			/etc/init.d/netfilter enable
			/etc/init.d/netfilter restart
		}
	}
else
	[ -s "/etc/rc.d/S45netfilter" ] || {
		/etc/init.d/netfilter enable
		/etc/init.d/netfilter restart
	}
fi
