#!/bin/sh
. /tmp/loader		# this script runs ~ every 15 minutes

case "$( uci get wireless.radio0.htmode )" in
	HT40*)
		case "$( _wifi mode $WIFIDEV )" in
			ap)
				uci set wireless.radio0.htmode=HT20
				uci commit wireless
			;;
		esac
	;;
esac

case "$HARDWARE" in
	"Buffalo WHR-HP-G54"|"Linksys WRT54G"*)
		for FILE in /lib/preinit/*; do {
			fgrep -q "ifconfig" "$FILE" && {
				fgrep -q "#ifconfig" "$FILE" || {
					_log do ifconfig_patch_away daemon info "often produces 'page allocation failure'"
					sed -i 's/ifconfig/:;#ifconfig/g' "$FILE"
				}
			}
		} done
	;;
esac

_watch flash_free_space

_watch wifi_mode || sleep 30		# lets settle down to see some neighs

_watch system_time
_watch dns_resolution

[ -n "$( uci get network.lan.gateway )" ] && {
	_watch vpn || {
		_vpn restart
	}
}

_watch pppoe
# _watch netserver
_watch sshd_or_telnet
# do a registration
/usr/sbin/cron.registrator_client.sh 
_watch dhcp_space
_net refresh_dnshosts

case "$CONFIG_PROFILE" in
	ffweimar*)
		[ -n "$( uci get system.@system[0].latitude )" ] && {
			echo "$( uci get system.@system[0].latitude ),$( uci get system.@system[0].longitude )">/var/run/latlon.txt
		}
	;;
	*)
		cron.add_collected_userdata_into_db

		_log sleep jitter_user_stats_process "$( _math random_integer 0 100 )" step 5
		_netfilter user_stats_process
	;;
esac

/usr/sbin/cron.reverse_ssh_tunnel

_firmware upgrade_is_needed && {
	touch /tmp/START_SYSUPGRADE
}


[ -e "/etc/init.d/firewall" ] && {
	/etc/init.d/firewall disable
}

[ -e "/etc/init.d/ulogd" ] && {
	/etc/init.d/ulogd disable
}

[ "$( uci get dhcp.@dnsmasq[0].notinterface )" = "wan" ] || {
	_net local_inet_offer >/dev/null && {
		uci set dhcp.@dnsmasq[0].notinterface=wan
		/etc/init.d/dnsmasq restart
	}
}

if iptables -t mangle -nL shaper | grep -q ^ACCEPT ; then
	[ -e "/etc/init.d/netfilter" ] && {
		/etc/init.d/netfilter enable
		reboot
	}
else
	[ -s "/etc/rc.d/S45netfilter" ] || {
		/etc/init.d/netfilter enable
		/etc/init.d/netfilter restart
	}
fi

[ -e "/tmp/ENDBOOT" ] || {
	[ "$( _system uptime min )" -gt 5 ] && {
		touch "/tmp/ENDBOOT"
		killall rcS     # fixme!
	}
}
