#!/bin/sh
[ -e '/tmp/ENDBOOT' ] || exit 1

. /tmp/loader				# this script runs ~ every 15 minutes
[ -n "$LOWMEM" ] && killall rcS		# only needed for old routers

_watch wifi_mode || _log sleep let_wifi_settle_down 180 step 5

# FIXME! remove if all updated / broken fstools
# https://dev.openwrt.org/ticket/19564 - maybe for all kernel 3.18+?

we_need_space()
{
	[ $OPENWRT_REV -le 44150 ] && return 0

	_system version '44942...99999' && {
		# https://dev.openwrt.org/ticket/19564
		uci set system.@system[0].avoid_autoreboot='true'
		return 0
	}

	_weblogin authserver is_myself
}

we_need_space && {
	for F in $( ls -1S /www/coredumps ); do test -s "$F" || >"/www/coredumps/$F"; done
}

# FIXME! this is a workaround for in interrupted user request from userDB-GUI
for FILE in /www/ticketcheck-requested_*; do {
	[ -e "$FILE" ] && {
		PROFILE_ID="$( echo "$FILE" | cut -d'_' -f2 )"
		rm "$DIR_DATABASE/USER/profile/id${PROFILE_ID}_counterA" 2>/dev/null
		echo >>$SCHEDULER "_db ticketcheck; rm $FILE"
	}
} done

_firmware upgrade_is_needed && {
	if _wifi watch_phy_problems; then
		echo >$SCHEDULER_IMPORTANT '_firmware check_forced_upgrade'
	else
		_system reboot_safe "update needed, but phy_problems: rebooting before firmware update"
	fi
}

# fixme! move to apply_profile
if $IPT -t mangle -nL shaper | grep -q ^'ACCEPT' ; then
	[ -e "/etc/init.d/netfilter" ] && {
		/etc/init.d/netfilter enabled || {
			/etc/init.d/netfilter enable
			/etc/init.d/netfilter restart
		}
	}
else
	[ -s "/etc/rc.d/S45netfilter" ] || {
		/etc/init.d/netfilter enable
		/etc/init.d/netfilter restart
	}
fi
