#!/bin/sh
. /tmp/loader

[ -n "$FAILSAFE" ] && exit

case $1 in
	unload_unneeded_kmodules)
		if [ -e "/www/GOOD_MODULE_UNLOAD" ]; then
			while read LINE; do {
				rmmod "$LINE"
			} done <"/www/GOOD_MODULE_UNLOAD"
		else
			L1="pppox pppoe slhc ppp_generic"
			L2="ppp_async switch_adm switch_robo switch_core diag"
			L3="ts_fsm ts_bm ts_kmp"
			L4="crc_ccitt aes_generic"
			L5="compat_xtables compat"
			L6="xt_multiport xt_comment xt_CLASSIFY xt_time xt_tcpmss xt_statistic"
			L7="xt_DSCP xt_dscp xt_string xt_layer7 xt_quota xt_pkttype xt_owner"
			L8="xt_recent xt_helper xt_conntrack xt_CT xt_NOTRACK xt_HL xt_hl xt_ipp2p"
			L9="ipt_ecn ipt_ECN ipt_NETMAP iptable_raw"
			L0="nf_nat_proto_gre nf_nat_tftp nf_nat_sip nf_nat_pptp nf_nat_h323 nf_nat_amanda nf_nat_irc nf_nat_ftp"
			LA="nf_conntrack_tftp nf_conntrack_sip nf_conntrack_pptp nf_conntrack_h323 nf_conntrack_proto_gre nf_conntrack_amanda nf_conntrack_irc nf_conntrack_ftp xt_length xt_connmark xt_connbytes xt_limit"

			LB="ipt_ULOG xt_mark xt_length ipt_REDIRECT iptable_nat nf_nat xt_connmark xt_connbytes xt_state nf_conntrack_ipv4 nf_defrag_ipv4 nf_conntrack ipt_REJECT xt_TCPMSS ipt_LOG xt_mac xt_limit root@E1-mtx1-AP:/ iptable_mangle iptable_filter ip_tables xt_tcpudp x_tables"
			[ -e "/www/SIMPLE_MESHNODE" ] || LB=

			[ "$( uci get network.wan.proto )" = "pppoe" ] && L1=
			LIST="$L1 $L2 $L3 $L4 $L5 $L6 $L7 $L8 $L9 $L0 $LA $LB"

			_net local_inet_offer >/dev/null || {
				LIST="$LIST ipt_MASQUERADE"
			}

			unload()
			{
				local list="$1"
				local kmod

				for kmod in $list; do {

					_log do kmodule_unloader daemon info "rmmod '$kmod'" 
					rmmod $kmod

					if lsmod | fgrep -q "$kmod"; then
						echo "$kmod"
					else
						echo "$kmod" >>"/www/GOOD_MODULE_UNLOAD"
					fi
				} done
			}

			I=0
			while [ -n "$LIST" ]; do {
				I=$(( $I + 1 ))
				[ $I -eq 100 ] && break
				LIST="$( unload "$LIST" )"
				LIST="$( _list shuffle "$LIST" )"
			} done
		fi

		killall klogd
		killall hotplug2
		killall syslogd

		[ -e /www/SIMPLE_MESHNODE ] && {
			touch /tmp/service_ulog_nowatching
			killall ulogd

			list_ip_from_dhcp_leases()
			{
				cut -d' ' -f3 /tmp/dhcp.leases
			}

			list_ip_from_arp_cache()
			{
				ip neigh show | cut -d' ' -f1
			}

			can_see_lan_clients()
			{
				local ip

				for ip in $( list_ip_from_dhcp_leases ) $( list_ip_from_arp_cache ); do {
					fgrep -q "$ip;" "/tmp/CLIENTS_LAN" && return 0
				} done

				test -e "/www/SIMPLE_MESHNODE_FORCE_DHCP_LAN"
			}

			uci set dhcp.wlan.ignore=1
			uci delete dhcp.@dnsmasq[0].dhcpscript

			if can_see_lan_clients; then
				/etc/init.d/dnsmasq restart
			else
				uci set dhcp.lan.ignore=1
				echo "nameserver $( uci get dhcp.@dnsmasq[0].server )" >"/etc/resolv.conf"
				/etc/init.d/dnsmasq stop
			fi
		}

		touch /tmp/service_cronwatchdog_nowatching
		touch /tmp/cron_watchdog_please_end_yourself_$( cat /tmp/cron_watchdog.id )

		touch /tmp/service_ssh_nowatching
		killall dropbear

		dmesg -c >>/tmp/dmesg.boot

		ROOTETHERNET="$( echo $LANDEV | cut -d'.' -f1 )"	# eth0.1 -> eth0
		ip link set dev $ROOTETHERNET txqueuelen 32

		echo 1024 >/proc/sys/net/nf_conntrack_max
	;;
	start)
		grep -qs 0 "/proc/sys/vm/panic_on_oom" && {
			_log do panic_on_oom daemon info "activating auto-reboot when oom is working"
			echo 1 >"/proc/sys/vm/panic_on_oom"
		}

		[ -e "/etc/init.d/deactivated_cron_daemon" ] && {
			mv /etc/init.d/deactivated_cron_daemon /etc/init.d/S51crond_fff+
			/etc/init.d/S51crond_fff+ start
		}

		ZRAM_DEV="/dev/zram0"
		ZRAM_SIZE=4

		zram_applicable()
		{
			grep -sq ^"$ZRAM_DEV " /proc/swaps && return 1
			[ -e "$ZRAM_DEV" ] || return 1
			which mkswap >/dev/null || return 1
			which swapon >/dev/null || return 1
		}

		zram_applicable && {
			_log do zram_init daemon info "activating $ZRAM_DEV for swapping ($ZRAM_SIZE MegaBytes)"
			echo $(( $ZRAM_SIZE * 1024 * 1024 )) >"/sys/block/$( basename $ZRAM_DEV )/disksize"
			mkswap $ZRAM_DEV
			swapon $ZRAM_DEV
		}

		[ -e "/www/GOOD_MODULE_UNLOAD" ] && {
			$0 unload_unneeded_kmodules
		}

		grep -sq ^"START=97" "/etc/init.d/watchdog" && {
			sed -i 's/=97/=01/' "/etc/init.d/watchdog"
			CMD1="pidof watchdog >/dev/null"
			CMD2="echo 1000 >/proc/\$( pidof watchdog )/oom_score_adj"
			sed -i "s|}|	$CMD1 \&\& $CMD2 \n}|" "/etc/init.d/watchdog"
			eval $CMD2
		}

		_db restore

		PPPOE=0
		[ -n "$( uci get network.wan.username )" ] && PPPOE="$(( $PPPOE + 1 ))"
		[ -n "$( uci get network.wan.password )" ] && PPPOE="$(( $PPPOE + 1 ))"

		if [ $PPPOE -eq 2 -a ! -e "/tmp/PPPOE_NEEDED" ]; then
			touch "/tmp/PPPOE_NEEDED"
		else
			rm -f "/tmp/PPPOE_NEEDED"
		fi

		# fixme!
		# newstyle:
		# check first paragraph, which contains "option Mode":
		#
		# sed -e '/./{H;$!d;}' -e 'x;/option Mode/!d;' /etc/config/olsrd | fgrep "Mode" | wc -l 
		#
		# equal 2? -> do something

		case "$( uci get system.@profile[0].name )" in
			tkolleg*)
				[ "$LANADR" = "10.10.2.33" ] && {
					iptables -t nat -I POSTROUTING -s 10.10.0.0/16 -o $LANDEV	-j MASQUERADE
					iptables -t nat -I POSTROUTING -d 10.10.0.10			-j MASQUERADE		# drucker
					iptables -t nat -I POSTROUTING -d 10.10.0.2			-j MASQUERADE		# exNT
				}
			;;
			liszt28*)
				_watch usbstick_rehungen

				# generalize portfw:
				[ "$LANADR" = "10.63.99.33" ] && {
					iptables -t nat -I PREROUTING -i $WANDEV -p tcp --dport 222 -j DNAT --to-destination 10.63.2.34:22
				}
			;;
			aschbach*)
				[ "$LANADR" = "10.10.2.33" ] && {
					ip address add 192.168.134.254/24 dev $LANDEV label $LANDEV:kasseGW		# kassen gateway
				}
			;;
			berlinle*)
				[ "$LANADR" = "10.63.11.33" ] && {
					ssh -i /etc/dropbear/dropbear_dss_host_key -R 2048:localhost:22 root@intercity-vpn.de &
				}
			;;
		esac

		found_specific_hna_offer()
		{
			uci show olsrd | grep -q "olsrd.@Hna4\[.\].netaddr=$1"
		}

		attach_lan_ip()		# fixme! build an uci-representation
		{
			local ip="$1"
			local label="$2"

			ip address show dev $LANDEV | fgrep -q " $ip/32 " || {
				_log do attach_lan_ip daemon info "adding $ip to $LANDEV:$label"
				ip address add $ip dev $LANDEV label "$( _sanitizer do "$LANDEV:$label" length:15 )"
			}
		}

		found_specific_hna_offer 6.6.6.5 && attach_lan_ip 6.6.6.5 monitor	# internal monitor aggregator
		found_specific_hna_offer 6.6.6.6 && attach_lan_ip 6.6.6.6 dns
		found_specific_hna_offer 6.6.6.7 && attach_lan_ip 6.6.6.7 userdb
		found_specific_hna_offer 6.6.6.8 && attach_lan_ip 6.6.6.8 tunnelsrv	# only use for ask is_possible?

		[ "$( _firmware updatemode )" = "testing" ] && {
			_firmware update_pmu
		}

		/usr/sbin/cron.check_inet_gw_fff+
	;;
	*)
		echo "Usage: $0 start"
	;;
esac
