#!/bin/sh
. /tmp/loader

[ -n "$FAILSAFE" ] && exit

[ -e "/tmp/WIFI_SPECIALS.sh" ] && . "/tmp/WIFI_SPECIALS.sh"

[ -e '/www/SMS' ] && {
	rm '/www/SMS'
	echo >>$SCHEDULER_IMPORTANT "_log it informant daemon sms 'bootup'"
}

RANGE="$( uci -q get system.@monitoring[0].sensor_netrange )" && {
	case "$RANGE" in
		'wan') RANGE="$WANNET/$WANPRE" ;;
		'lan') RANGE="$LANNET/$LANPRE" ;;
	esac

	echo >>$SCHEDULER "_net list_webservers ${RANGE#*/} ${RANGE%/*} >/tmp/SCAN_WEBS"
}

[ -e '/etc/init.d/deactivated_cron_daemon' ] && {
	mv /etc/init.d/deactivated_cron_daemon /etc/init.d/S51crond_fff+
	/etc/init.d/S51crond_fff+ start
}

case "$CONFIG_PROFILE" in
	aschbach*)
		[ "$LANADR" = "10.10.2.33" ] && {
			ip address add 192.168.134.254/24 dev $LANDEV label $LANDEV:kasseGW		# kassen gateway
		}
	;;
esac

#	found_specific_hna_offer()
#	{
#		uci show olsrd | grep -q "olsrd.@Hna4\[.\].netaddr=$1"
#	}
#
#	attach_lan_ip()		# fixme! build an uci-representation
#	{
#		local ip="$1"
#		local label="$2"
#
#		ip address show dev $LANDEV | grep -Fq " $ip/32 " || {
#			_log it attach_lan_ip daemon info "adding $ip to $LANDEV:$label"
#			ip address add $ip dev $LANDEV label "$( _sanitizer run "$LANDEV:$label" length:15 )"
#		}
#	}
#
#	found_specific_hna_offer 6.6.6.5 && attach_lan_ip 6.6.6.5 monitor	# internal monitor aggregator
#	found_specific_hna_offer 6.6.6.6 && attach_lan_ip 6.6.6.6 dns
#	found_specific_hna_offer 6.6.6.7 && attach_lan_ip 6.6.6.7 userdb
#	found_specific_hna_offer 6.6.6.8 && attach_lan_ip 6.6.6.8 tunnelsrv	# only use for ask is_possible?

# cache luci header for splash page, improve by native lua call?
# this does not work ("401 auth required") when luci is not installed!
command -v 'lua' >/dev/null && _curl it 'http://127.0.0.1/cgi-bin/luci' >/tmp/LUCI_HEADER
