#!/bin/sh
. /tmp/loader

case "$1" in
	start)
		which hdparm >/dev/null && {
			_log do tune_ide_disc daemon info "setting spindown-time to 5 minutes and spinning down now"
			hdparm -y -S 60 /dev/discs/disc0/disc
			# fixme! is here the place to mount partitions, but needs some abstraction / look into freifunk-usbstick
		}

		echo >>$SCHEDULER 'cron.monitoring send_alive_message'
	;;
esac
