#!/bin/sh
. /tmp/loader

[ -n "$FAILSAFE" ] && exit
[ ! -e "/www/SOFTWARE_FULLY_INSTALLED" ] && exit

case $1 in
	start)
		_scheduler add "startup_helper"
	;;
	call)
		which hdparm >/dev/null && {
			_log do tune_ide_disc daemon info "setting spindown-time to 5 minutes and spinning down now"
			hdparm -y -S 60 /dev/discs/disc0/disc
			# fixme! is here the place to mount partitions, but needs some abstraction / look into freifunk-usbstick
		}

	;;
	*)
		_log do print_usage daemon debug "Usage: $0 (start|call)"
	;;
esac
