#!/bin/sh /etc/rc.common
# Priorize OLSR packages
# Copyright (C) 2007-2015 Sven-Ola, Weimarnetz

START=90
STOP=90

list_olsr_interfaces()
{
	sed -ne '/^Interface/{s/^Interface//;s/"//g;p}' '/var/etc/olsrd.conf'
}

start_tc()
{
	local list_devs="${1:-$( list_olsr_interfaces )}"
	local dev

	for dev in $list_devs; do
		tc qdisc add dev $dev root handle 1: prio
		tc qdisc add dev $dev parent 1:1 handle 10: sfq perturb 10
		tc qdisc add dev $dev parent 1:2 handle 20: sfq perturb 10
		tc qdisc add dev $dev parent 1:3 handle 30: sfq perturb 10
		tc filter add dev $dev protocol ip parent 1: prio 1 u32 match ip protocol 17 0xff match ip dport 698 0xffff flowid 1:1
		tc filter add dev $dev protocol ip parent 1: prio 2 u32 match ip protocol 6 0xff match u8 0x10 0xff at nexthdr+13 flowid 1:1
		tc filter add dev $dev protocol ip parent 1: prio 3 u32 match ip protocol 17 0xff match ip dport 53 0xffff flowid 1:2
		tc filter add dev $dev protocol ip parent 1: prio 4 u32 match u16 0x00ff 0xff00 at 2 flowid 1:2
		tc filter add dev $dev protocol ip parent 1: prio 5 u32 match ip protocol 0 0x00 flowid 1:3
	done
}
	
stop_tc()
{
	local list_devs="${1:-$( list_olsr_interfaces )}"
	local dev

	for dev in $list_devs; do
		tc filter del dev $dev protocol ip parent 1: prio 5 u32 match ip protocol 0 0x00 flowid 1:3
		tc filter del dev $dev protocol ip parent 1: prio 4 u32 match u16 0x00ff 0xff00 at 2 flowid 1:2
		tc filter del dev $dev protocol ip parent 1: prio 3 u32 match ip protocol 17 0xff match ip dport 53 0xffff flowid 1:2
		tc filter del dev $dev protocol ip parent 1: prio 2 u32 match ip protocol 6 0xff match u8 0x10 0xff at nexthdr+13 flowid 1:1
		tc filter del dev $dev protocol ip parent 1: prio 1 u32 match ip protocol 17 0xff match ip dport 698 0xffff flowid 1:1
		tc qdisc del dev $dev parent 1:3 handle 30: sfq perturb 10
		tc qdisc del dev $dev parent 1:2 handle 20: sfq perturb 10
		tc qdisc del dev $dev parent 1:1 handle 10: sfq perturb 10
		tc qdisc del dev $dev root handle 1: prio
	done
}

start()
{
	logger -s "Starting olsr prio..."
	start_tc
}

stop()
{
	logger -s "Stopping olsr prio..."
	stop_tc
}

restart()
{
	stop_tc
	start_tc
}
