#!/bin/sh /etc/rc.common 
# set /etc/HARDWARE early at boot.. apply_profile.code is later doing more specific detections 

START=15 

boot()
{
    if [ ! -s /etc/HARDWARE ]; then
        read HARDWARE < /tmp/sysinfo/model
        [ -z "$HARDWARE" ] && { 
            HARDWARE=$(grep ^machine /proc/cpuinfo | sed 's/.*: \(.*\)/\1/')
        }
        [ -z "$HARDWARE" ] && { 
            HARDWARE="unknown" 
        }
        echo "$HARDWARE" > /etc/HARDWARE
    fi
}
