#!/bin/sh

### during hotplug-ifup maintain list with interface = device = ssid,
#    - e.g. mkdir -p /var/run/interfaces wan (content = eth0.2) and eth0.2 (content = wan)
#    + mode + ssid? + driver
#    -> build NETPARAM or replace it?

case "$ACTION" in
        ifup)
		. /tmp/loader
		mkdir -p '/var/run/interfaces'	# FIXME! change location to $TMPDIR?

		# INTERFACE = wan
		# DEVICE = eth0.2
		echo "$DEVICE"    >"/var/run/interfaces/name2dev_$INTERFACE"
		echo "$INTERFACE" >"/var/run/interfaces/dev2name_$DEVICE"
		touch		   "/var/run/interfaces/nameUP_$INTERFACE"
		touch		   "/var/run/interfaces/deviceUP_$DEVICE"

		# TODO: history up/down?

		MAC="$( _net dev2mac "$DEVICE" )" && {
			[ -e "$PERMDIR/netparam_iface-$INTERFACE-mac" ] && {
				read -r MAC_OLD <"$PERMDIR/netparam_iface-$INTERFACE-mac"
			}

			[ "$MAC" = "$MAC_OLD" ] || {
				echo "$MAC" >"$PERMDIR/netparam_iface-$INTERFACE-mac"
			}
		}

		grep -q "^.*${DEVICE}:" '/proc/net/wireless' && {
			set -- $( iw dev "$DEVICE" info | grep 'wiphy ' )	# FIXME: explode
			PHY="$2"

			_wifi phy_amp_predistortion "$PHY" 'on'

			echo "phy$PHY" >"/var/run/interfaces/dev2radio_$DEVICE"
			echo "phy$PHY" >"/var/run/interfaces/name2radio_$INTERFACE"

			[ -e "$PERMDIR/netparam_phy-$PHY-mac-$INTERFACE" ] && {
				read -r MAC_OLD <"$PERMDIR/netparam_phy-$PHY-mac-$INTERFACE"
			}

			[ "$MAC" = "$MAC_OLD" ] || {
				echo "$MAC" >"$PERMDIR/netparam_phy-$PHY-mac-$INTERFACE"

				INDEX="$( _wifi get "$INTERFACE" index )"
				echo "$MAC" >"$PERMDIR/netparam_iface-idx2mac-$INDEX"
			}

			DRIVER="$( _wifi dev2driver "$DEVICE" )"
			echo "$DRIVER" >"/var/run/interfaces/dev2driver_$DEVICE"
			echo "$DRIVER" >"/var/run/interfaces/name2driver_$INTERFACE"
		}
	;;
	ifupdate)
	;;
	ifdown)
		rm "/var/run/interfaces/nameUP_$INTERFACE"
		rm "/var/run/interfaces/deviceUP_$DEVICE"
	;;
esac
