#!/bin/sh

olsrd_list_configured_interfaces()
{
	local i=0
	local interface

	while interface="$( uci -q get olsrd.@Interface[$i].interface )"; do {
		case "$( uci -q get olsrd.@Interface[$i].ignore )" in
			1|on|true|enabled|yes)
				# is disabled
			;;
			*)
				echo "$interface"	# e.g. 'lan'
			;;
		esac

		i=$(( $i + 1 ))
	} done
}

olsrd_interface_already_in_config()
{
	# e.g.: 'Interface "eth0.1" "eth0.2" "wlan0"'
	if grep -s ^'Interface ' '/var/etc/olsrd.conf' | grep -q "\"$DEVICE\""; then
		logger -t olsrd_hotplug -p daemon.debug "[OK] already_active: '$INTERFACE' => '$DEVICE'"
		return 0
	else
		logger -t olsrd_hotplug -p daemon.info "[OK] ifup: '$INTERFACE' => '$DEVICE'"
		return 1
	fi
}

olsrd_interface_needs_adding()
{
	local interface

	# likely and cheap operation:
	olsrd_interface_already_in_config && return 1

	for interface in $(olsrd_list_configured_interfaces); do {
		[ "$interface" = "$INTERFACE" ] && {
			olsrd_interface_already_in_config || return 0
		}
	} done

	logger -t olsrd_hotplug -p daemon.debug "[OK] interface '$INTERFACE' => '$DEVICE' not used for olsrd"
	return 1
}

olsrd_traffic_control_add()
{
	if which tc >/dev/null; then
		logger -t olsrd_hotplug -p daemon.info "[OK] prioritize OLSR packets on interface '$INTERFACE' => '$DEVICE'"
	else
		logger -t olsrd_hotplug -p daemon.info "[OK] cannot find 'tc' - cannot prioritize OLSR packets"
		return 0
	fi

	tc qdisc add dev $DEVICE root handle 1: prio
	tc qdisc add dev $DEVICE parent 1:1 handle 10: sfq perturb 10
	tc qdisc add dev $DEVICE parent 1:2 handle 20: sfq perturb 10
	tc qdisc add dev $DEVICE parent 1:3 handle 30: sfq perturb 10
	tc filter add dev $DEVICE protocol ip parent 1: prio 1 u32 match ip protocol 17 0xff match ip dport 698 0xffff flowid 1:1
	tc filter add dev $DEVICE protocol ip parent 1: prio 2 u32 match ip protocol 6 0xff match u8 0x10 0xff at nexthdr+13 flowid 1:1
	tc filter add dev $DEVICE protocol ip parent 1: prio 3 u32 match ip protocol 17 0xff match ip dport 53 0xffff flowid 1:2
	tc filter add dev $DEVICE protocol ip parent 1: prio 4 u32 match u16 0x00ff 0xff00 at 2 flowid 1:2
	tc filter add dev $DEVICE protocol ip parent 1: prio 5 u32 match ip protocol 0 0x00 flowid 1:3
}

case "$ACTION" in
	ifup)
		# only work after the first normal startup
		# also: no need to test, if enabled
		[ -e '/var/etc/olsrd.conf' ] && {
			# INTERFACE = e.g. 'wlanadhocRADIO1' or 'cfg144d8f'
			# DEVICE    = e.g. 'wlan1-1'
			olsrd_interface_needs_adding && {
				. /etc/rc.common /etc/init.d/olsrd restart
			}

			grep -s ^'Interface ' '/var/etc/olsrd.conf' | grep -q "\"$DEVICE\"" && {
				olsrd_traffic_control_add
			}
		}
	;;
esac
