#!/bin/sh

case "$ACTION" in
	ifup)
		uci -q get network.$INTERFACE.dyndns >/dev/null && {
			. /tmp/loader
			echo >>$SCHEDULER_IMPORTANT "_wget do \"$( uci -q get network.$INTERFACE.dyndns )\""
		}

		[ "$( uci -q get network.$INTERFACE.proto )" = 'dhcp' ] && {
			. /tmp/loader
			echo >>$SCHEDULER '/etc/init.d/S41build_static_netparam'
		}
	;;
esac
