#!/bin/sh

case "$ACTION" in
	ifup)
		uci -q get network.$INTERFACE.dyndns >/dev/null && {
			. /tmp/loader
			echo >>$SCHEDULER_IMPORTANT "_wget do $( uci -q get network.$INTERFACE.dyndns )"
		}

		[ "$( uci -q get network.$INTERFACE.proto )" = 'dhcp' ] && {
			. /tmp/loader
			echo >>$SCHEDULER '/etc/init.d/S41build_static_netparam'
		}
	;;
	ifupdate)
		# wrong place but works:
		[ -e '/etc/crontabs/root' ] && {
			. /tmp/loader
			[ "$( _stopwatch stop '/tmp/CRON_LASTCALL' interim,nolog,seconds )" -gt 3000 ] && {
				# locking maybe unneeded
				mkdir '/tmp/LOCK_dhcpscript_cron_restart' && {
					_stopwatch start '/tmp/CRON_LASTCALL' global
					_log do hotplug_dyndns daemon alert "cron died, restarting"
					/etc/init.d/S51crond_fff+ restart
					rm -fR '/tmp/LOCK_dhcpscript_cron_restart'
				}
			}
		}
	;;
esac
