#!/bin/sh

# this outputs an inital loader which can be sourced for each 'class', e.g. for class 'wifi':
#
# _wifi ()
# {
#	  test -z "$GLOBAL_wifi" && . /etc/kalua/wifi && GLOBAL_wifi=1	# load class_functions and set global var for remembering
# 	  local FUNCTION="$1"						# save first arg
#	  shift								# shift all args, loosing $1
#	  _wifi_$FUNCTION "$@"						# pass all args to real function
# }
#
# idee: man koennte beim initialen einsourcen die _wifi() mit dranhaengen, ohne den "schon gesourced?"-test

_init ()
{
	local BASE="/etc/kalua"		# scriptbase, simply throw your 'class' here
	local DEST="/tmp/loader"	# scripts can source this file and use all 'classes'
	local CLASS
	
	for CLASS in $(find $BASE -type f); do {
		CLASS="$( basename $CLASS )"
		echo -en "_$CLASS(){\ntest -z \"\$GLOBAL_$CLASS\" && . $BASE/$CLASS && GLOBAL_$CLASS=1;local F=\$1;shift;_${CLASS}_\$F \"\$@\"\n}\n" >>"$DEST"
	} done
}

_init
