#!/bin/sh

# files with status-info
SYSLOG="/var/log/messages"
SYSLOG_SAFED="/www/safed_syslog_fff+"
TRACE_INET_GATEWAY="/tmp/archiv_trace_inet_gateway_fff+"
TEST_NEIGHBOUR_SPEED="/tmp/archiv_test_neighbour_speed_fff+"
SERVICE_INFO="/tmp/archiv_service_announcement_fff+"
CLIENTS_WIFI="/tmp/network_wifi_fff+"
CLIENTS_LAN="/tmp/network_lan_fff+"
CLIENTS_WAN="/tmp/network_wan_fff+"
CLIENTS_ALL="/tmp/network_clients_fff+"
OLSR_LAN="/www/placeholder_for_showing_that_lan_olsr_is_spoken"
OLSR_WAN="/www/placeholder_for_showing_that_wan_olsr_is_spoken"

# infosite-related stuff
WIKI_MAIN_URL="http://wireless.subsignal.org"
WIKI_ARTICLE_1="title=Vorlage:Startseite.Aktuelles"
WIKI_ARTICLE_1_HEADLINE="Aktuelle Meldungen"
WIKI_ARTICLE_2="title=Vorlage:Spendenaufruf"
WIKI_ARTICLE_2_HEADLINE="Spendenaufruf"
WIKI_ARTICLE_3="title=Vorlage:Nutzungsbedingungen"
WIKI_ARTICLE_3_HEADLINE="Nutzungsbedingungen"
NEWSSERVER_URL="http://news.weimarnetz.de/newsgroups"
LATEST_NEWS_URL="http://www.weimarnetz.de/latestnews.html"
LATEST_NEWS_HEADLINE="Aktuelle Diskussionen"
