#!/bin/sh

case "$ACTION" in
	'add')
		case "$DEVPATH" in
			# /devices/platform/101c0000.ehci/usb1/1-1/1-1:1.0/host0/target0:0:0/0:0:0:0/block/sda
			# /devices/platform/101c0000.ehci/usb1/1-1/1-1:1.0/host0/target0:0:0/0:0:0:0/block/sda/sda1
			*'/block/sd'[a-z]'/sd'[a-z][0-9])
				. /tmp/loader
				_storage automount
			;;
		esac
	;;
esac
