#!/bin/sh
case "$QUERY_STRING" in
	REDIRECTED=1*);;
	*)
		read WIFIADR FORKS 2>/dev/null </tmp/WELCOME_HELPER
		[ ${#FORKS} -gt 1 -o -z "$FORKS" ] && {
			cat /tmp/weblogin_cached_for_overload 2>/dev/null && exit
		}
	;;
esac
echo -n >>/tmp/WELCOME_HELPER "#"	# raise counter, see cron.minutely
. /tmp/loader
[ -e /tmp/weblogin_cached_for_overload ] || {
	case "$( uci get system.@weblogin[0].enabled )" in
		1)
			case "$( nvram get fff_weblogin_password2mobile )" in
				1)
					_weblogin htmlout_loginpage "" "" "" "" "http://$WIFIADR" "(cache)" "mobile_mode" >/tmp/weblogin_cached_for_overload
				;;
				*)
					_weblogin htmlout_loginpage "" "" "" "" "http://$WIFIADR" "(cache)" >/tmp/weblogin_cached_for_overload
				;;
			esac
		;;
		*)
			_weblogin htmlout_gatepage >/tmp/weblogin_cached_for_overload
		;;
	esac
}
. /www/cgi-bin-welcome_stage2
