#!/bin/sh
. /tmp/loader

eval $( _http query_string_sanitize )
_http header_mimetype_output "text/html"
_webadmin db_defs

eval $( _webadmin action $FORM_ACTION )		# DESC_SHORT / DESC_LONG

echo -n "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN' 'http://www.w3.org/TR/html4/strict.dtd'>"
echo -n "<html><head><title>WLAN-System: $DESC_SHORT</title>$( _webadmin htmlout_javascript )"
echo -n "<META HTTP-EQUIV='cache-control' CONTENT='no-cache'></head><body bgcolor='white'>"
echo -n "<table cellspacing='2' cellpadding='2' border='0' width='100%'><tr>"

_webadmin htmlout_links2category

echo -n "</tr><tr><td colspan='5' bgcolor='#D3D3D3'>"
echo -n "<br><b>&Uuml;bersicht</b>:&nbsp;&nbsp;WLAN-System <b>&rarr;</b> Benutzerverwaltung <b>&rarr;</b> $DESC_SHORT :"
echo -n "<br><br></td></tr></table>"

case $FORM_ACTION in
	user_add)
		if [ "$FORM_SEND" = "true" ]; then
			_webadmin formsend_useradd
		else
			_webadmin htmlout_form_useradd
		fi
	;;
	user_edit|user_show)
		if [ "$FORM_SEND" = "true" ]; then
			_webadmin formsend_useredit
		else
			_webadmin htmlout_form_useredit
		fi
	;;
esac

echo -n "</body></hmtl>"
