#!/bin/sh

. /etc/functions_base_fff+ && func_need log http
. /www/cgi-bin-admin_functions

eval $(func_http_sanitize_query_string)
func_http_header_mime_output "text/html"

eval $(func_admingui_get_action $FORM_ACTION)		# DESC_SHORT / DESC_LONG

echo -n "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN' 'http://www.w3.org/TR/html4/strict.dtd'>"
echo -n "<html><head><title>WLAN-System: $DESC_SHORT</title>$( func_admingui_javascript )</head><body bgcolor='white'>"
echo -n "<table cellspacing='2' cellpadding='2' border='0' width='100%'><tr>"

func_admingui_links2category

echo -n "</tr><tr><td colspan='5' bgcolor='#D3D3D3'>"
echo -n "<br><b>&Uuml;bersicht</b>:&nbsp;&nbsp;WLAN-System <b>&rarr;</b> Benutzerverwaltung <b>&rarr;</b> $DESC_SHORT :"
echo -n "<br><br></td></tr></table>"

case $FORM_ACTION in
	user_add)
		if [ "$FORM_SEND" = "true" ]; then
			func_admingui_user_add_form_was_send
		else
			func_admingui_user_add_form
		fi
	;;
esac

echo -n "</body></hmtl>"
