#!/bin/sh
case "$QUERY_STRING" in
	REDIRECTED=1*);;
	*)
		read WIFIADR FORKS 2>/dev/null </tmp/WELCOME_HELPER
		[ ${#FORKS} -gt 4 ] && {
			echo -en "Content-type: text/html\n\n<html><head><title>Weblogin &middot; Captive portal &middot; Splash screen &middot; $WIFIADR</title></head><body bgcolor='#DAFBE8'><br><p><big>&nbsp;<tt>[de]</tt>&nbsp;Netzwerk-&Uuml;berlastung - bitte 3 Minuten warten.<br>&nbsp;<tt>[en]</tt>&nbsp;Network overload - please wait 3 minutes.<br>&nbsp;<tt>[fr]</tt>&nbsp;Surcharge du r&eacute;seau - s'il vous pla&icirc;t attendre 3 minutes.</big></p><p><form method='post' action='http://$WIFIADR/cgi-bin-welcome?REDIRECTED=1'><input type='hidden' name='FORM_ENFORCE' value='true'><input type='submit' name='' value='Warnung ignorieren &sdot; Ignore &sdot; Ignorer'></form></p></body></html>"
			exit
		}
	;;
esac
echo -n >>/tmp/WELCOME_HELPER "#"	# raise counter, see cron.minutely
. /www/cgi-bin-welcome_stage2
