#!/bin/sh
[ "$REQUEST_METHOD" != "POST" ] && {
	read WIFIADR FORKS 2>/dev/null </tmp/WELCOME_HELPER		# read LOAD NOP </proc/loadavg
	[ ${#FORKS} -gt 4 ] && {
		echo -en "Content-type: text/html\n\n<html><head><title>Weblogin | $WIFIADR</title></head><body><big><br>&nbsp;<tt>[de]</tt>&nbsp;Netzwerk-&Uuml;berlastung - bitte 3 Minuten warten.<br>&nbsp;<tt>[en]</tt>&nbsp;Network overload - please wait 3 minutes.<br>&nbsp;<tt>[fr]</tt>&nbsp;Surcharge du r&eacute;seau - s'il vous pla&icirc;t attendre 3 minutes.</big><br><br><form method='post' action='http://$WIFIADR/cgi-bin-welcome?REDIRECT=1'><input type='hidden' name='FORM_ENFORCE' value='true'><input type='submit' name='' value='Warnung ignorieren &sdot; Ignore &sdot; Ignorer'></form><br><small>&nbsp;&nbsp;technical info:<br>&nbsp;&nbsp;load is ${LOAD:-1}<br>&nbsp;&nbsp;httpd forked ${#FORKS}x</small></body></html>"
		exit
	}
}
echo -n >>/tmp/WELCOME_HELPER "#"	# raise counter, see cron.minutely
. /www/cgi-bin-welcome_stage2
