#!/bin/sh
. /tmp/loader

MODE="${1:-unset}"
MAC="${2:-ff:00:00:00:00:00}"		# fixme! this enforces an invalid mac, see sanitizer_mac()
IP="${3:-127.0.0.1}"
HOST="${4:-unset}"

case "$MAC" in
	*"-"*)
		_log do dhcp_script daemon info "ignore non-ethernet events: $MAC"
		exit
	;;
esac

if [ -n "$DNSMASQ_INTERFACE" ]; then
	DEV="$DNSMASQ_INTERFACE"
else
	DEV="$( _net ip2dev $IP )"
fi

case "$DEV" in
	 $WANDEV) TYPE="wan" ;;
	 $LANDEV) TYPE="lan" ;;
	$WIFIDEV) TYPE="wifi" ;;
	  $LODEV) TYPE="loopback" ;;
	       *) TYPE="unknown" ;;
esac

[ "$MODE" = "old" ] || _log do dhcp_$MODE daemon info "'$MAC' is from '$DEV' = ${TYPE}-DEV"

case "$MODE" in
	add|old)
		case "$( uci get system.@weblogin[0].enabled )" in
			""|0)
			;;
			*)
				[ "$HOST" = "check_if_reachable" ] && {
					_netfilter user_reachable "$MAC" "$IP" >/dev/null || exit 0
				}

				[ "$MODE" = "old" ] && {
					_netfilter user_probe "$MAC" && exit 0
				}

				USER="$MAC"
				NODE_HOSTNAME="$( uci get system.@system[0].hostname )"
				SIGNAL="${NODE_HOSTNAME}_dhcp-${MODE}"				# keyword 'dhcp' is important for login_check()
				export REMOTE_ADDR="$IP"

				if _weblogin login_check "$USER" "" "$MAC" "$SIGNAL" ; then
					# for "very fast unsplashing" and not showing 'please use credentials'
					iptables -t mangle -I PREROUTING -j ACCEPT
					_log do $SIGNAL daemon info "[OK] _weblogin login_check $USER"
					_netfilter user_add "$MAC" "$IP"
					# remove the hack for "very fast unsplashing"
					iptables -t mangle -D PREROUTING -j ACCEPT
				else
					if _weblogin login_check "$USER" "$NODE_HOSTNAME" "$MAC" "$SIGNAL" ; then
						_log do $SIGNAL daemon info "[OK] _weblogin login_check $USER/$NODE_HOSTNAME (2nd try)"
						_netfilter user_add "$MAC" "$IP"
					else
						_log do $SIGNAL daemon info "[ERR] _weblogin login_check $USER/$NODE_HOSTNAME"
					fi
				fi
			;;
		esac

		case "$CONFIG_PROFILE" in
			ffweimar*)
				if [ "$TYPE" = "lan" ]; then
					_log do dhcp_$MODE daemon info "this profile is always auto-unsplashed"
					_netfilter user_add "$MAC" "$IP"
				else
					_log do dhcp_$MODE daemon info "'$MAC' is not from lan, exit"
					exit
				fi
			;;
		esac
	;;
	del)
		if [ "$( uci get system.@weblogin[0].dhcpautologout )" = "1" ]; then
			_scheduler add "_netfilter user_del $MAC"
		else
			ip neigh change $IP dev $DEV lladdr $MAC nud reachable
		fi
	;;
esac

[ "$HOST" = "check_if_reachable" ] || exit 0	# no croncheck during bootup

pidof crond >/dev/null || {		# wrong place but works
	[ -e "/tmp/dhcpscript_cron_restart" ] || {
		touch "/tmp/dhcpscript_cron_restart"
		_log do watch_cron daemon alert "cron died, restarting"
		/etc/init.d/S51crond_fff+ start
		rm "/tmp/dhcpscript_cron_restart"
	}
}
