#!/bin/sh
. /tmp/loader

# todo:
# with/without OLSR on all interfaces? or specific interfaces?

netparam_for_uci_devices ()
{
	for DEVICE in loopback wlan lan wan ; do {

		case $DEVICE in
			loopback) NAME="LO" ;;
			wlan)	  NAME="WIFI" ;;
			lan)	  NAME="LAN" ;;
			wan)	  NAME="WAN" ;;
		esac

		IFNAME="$(  uci -q get network.$DEVICE.ifname  )"
		ADDRESS="$( uci -q get network.$DEVICE.ipaddr  )"
		NETMASK="$( uci -q get network.$DEVICE.netmask )"
		MTU="$( ip link show dev "${IFNAME:-nonexistent_$DEVICE}" | sed -n 's/^.* mtu \([0-9]*\).*/\1/p;q' )"

		echo "${NAME}DEV=$IFNAME"
		echo "${NAME}MTU=$MTU"
		echo "${NAME}ADR=$ADDRESS"
		echo "${NAME}MSK=$NETMASK"

		BROADCAST=;NETWORK=;PREFIX=
		[ -n "$MTU" ] && eval $( ipcalc.sh $ADDRESS $NETMASK )

		echo "${NAME}BRC=$BROADCAST"
		echo "${NAME}NET=$NETWORK"
		echo "${NAME}PRE=$PREFIX"
		echo "${NAME}OLSR="
	} done
}

_build ()
{
	local FUNC="build"
	local FILE="/tmp/NETPARAM"

	_log do $FUNC daemon debug "working"

	_uci is_oldstyle || {
		_log do $FUNC daemon debug "building '$FILE' for an uci-device"
		netparam_for_uci_devices >$FILE
		return 0
	}

	/rom/usr/bin/netparam >$FILE && {
		_log do $FUNC daemon debug "successfully build '$FILE'"
		return 0
	}
	
	_log do $FUNC daemon crit "error during build, trying pivot-root"
	/usr/bin/netparam >$FILE && {
		_log do $FUNC daemon crit "success building '$FILE'"
		return 0
	}
	
	_log do $FUNC daemon crit "error, could not build '$FILE'"
	return 1
}

_restore_original_netparam ()
{
	local FUNC="restore_original_netparam"
	local ORIGINAL="/rom/usr/bin/netparam"
	local COPY="/usr/bin/netparam"

	_uci is_oldstyle || return 0

	[ "$( _file hash "$ORIGINAL" )" = "$( _file hash "$COPY" )" ] && {
		_log do $FUNC daemon debug "netparam seems to be fine"
		return
	}	

	_log do $FUNC daemon debug "HASH's differ - replacing netparam in filesystem with copy in rom"
	
	cp $ORIGINAL $COPY || {
		_log do $FUNC daemon debug "error during copy? trying to symlink"
		
		>$COPY		# create 0 byte-file
		rm $COPY
		ln -s $ORIGINAL $COPY && {
			_log do $FUNC daemon debug "symlinking went fine"
			return
		}
		_log do $FUNC daemon crit "error during symlinking"
		return 1
	}
	
	_log do $FUNC daemon debug "successfully replaced"
}

if [ -e /tmp/BOOT ] || [ "$1" = "restore_original_netparam" ]; then
	_restore_original_netparam
fi

_build

/etc/kalua_init		# this includes a static version of NETPARAM
			# fixme! hook when 'ifup wan' gets an dhcp-lease
