#!/bin/sh
. /tmp/loader

# wget -qO /dev/null "http://127.0.0.1/cgi-bin-rrd1.html?START=end-24h"		# stats,wifi (signal/noise,rate,olsr-traffic)
# scp /tmp/rrd/img/end-24hWLAN_WLA_STATS.png intercity-vpn.de:/var/www/99.png

# idee:
# random node-IP in mesh with 1 hop or 2 hops -> IP = main-interface
# [ ! -e contact_$IP ] || [ "$(cat contact_${IP}_fetched)" -lt $(( $(_system date unixtime) - 86400 )) ] && {
# 	wget -qO - http://$IP/cgi-bin-contact.html | sed -n '/<H1>Kontakt<\/H1>/,$p'| sed '/^<\/TABLE>/q' >/tmp/node_$IP
#
#	[ "$( md5sum /tmp/node_$IP | cut -d' ' -f1 )" = "c9614a47d313e7be6f6cf2a7b88d5d2b" ]; then
#		echo "empty"
#	}
# }			# ~ 800 Bytes if all fields are set

_watch flash_free_space

_watch wifi_mode || sleep 30		# lets settle down to see some neighs

_olsr check_plausi $( _olsr neighs ) || _olsr daemon restart "plausi_check_failed"

_watch vpnc
_watch system_time
_watch hanging_broadcom_wifi
_watch hanging_xrelayd
_watch rrd_integrity
_watch zombie_processes
_watch dns_resolution
_watch pppoe
_watch netserver
_watch webcam
_watch webserver
_watch sshd_or_telnet
_watch random_node_id
