#!/bin/sh

# "Stick to portable constructs where possible, and you will make somebody's life easier in the future. Maybe your own."

# this outputs an inital small '/tmp/loader' which can be sourced
# and automatically solve the dependencies for all 'classes' and it methods(),
# e.g. for class '_system' and method architecture()
#
# TODO: method 'unload'
# TODO: method 'help'
# TODO: show stats for each call: sed -n "s/^\(.*\) ().*/\1/p" $BASEDIR/$CLASS | wc -l | sed 's/ //g'

while read -r LINE; do {
	# none /run/user tmpfs rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755 0 0
	#                                      ^^^^^^ does not matter, we only 'source' shellscripts
	case "$LINE" in
		*' tmpfs rw,'*)
			set -- $LINE
			mkdir -p "$2/kalua" 2>/dev/null && {
				TMPDIR="$2/kalua"
				break
			}
		;;
	esac
} done <'/proc/mounts'
logger -s -- "$0: [OK] use \$TMPDIR which points to '${TMPDIR:=/tmp}'"
chmod -R 777 "$TMPDIR"

BASEDIR="$( dirname $0 )/kalua"		# e.g. /etc/kalua_init -> /etc | scriptbase, simply put your 'class'-files in
POOLDIR="$TMPDIR/kalua_pool"
LOADER="$TMPDIR/loader_$$"
LOADER_FINAL="$TMPDIR/loader"		# later '$LOADER_ENTRY' is symlinked to it
LOADER_ENTRY='/tmp/loader'
mkdir -p "$POOLDIR"

# _ s    http		-> show methods for class 'http'
# _ http arg1 argX	-> include + start
# _ http		-> list methods and include
# _ http include	-> include only
# _ t			-> test if loader already included
# _			-> list classes

cat >"$LOADER" <<EOF
#!/bin/sh
_ t 2>/dev/null&&return

_(){ case \$1 in
s)sed -n "/;}$/! s/^\(_\${2}_.*\)()/\1/p" $BASEDIR/\$2|sort;;
i)local a=\${3-s} b=\$2;shift 3;_ \$b;case \$a in include);;*)_\${b}_\$a "\$@";;esac;;
t);;*)[ \$1 ]&&. $POOLDIR/\$1||ls -1 $POOLDIR|grep ^[a-z]|sort|sed s/^/_/;;esac;}

EOF

# generate loader and add methods 'show' + 'include'
for CLASS in $BASEDIR/*; do {
	CLASS="${CLASS##*/}"	# quick basename

	cat >"$POOLDIR/$CLASS" <<EOF
_$CLASS(){ local a=\${1-s};shift;_${CLASS}_\$a "\$@";}
_${CLASS}_s(){ _ s $CLASS;}
_${CLASS}_include(){ :;}
. $BASEDIR/$CLASS
EOF
	if sh -n "$BASEDIR/$CLASS"; then
		echo >>"$LOADER" "_$CLASS(){ _ i $CLASS \"\$@\";}"
	else
		echo >>"$LOADER" "_$CLASS(){ logger -s -- class_error: _$CLASS \$@ ;}"
	fi

	# include GLOBAL_VARS which must be in head-section of CLASS, e.g. MYVAR=123
	# TODO: rewrite with 1 sed-call
	read -r LINE _ <"$BASEDIR/$CLASS"
	case "$LINE" in
		'#!/bin/sh'*)
			sed -n "2,/^_$CLASS/{/^[A-Z]/p}" "$BASEDIR/$CLASS" >>"$LOADER"
		;;
	esac
} done

# include own extensions
for FILE in "$0.user_"* "$0.user"; do {
	[ -e "$FILE" ] && . "$FILE" >>"$LOADER"
} done

# symlink /tmp/loader -> copy in ramdisc
mv "$LOADER" "$LOADER_FINAL"
[ -h "$LOADER_ENTRY" ] || {
	[ -e "$LOADER_ENTRY" ] && rm "$LOADER_ENTRY"
	ln -s "$LOADER_FINAL" "$LOADER_ENTRY"
}

logger -s -- "$0: [OK] done '$LOADER_ENTRY' using files in $POOLDIR"
logger -s -- "$0: [OK] reload new loader with '_(){ false;}; . $LOADER_ENTRY' if in interactive shell"
