#!/bin/sh
. /tmp/loader

# logger "$0: query: '$QUERY_STRING'"		# fast debug

eval $( _http query_string_sanitize "$0" )

_http header_mimetype_output "text/html"

cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<html><head><title>$( _i18n get "$LANG" wifi_system ): $( _i18n get "$LANG" rights_management )</title>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=ISO-8859-15">
<META HTTP-EQUIV='cache-control' CONTENT='no-cache'></head>

<body bgcolor='white'>
EOF

[ -n "$FORM_PROFILE" ] && {
	echo '<h1>thank you, the device is restarting now and ready to use</h1>'
	echo "<h3>please apply a sticker with the number $FORM_NODENUMBER to your device.</h3>"
	echo "<h3>the new IP-adress of your device is '$( _ipsystem do 'LANADR' $FORM_NODENUMBER )'."

	echo '</body></html>'
	exit 0
}

cat <<EOF
<h3>please configure your mesh-network-device</h3>

<table cellspacing='0' cellpadding='0' border='1'>

<form action=''>

<tr><td>
profile name
</td><td>
<select name='FORM_PROFILE'>
<option>freifunk</option>
<option>hotel</option>
<option selected>FOSSASIA</option>
</select>
</td></tr>

<tr><td>
WiFi-mode
</td><td>
<select name='FORM_WIFIMODE'>
<option>AP/Master</option>
<option>AdHoc</option>
<option selected>Hybrid (AP &plus; AdHoc together, recommended)</option>
</select>
</td></tr>

<tr><td>
Location of this router<br>(this is for future maintenance <br>purposes and will be the hostname)
</td><td>
<input type='text' size='32' name='FORM_HOSTNAME'>
</td></tr>

<tr><td>
give your device a unique number in<br> your network, e.g. 168
</td><td>
<input type='text' size='4' name='FORM_NODENUMBER'>
</td></tr>

<tr><td>
direct Internet-connection via WAN-Port?
</td><td>
<input type='checkbox' name='FORM_INETOFFER' value='dhcp'>
</td></tr>

<tr><td>
&nbsp;
</td><td>
&nbsp;<br>&nbsp;
<input type='submit' value='OK' name='submit'>
</td></tr>

</form>

</table>

</body>
</html>
EOF
