#!/bin/sh
. /tmp/loader

_webconfig htmlout_head
eval $( _http query_string_sanitize )

if [ "$REQUEST_METHOD" = "POST" ]; then			# do this, if submit-button was pressed		(POST-method)

	if [ "$gui" = "user" ]; then			# USER-Menu (rights-management)
		_webconfig htmlout_gui_user_submitted
	else						# CONFIG-Menu after "profile" was selected
		_webconfig form_select_profile_process
	fi
else 							# do this, if ONLY formular is called 		(GET-method)
	case "$gui" in
		user)
			_webconfig build_vars_gui_user
			_webconfig build_lang_gui_user
			_webconfig htmlout_gui_user
		;;
		*)
			_webconfig htmlout_form_select_profile
		;;
	esac
fi

_webconfig htmlout_foot
