#!/bin/sh

# this works with a 'TP-LINK TL-WR1043ND'
CHICKENDOOR_GPIO_BREAK='/sys/class/leds/tp-link:green:system/brightness'
CHICKENDOOR_GPIO_MOTOR='/sys/class/leds/tp-link:green:usb/brightness'

_chickendoor_state()
{
	local funcname='chickendoor_state'
	local state="$1"
	local file="$PERMDIR/$funcname"

	case "$state" in
		enabled)
			test -e "$file"
		;;
		up|down)
			echo >"$file" "$state"
		;;
		open|closed)
			echo >"$file" "$state"
			_log shell_is_interactive && return 0

			local webcam_port=33333
			local webcam_link="http://bwireless.mooo.com:$webcam_port/webcam.jpg"
			local greetings='Gruesse von der automatischen Huehnerklappe.'
			local housekeeper="$( _chickendoor housekeeper )"
			local housekeeper_next="$( _chickendoor housekeeper 'next' )"
			local subject_pre="Schlachthof: $( _i18n get 'de' 'dayname_today' )"

			case "$state" in
				open)
					_mail send_telegram "$housekeeper" \
						"$subject_pre frueh: Huehnerklappe wurde geoeffnet." \
						"Sonnenaufgang heute: $( _system date unixtime2date "$( _date sunrise_today )" )\n" \
						"Sonnenuntergang heute: $( _system date unixtime2date "$( _date sunset_today )" )\n\n" \
						"Alles i.O.\nKeine Stoerung - den Huehnern gehts gut.\n\n" \
						"Bilder hier:\n$webcam_link\n\n$greetings"

					[ "$housekeeper" = "$housekeeper_next" ] || {
						_mail send_telegram "$housekeeper_next" \
							"$subject_pre - Huehnerstall: naechste Woche bist du dran" \
							"Wunderschoenen guten Morgen.\n" \
							"Denk daran, das du ab morgen dran bist,\n"
							"und macht eine saubere Uebergabe...\n"
					}
				;;
				closed)
					_mail send_telegram "$housekeeper" \
						"$subject_pre abend: Huehnerklappe wurde geschlossen." \
						"Sonnenuntergang heute: $( _system date unixtime2date "$( _date sunset_today )" )\n\n" \
						"Alles i.O.\nKeine Stoerung - den Huehnern gehts gut.\n\n" \
						"Bilder hier:\n$webcam_link\n\n$greetings"
				;;
			esac
		;;
		get|*)
			cat "$file"
		;;
	esac
}

_chickendoor_toggle()
{
	_chickendoor state 'enabled' || return 0

	case "$( _chickendoor state 'get' )" in
		'open')
			_chickendoor evening_close
		;;
		'closed'|*)
			_chickendoor morning_open
		;;
	esac
}

_chickendoor_housekeeper()
{
	local option="$1"	# <empty>|next
	local o calendar_week
	local bb='bb|npl.de'
	local jakob='jakob.aschenbach|gmx.de'
	local jan='zirkuswagenbau|web.de'
	local kurt='kurdinat|akut-guitars.de'
	local danny='gesellschertel|web.de'
	local robert='robert.p.frech|gmail.com'
	local ina='michalski|steinhauerei-weimar.de'

	if [ "$option" = 'next' ]; then
		calendar_week="$( date +%U )"	# sunday = first day of week
	else
		calendar_week="$( date +%W )"
	fi

	case "$calendar_week" in
		49|04|11|18|25|32|39|46) o="$jan" ;;
		50|05|12|19|26|33|40|47) o="$jakob" ;;
		51|06|13|20|27|34|41|48) o="$ina" ;;
		52|07|14|21|28|35|42|49) o="$danny" ;;
		01|08|15|22|29|36|43|50) o="$kurt" ;;
		02|09|16|23|30|37|44|51) o="$robert" ;;
		03|10|17|24|31|38|45|52) o="$bb" ;;
	esac

	echo "$o $bb" | sed 's/|/@/g'
}

_chickendoor_evening_close()
{
	local funcname='chickendoor_evening_close'
	local interval="${1:-155}"

	_chickendoor down
	_log sleep $funcname "$interval" step 1
	_chickendoor stop

	_chickendoor state 'closed'
}

_chickendoor_morning_open()
{
	local funcname='chickendoor_morning_open'
	local interval="${1:-15}"

	_chickendoor up
	_log sleep $funcname "$interval" step 1
	_chickendoor stop

	_chickendoor state 'open'
}

_chickendoor_up()	# TODO: up/down can change if spindle overturns
{
	_chickendoor release
	echo 255 >"$CHICKENDOOR_GPIO_MOTOR"
	_chickendoor state 'up'
}

_chickendoor_down()
{
	_chickendoor release

	_log it chickendoor_down daemon info 'done'
	_wifi led on

	_chickendoor state 'down'
}

_chickendoor_stop()
{
	_log it chickendoor_stop daemon info 'done'
	echo '0' >"$CHICKENDOOR_GPIO_MOTOR"

	_wifi led off
	_chickendoor brake
}

_chickendoor_release()
{
	_log it chickendoor_release daemon info 'break: released'
	echo '0' >"$CHICKENDOOR_GPIO_BREAK"
}

_chickendoor_brake()
{
	_log it chickendoor_brake daemon info 'brake: holding'
	echo '255' >"$CHICKENDOOR_GPIO_BREAK"
}
