#!/bin/sh

_cron_daemon_restart()
{
	local func="cron_daemon_restart"
	local reason="$1"

	_log it $func daemon info "[START] $reason"
	/etc/init.d/*crond* restart
	_log it $func daemon info "[READY]"
}

_cron_vpnserver()
{
	local funcname='cron_vpnserver'
	local ip="${1:-84.38.67.43}"
	local firstrun="$TMPDIR/firstrun_$funcname"
	local public_ip port
	local loopback_interface='lo'

	read -r UP REST </proc/uptime
	[ ${UP%.*} -lt 180 ] && return 0

	[ -e "$firstrun" ] || {
		touch "$firstrun"
		_log it $funcname daemon sms 'firstrun/bootup'

		# left from default init-script with dummy-config
		pidof vtund && killall vtund

		[ -e '/etc/olsrd.conf' ] || {
			public_ip="$( _net get_external_ip )"
			port="$( _vpn innercity_master_vtund get_port )"

			get_plugin()
			{
				local name="$1"
				# print highest number (sorting)
				for file in "/usr/local/lib/olsrd_$name.so."* "/usr/lib/olsrd_$name.so."*; do {
					[ -e "$file" ] && {
						basename "$file"
						return 0
					}
				} done
			}

			# new vtun-interfaces are automatically added in vpn_innercity_master_iface()
			# TODO: own func + configure MainIP on loopback/VPN? and use for service
			cat >'/etc/olsrd.conf' <<EOF
DebugLevel 0

LoadPlugin "$( get_plugin 'txtinfo' )"
 {
	PlParam "accept" "127.0.0.1"
	PlParam "listen" "0.0.0.0"
	PlParam "port" "2006"
 }

LoadPlugin "$( get_plugin 'jsoninfo' )"
 {
	PlParam "accept" "127.0.0.1"
	PlParam "listen" "0.0.0.0"
	PlParam "port" "9090"
 }

LoadPlugin "$( get_plugin 'nameservice' )"
 {
	PlParam "name" "$HOSTNAME"
	PlParam "service" "http://$HOSTNAME:80|tcp|VPN-hideandseek:$public_ip:$port"
 }

Hna4
 {
	0.0.0.0 0.0.0.0		# we have internet
 }

Interface "$loopback_interface"
 {
	# values for speed 7
	Ip4Broadcast 255.255.255.255
	HelloInterval 4.0
	HelloValidityTime 175.0
	TcValidityTime 700.0
	TcInterval 3.0
	MidInterval 35.0
	MidValidityTime 700.0
	HnaInterval 14.0
	HnaValidityTime 175.0
 }
EOF
			ln -s '/etc/olsrd.conf' '/var/etc/olsrd.conf'
		}
	}

	read -r LOAD REST </proc/loadavg

	case "$LOAD" in
		0.0*|0.1*|0.2*|0.3*)
			[ -e '/tmp/DEBUG' ] && rm '/tmp/DEBUG'
		;;
		*)
			ps >>$PERMLOG
			touch '/tmp/DEBUG'
			_log it $funcname daemon alert "high load: $LOAD / $REST"
		;;
	esac

	ping -s 64 -c1 "$ip" >/dev/null || _log it $funcname daemon alert "ping to $ip failed"
	[ -e '/usr/sbin/olsrd' ] && _olsr build_overview_static
	[ -e '/usr/local/sbin/vtund' ] && _vpn innercity_master_vtund check_on_server
	cron.build_netjson.sh "${CONFIG_PROFILE%_*}" >'/var/www/map.json'

	# uptime.sec->minutes divideable (without rest) by 360? -> each 360 mins
	[ $(( $(( ${UP%.*} / 60 )) % 360 )) -eq 0 ] && {
		_firmware update_pmu
		_watch archivsize "$PERMLOG" 200 300
	}

	_scheduler run
	case "$( date '+%H:%M' )" in
		*':00'|*':15'|*':30'|*':45')
			_watch archivsize '/tmp/messages' 2000
			cron.monitoring send_alive_message
		;;
		'04:05')
			_vpn innercity_master_vtund stop
		;;
		'04:06')
			_vpn innercity_master_vtund start
		;;
	esac

	# TODO: build an interactive 'vpn_setup'
	# TODO: compile 'uci'
	#
	### install 'innercity-VPN' on a fresh debian7 VPS-server:
	# apt-get -y install build-essential bison flex zlib1g-dev liblzo2-dev libncurses5-dev libreadline6-dev libcurl4-openssl-dev lsof
	# enable tun/tap via webinterface
	# maybe: http://lowendbox.com/blog/yes-you-can-run-18-static-sites-on-a-64mb-link-1-vps/
	#
	### OLSR:
	# wget -O olsrd-latest.tar.bz2 http://www.olsr.org/releases/latest.tar.bz2
	# tar xjf olsrd-*; cd olsrd-*
	# make build_all && make install_all
	# cd ..; rm -fR olsrd-*
	# mkdir -p /var/etc
	# ln -s /usr/local/sbin/olsrd /usr/sbin/olsrd
	# ln -s /etc/olsrd.conf /var/etc/olsrd.conf
	#
	### OLSRv2:
	# apt-get -y install cmake pkg-config libnl-3-dev libnl-genl-3-dev libtomcrypt-dev
	# for cmake 3.x:
	#   // http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04
	#   apt-get install python-software-properties
	#   apt-get install software-properties-common
	#   add-apt-repository ppa:george-edison55/cmake-3.x
	#   apt-get update
	#   apt-get install cmake
	# git clone http://olsr.org/git/oonf.git
	# cd oonf/build && cmake .. && make
	# ./olsrd2_static --version
	#
	### TINC:
	# wget http://www.tinc-vpn.org/packages/tinc-1.1pre11.tar.gz
	# tar xzf tinc-*; cd tinc-*
	# ./configure && make && make install
	# rm -fR tinc-*
	#
	### TINC-config:
	# wget -O vpnconfig-master.tar.gz https://github.com/weimarnetz/vpnconfig/archive/latest.tar.gz
	# tar xzf vpnconfig-*; cd vpnconfig-*
	# mkdir -p /etc/tinc/wnvpn
	# cp -vR tinc/wnvpn/* /etc/tinc/wnvpn
	# cp -vR tinc/wnvpn/* /usr/local/etc/tinc/wnvpn
	# READ: https://github.com/weimarnetz/vpnconfig#ip-schema (e.g. 'vpn4' = .52)
	# vi /etc/tinc/wnvpn/tinc-up
	# vi /etc/tinc/wnvpn/tinc-down
	# vi /etc/tinc/wnvpn/tinc.conf
	# tinc -n 'wnvpn' init 'vpn4'
	# ls -l /usr/local/etc/tinc/wnvpn/rsa_key.priv
	# tincd -c /etc/tinc/wnvpn
	#
	### VTUN:
	# wget http://downloads.sourceforge.net/project/vtun/vtun/3.0.3/vtun-3.0.3.tar.gz
	# tar xzf vtun-*; cd vtun-*
	# test -e /usr/local/bin/strip || ln -s /bin/true /usr/local/bin/strip
	# ./configure --disable-ssl && make && make install
	# cd ..; rm -fR vtun-*
	#
	### UCI:
	# {
	# echo 'system.@monitoring[0].url=http://intercity-vpn.de/networks/liszt28'
	# echo 'system.@system[0].hostname=ChicagoVPS'
	# echo 'system.@fwupdate[0].mode=testing'
	# echo 'system.vpn.port=5001'
	# echo 'system.@profile[0].name=ffweimar_ap'
	# echo 'system.@profile[0].nodenumber=1'
	# echo 'system.@profile[0].ipsystem=ffweimar'
	# echo 'network.lan.ifname=venet0'
	# } >/etc/kalua_uci
	#
	# - set sms_password?
	#
	### KALUA:
	# wget -O /tmp/tarball.tgz http://intercity-vpn.de/firmware/tarball.tgz
	# cd /; tar xzf /tmp/tarball.tgz && rm -f /tmp/tarball.tgz; cd ~
	# /etc/kalua_init
	# (respect possible error-messages, e.g. bash-linking)
	#
	### WEBSERVER:
	# apt-get -y install $YOUR_CHOICE (e.g. apache2 or http://zeniv.linux.org.uk/~alan/%C2%B5Web/ )
	# mkdir -p /var/www
	# test -e /var/www/index.html && mv /var/www/index.html /var/www/index.html_old
	# touch /var/www/cgi-bin-status.html && ln -s /var/www/cgi-bin-status.html /var/www/index.html
	# hint: set 'DocumentRoot' = '/var/www' in '/etc/apache2/sites-available/000-default.conf'
	# wget -O /var/www/favicon.ico http://intercity-vpn.de/favicon.ico
	# cp /www/robots.txt /var/www
	# touch /var/www/cgi-bin-tool.sh
	# /usr/sbin/cron.build_netjson.sh setup_html /var/www
	#
	### crontab -e
	# (for user root: before enabling this crontab, fire this line manually first and solve problems)
	# * * * * * test -e /tmp/loader || /etc/kalua_init && . /tmp/loader && _cron vpnserver
	#
	### TODO:
	# wget -O /bin/ipcalc.sh "https://dev.openwrt.org/browser/trunk/package/base-files/files/bin/ipcalc.sh?format=txt"
	# olsr-HNA4/MainIP?: https://github.com/weimarnetz/vpnconfig#ip-schema
	# remove packages for compiling?
	# unalias cp/rm/mv -> avoiding 'cp -i' (always asking)
	# auto-key-update for tinc (1 server changes, all other must update)
}
