#!/bin/sh

_filetype_check_header()
{
	local MAGIC="$1"		# keyword 'show' or a regex, e.g. ^1f8b:
	local FILE="$2"
	local BYTES LINE
	local GREPFLAG="-q"

	[ -e "$FILE" ] || return 1

	BYTES="$( echo "$MAGIC" | sed 's/ //g' )"
	BYTES=$(( ${#BYTES} / 2 ))

	case "$MAGIC" in
		show) MAGIC=; BYTES=16; GREPFLAG= ;;
	esac

	dd if="$FILE" bs=${BYTES} count=1 2>&- |
		hexdump -C |
			if read -r LINE; then echo "${LINE#* }"; fi |
				sed 's/ //g' |
					grep $GREPFLAG "$MAGIC" && {
						return 0
					}
	return 1
}

_filetype_detect_mimetype()
{
	local file="$1"
	local list='tar gzip pdf gif html shellscript'
	local mime

	for mime in $list; do {
		_filetype $mime "$file" && break
	} done
	[ $? -eq 0 ] || mime='plain'

	case "$mime" in
		tar)  mime='application/tar' ;;
		gzip) mime='application/gzip' ;;
		pdf)  mime='application/pdf' ;;
		gif)  mime='image/gif' ;;
		html) mime='text/html' ;;
		shellscript) mime='text/x-shellscript' ;;
		*)    mime='text/plain' ;;
	esac

	echo "$mime"
}

_filetype_compressed()
{
	local file="$1"

	_filetype gzip "$file"
}

_filetype_gif()
{
	return 1
}

_filetype_html()
{
	return 1
}

_filetype_gzip()
{
	local FILE="$1"
	local MAGIC="^1f8b"

	_filetype check_header "$MAGIC" "$FILE"
}

_filetype_shellscript()
{
	local file="$1"
	local magic='^23212f62696e2f7368'	#!/bin/sh

	_filetype check_header "$magic" "$file"
}

_filetype_pdf()
{
	local FILE="$1"
	local MAGIC="^255044462d31"	# '%PDF-1.'

	_filetype check_header "$MAGIC" "$FILE"
}

_filetype_script()
{
	local file="$1"
	local magic="^23212f"		# first 3 bytes of '#!/bin/sh'

	_filetype check_header "$magic" "$file"
}

_filetype_elf()
{
	local file="$1"
	local magic="^7f454c46"		# first 4 bytes: '.ELF'

	_filetype check_header "$magic" "$file"
}

_filetype_tar()
{
	local file="$1"
	local check_lines_max=50
	local magic="00000100  00 75 73 74 61 72 20 20  "

	hexdump -C "$file" | head -n "$check_lines_max" | grep -q "$magic"
}
