#!/bin/sh

_i18n_sanitize_userwish()	# TODO: where does it come from?: 'de de-DE,'
{
	local accept="$1"	# e.g. 'za;de-CH;q=0.843,de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.39'
	local obj lang val

	# TODO: remove artificial added 'lang' later, if also normally listed
	#       - mark with e.g. '80 en:' and if 'en' exist -> remove

	# https://github.com/iain/http_accept_language
	# http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
	# http://www.thefutureoftheweb.com/blog/use-accept-language-header

	local oldIFS="$IFS"; IFS=',;' ; explode $accept; IFS="$oldIFS"

	for obj in "$@"; do {
		case "$obj" in
			'q='*)
				case "${obj%.*}" in
					'q=0')
						val="${obj#*=}"
					;;
					*)
						# invalid values or <empty>
						val='1.00'
					;;
				esac

				echo "$val $lang"

				case "$lang" in
					*'-'*)	# en-US -> en (main lang from sublang)
						echo "$val ${lang%-*}"
					;;
				esac

				lang=
			;;
			*)
				[ -n "$lang" ] && {
					echo "1.00 $lang"

					case "$lang" in
						*'-'*)	# en-US -> en
							echo "1.00 ${lang%-*}"
						;;
					esac
				}

				lang="$obj"
			;;
		esac
	} done
}

_i18n_default_lang()
{
	local default_fallback="$( uci -q get system.@weblogin[0].defaultlang )"

	echo "${default_fallback:-de}"
}

_i18n_effective_lang()
{
	local accept="${1:-$HTTP_ACCEPT_LANGUAGE}"	# e.g. en-ca,en;q=0.8,en-us;q=0.6,de-de;q=0.4,de;q=0.2
	local cachefile='/tmp/accept_lang_cache'	#      za;de-CH;q=0.843,de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.39
	local line default_fallback

	[ -z "$accept" ] && {
		_i18n default_lang
		return 0
	}

	if line="$( grep -s " $accept"$ "$cachefile" )"; then
		echo ${line% *}
	else
		_i18n sanitize_userwish "$accept" | sort -nr | while read -r lang; do {
			explode $lang

			case "$2" in
				# supported languages
				de|en|ru|da|ja|fr)
					echo "$2 $accept" >>"$cachefile"
					break
				;;
			esac
		} done

		if line="$( grep -s " $accept"$ "$cachefile" )"; then
			echo ${line% *}
		else
			default_fallback="$( _i18n default_lang )"

			echo "$default_fallback $accept" >>"$cachefile"
			echo "$default_fallback"
		fi
	fi
}

_i18n_lang()
{
	local lang="$1"		# ISO 639-1
				# FIXME! we need a way to transport/know, if lang = left2right or right2left
	case "$lang" in
		de|en|ru|da|ja|fr)
			echo "$lang"
		;;
		*)
			_i18n effective_lang
		;;
	esac
}

_i18n_get()				# TODO: chinese-simplified/arabic/hebrew (right2left)
{					#       espaniol/vietnam/hindu
					#       tuerkisch/italienisch/esperanto/klingon
	local LANG="$( _i18n lang "$1" )"		# fixme! do it without fork? (use returncode as lang)
	local KEYWORD="${2:-empty}"
	local context="$3"				# html|filename (weblogin?|admin-panel?)
	local o="element_${KEYWORD}_is_unset"

	case "$KEYWORD" in
		switched_off) case $LANG in
			de) o='ausgeschaltet';;
			en) o='switched off';; esac
		;;
		tickets_will_be_delivered_soon) case $LANG in
			de) o="Die Tickets werden in den n&auml;chsten Minuten per E-Mail zugestellt." ;;
			en) o="the tickets will be delivered in the next couple of minutes via email." ;; esac
		;;
		animalnames_german) case $LANG in
			de) o="Tiernamen, deutsch" ;;
			en) o="animals, german" ;; esac
		;;
		capital_citys) case $LANG in
			de) o="Hauptst&auml;dte der Welt" ;;
			en) o="capitals of the world" ;; esac
		;;
		artists_school_of_leipzig) case $LANG in
			de) o="K&uuml;nstler der Leipziger Schule" ;;
			en) o="school of leipzig's artists" ;; esac
		;;
		shoe_brands) case $LANG in
			de) o="Schuhmarken dieser Welt" ;;
			en) o="shoebrands of the world" ;; esac
		;;
		classical_composers) case $LANG in
			de) o="Komponisten klassischer Musik" ;;
			en) o="classical era composers" ;; esac
		;;
		uniq_username) case $LANG in
			de) o="Benutzername immer gleichbleibend" ;;
			en) o="username keeps the same" ;; esac
		;;
		yes) case $LANG in
			de) o="ja" ;;
			en) o="yes" ;; esac
		;;
		no) case $LANG in
			de) o="nein" ;;
			en) o="no" ;; esac
		;;
		or) case $LANG in
			de) o="oder" ;;
			en) o="or" ;; esac
		;;
		none) case $LANG in
			de) o="keine" ;;
			en) o="none" ;; esac
		;;
		browse) case $LANG in
			de) o="bl&auml;ttern" ;;
			en) o="browse" ;; esac
		;;
		choice) case $LANG in
			de) o="Wahl" ;;
			en) o="choice" ;; esac
		;;
		creation_time) case $LANG in
			de) o="Erstellungszeit" ;;
			en) o="creation time" ;; esac
		;;
		action) case $LANG in
			de) o="Aktion" ;;
			en) o="action" ;; esac
		;;
		roomnumber) case $LANG in
			de) o="Zimmernummer" ;;
			en) o="roomnumber" ;; esac
		;;
		name_of_guest) case $LANG in
			de) o="Name des Gastes" ;;
			en) o="name of guest" ;; esac
		;;
		bookingcode) case $LANG in
			de) o="Buchungscode" ;;
			en) o="bookingcode" ;; esac
		;;
		protocol) case $LANG in
			de) o="Protokoll" ;;
			en) o="protocol" ;; esac
		;;
		# FIXME! maybe use 'no service' for all languages?
		# this is used for ESSID = max 31 chars, so:
		# Locationname + <space> + 'maintenance' + <space> + $context = $NODENUMBER/$interface
		# =    13      +    1    +       11      +    1    +          3...5                    = 16...18 chars
		maintenance_mode) case $LANG in
			de) o="$( _sanitizer run "$( _weblogin metadata_locationname )" length:$(( 16 - ${#context} )) ) Wartungsmodus $context" ;;
			en) o="$( _sanitizer run "$( _weblogin metadata_locationname )" length:$(( 18 - ${#context} )) ) maintenance $context" ;; esac
		;;
		maintenance_hint1) case $LANG in
			de) o="Gerne beantworten wir Ihnen Fragen zum System" ;;
			en) o="We will be glad to answer your questions regarding the WiFi-system," ;; esac
		;;
		maintenance_hint2) case $LANG in
			de) o="unter der Telefonummer" ;;
			en) o="please call" ;; esac
		;;
		letter_line1) case $LANG in
			de) o="das WLAN-System hat festgestellt, dass von der Ticketart" ;;
			en) o="the WiFi-system has recognized, that from ticket-type" ;; esac
		;;
		letter_line2) case $LANG in
			de) o="nur noch wenige Logins vorhanden sind. Im Dateianhang finden" ;;
			en) o="there are only a small number of logins available. Attached you" ;; esac
		;;
		letter_line3) case $LANG in
			de) o="Sie deshalb eine weitere Liste in verschiedenen Vorlagen." ;;
			en) o="will find the next list in different templates." ;; esac
		;;
		letter_line4) case $LANG in
			de) o="Die bisherigen Listen behalten Ihre Gueltigkeit." ;;
			en) o="The remaining lists keep valid." ;; esac
		;;
		letter_salutation) case $LANG in
			de) o="Guten Tag" ;;
			en) o="Dear Madam/Sir" ;; esac
		;;
		letter_finale1) case $LANG in
			de) o="mit drahtlosen Gruessen," ;;
			en) o="with wireless greetings," ;; esac
		;;
		letter_finale2) case $LANG in
			de) o="Ihr WLAN-System von" ;;
			en) o="your WiFi-system from" ;; esac
		;;
		new_tickets) case $LANG in
			de) o="neue Tickets" ;;
			en) o="new tickets" ;; esac
		;;
		timestamp_of_automatic_generation) case $LANG in
			de) o="Zeitpunkt der automatischen Generierung" ;;
			en) o="timestamp of automatic generation" ;; esac
		;;
		standard_labels) case $LANG in
			de) o="Standard Etiketten" ;;
			en) o="standard labels" ;; esac
		;;
		standard_labels_identifier) case $LANG in
			de) o="\"Zweckform\" L4732" ;;
			en) o="\"Avery\" L4732" ;; esac
		;;
		overview) case $LANG in
			de) o="&Uuml;bersicht" ;;
			en) o="overview" ;; esac
		;;
		label) case $LANG in
			de) o="Etikett" ;;
			en) o="label" ;; esac
		;;
		labels) case $LANG in
			de) o="Etiketten" ;;
			en) o="labels" ;; esac
		;;
		administration) case $LANG in
			de) o="Administration" ;;
			en) o="administration" ;; esac
		;;
		labels_overview) case $LANG in
			de) o="Etiketten&uuml;bersicht" ;;
			en) o="label-overview" ;; esac
		;;
		for_standard_labels) case $LANG in
			de) o="fuer Standard-Etiketten" ;;
			en) o="for standard-labels" ;; esac
		;;
		in_an_overview) case $LANG in
			de) o="in einer Uebersicht" ;;
			en) o="in an overview" ;; esac
		;;
		wifi_tickets) case $LANG in
			de) o="WLAN-Tickets" ;;
			en) o="WiFi-tickets" ;; esac
		;;
		wifi_system) case $LANG in
			de) o="WLAN-System" ;;
			en) o="WiFi-system" ;; esac
		;;
		mail_delivery) case $LANG in
			de) o="Mailversand" ;;
			en) o="mail delivery" ;; esac
		;;
		device_count) case $LANG in
			de) o="Ger&auml;tezahl" ;;
			en) o="number of devices" ;; esac
		;;
		percent_uplink) case $LANG in
			de) o="% des Uplinks" ;;
			en) o="% of uplink" ;; esac
		;;
		minutes) case $LANG in
			de) o="Minuten" ;;
			en) o="minutes" ;; esac
		;;
		kilobytes) case $LANG in
			de) o="Kilobytes" ;;
			en) o="kilobytes" ;; esac
		;;
		kilobits) case $LANG in
			de) o="Kilobits" ;;
			en) o="kilobits" ;; esac
		;;
		megabytes) case $LANG in
			de) o="Megabytes" ;;
			en) o="megabytes" ;; esac
		;;
		megabits) case $LANG in
			de) o="Megabits" ;;
			en) o="megabits" ;; esac
		;;
		gigabytes) case $LANG in
			de) o="Gigabytes" ;;
			en) o="gigabytes" ;; esac
		;;
		hours) case $LANG in
			de) o="Stunden" ;;
			en) o="hours" ;; esac
		;;
		days) case $LANG in
			de) o="Tage" ;;
			en) o="days" ;; esac
		;;
		months) case $LANG in
			de) o="Monate" ;;
			en) o="months" ;; esac
		;;
		active) case $LANG in
			de) o="aktiv" ;;
			en) o="active" ;; esac
		;;
		hint) case $LANG in
			de) o="Hinweis" ;;
			en) o="hint" ;; esac
		;;
		macaddress) case $LANG in
			de) o="MAC-Adresse" ;;
			en) o="MAC-address" ;; esac
		;;
		hostnames) case $LANG in
			de) o="Hostnamen" ;;
			en) o="hostnames" ;; esac
		;;
		fuzziness) case $LANG in
			de) o="Unsch&auml;rfe" ;;
			en) o="fuzziness" ;; esac
		;;
		till) case $LANG in
			de) o="bis" ;;
			en) o="till" ;; esac
		;;
		only_login_x2y_will_be_shown1) case $LANG in
			de) o="Es werden nur die Logins" ;;
			en) o="only logins" ;; esac
		;;
		only_login_x2y_will_be_shown2) case $LANG in
			de) o="angezeigt" ;;
			en) o="will be shown" ;; esac
		;;
		only_last_x_login_will_be_shown1) case $LANG in
			de) o="es werden nur die letzten" ;;
			en) o="only the last" ;; esac
		;;
		only_last_x_login_will_be_shown2) case $LANG in
			de) o="angezeigt" ;;
			en) o="will be shown" ;; esac
		;;
		selected_logins) case $LANG in
			de) o="ausgew&auml;hlte Logins" ;;
			en) o="selected logins" ;; esac
		;;
		all_shown_logins) case $LANG in
			de) o="alle angezeigten Logins" ;;
			en) o="all shown logins" ;; esac
		;;
		login_overview) case $LANG in
			de) o="Login&uuml;bersicht" ;;
			en) o="login-overview" ;; esac
		;;
		logindata_was_safed) case $LANG in
			de) o="Logindaten wurden gespeichert" ;;
			en) o="logindata was safed" ;; esac
		;;
		devices_number) case $LANG in
			de) o="Ger&auml;teanzahl" ;;
			en) o="number of devices" ;; esac
		;;
		used_time) case $LANG in
			de) o="benutzte Zeit" ;;
			en) o="used time" ;; esac
		;;
		passed_time) case $LANG in
			de) o="vergangene Zeit" ;;
			en) o="passed time" ;; esac
		;;
		for_all_profiles) case $LANG in
			de) o='f&uuml;r alle Profile' ;;
			en) o='for all profiles' ;; esac
		;;
		profile_was_safed) case $LANG in
			de) o="Profil wurde gespeichert" ;;
			en) o="profile was safed" ;; esac
		;;
		profile_apply) case $LANG in
			de) o="Profil anlegen" ;;
			en) o="profile apply" ;; esac
		;;
		profile_update) case $LANG in
			de) o="Profil aktualisieren" ;;
			en) o="update profile" ;; esac
		;;
		login_update) case $LANG in
			de) o="Login aktualisieren" ;;
			en) o="update login" ;; esac
		;;
		ticket_carboncopy) case $LANG in
			de) o="Anzahl der Kopien" ;;
			en) o="number of copies" ;; esac
		;;
		hint_auth_via_mac) case $LANG in
			de) o="MAC-Adresse und optional Hostname werden zur Authentifizierung ben&ouml;tigt" ;;
			en) o="MAC-address and optionally the hostname are needed for authentication" ;; esac
		;;
		desc_macaddress) case $LANG in
			de) o="eine Hardwareadresse in der Form <i>00:11:22:33:44:55</i> deren Teilnahme bzw. Freischaltung am Netzwerk automatisch erfolgen soll" ;;
			en) o="a hardware-address looking like <i>00:11:22:33:44:55</i> which should be free to use the network" ;; esac
		;;
		desc_hostnames) case $LANG in
			de) o="wenn erw&uuml;nscht kann die G&uuml;ltigkeit der MAC-Adresse auf bestimmte Zugangspunkte begrenzt werden. Mehrere Zugangspunkte durch Leerzeichen trennen" ;;
			en) o="if wished, the validity-scope of the mac-address can be limited to specific nodes. several entries must be separated by spaces" ;; esac
		;;
		desc_profiletype) case $LANG in
			de) o="welches Profil soll Grundlage f&uuml;r diesen Login werden?" ;;
			en) o="which profile should be the base for this login?" ;; esac
		;;
		desc_usercomment) case $LANG in
			de) o="falls n&ouml;tig Notizen zum Nutzer, Ereignis oder Ger&auml;t" ;;
			en) o="if needed a notice regarding user, event or device" ;; esac
		;;
		hint_auth_credentials) case $LANG in
			de) o="Benutzername und Passwort werden zur Authentifizierung ben&ouml;tigt" ;;
			en) o="username and password are needed for authentication" ;; esac
		;;
		desc_username) case $LANG in
			de) o="ein einfach zu schreibender Loginname, <i>leer</i> lassen f&uuml;r automatische Generierung mit dem Namensraum" ;;
			en) o="a simple to write loginname, <i>empty</i> will enforce an automatic generation using namespace" ;; esac
		;;
		desc_password) case $LANG in
			de) o="Zahlenkombination (empfohlen), <i>leer</i> lassen f&uuml;r automatische Generierung" ;;
			en) o="combination of numbers (recommended), leave <i>empty</i> for an automatic generation" ;; esac
		;;
		desc_fuzzy) case $LANG in
			de) o="Gro&szlig;- bzw. Kleinschreibung am Anfang spielt keine Rolle und Benutzernamen und Passwort k&ouml;nnen vertauscht werden" ;;
			en) o="upper- or lowercase at the beginning doesn't matter and username/password can be switched around" ;; esac
		;;
		desc_devices_number) case $LANG in
			de) o="wieviel unterschiedliche Ger&auml;te d&uuml;rfen diesen Login benutzen? <i>leer</i> lassen bedeutet unbegrenzt" ;;
			en) o="how many different devices are allowed to use this login? <i>empty</i> means unlimited" ;; esac
		;;
		desc_ticket_carboncopy) case $LANG in
			de) o="soll eine gr&ouml;&szlig;ere Anzahl der gleichen Ticketart angelegt werden? Benutzername und Passwort werden dann in jedem Fall automatisch generiert" ;;
			en) o="want to create several tickets of same type? in this case username and password are automatically generated" ;; esac
		;;
		desc_price) case $LANG in
			de) o="f&uuml;r die Buchhaltung bzw. revisionssichere Protokollierung" ;;
			en) o="for the bookkeeping or rather the revisionsafe logging" ;; esac
		;;
		desc_landing_page) case $LANG in
			de) o="auf diese Seite wird der Benutzer geleitet, nachdem er sein Passwort eingegeben hat, z.b. https://www.google.de" ;;
			en) o="to this page the user is redirected, after submitting the credentials, e.g. https://www.google.com" ;; esac
		;;
		desc_adblock) case $LANG in
			de) o="Werbe-banner und -grafiken werden herausgefiltert" ;;
			en) o="ad-banners and -graphics are filtered out" ;; esac
		;;
		desc_youth_protection) case $LANG in
			de) o="der Abruf von Webseiten wird durch einen Filter geleitet" ;;
			en) o="the fetching of webpages is mangled through a filter" ;; esac
		;;
		desc_max_download_speed) case $LANG in
			de) o="erlaubte Geschwindkeit bei eintreffendem Datenverkehr, <i>leer</i> meint unbegrenzt" ;;
			en) o="allowed speed for incoming data transmission, <i>empty</i> means unlimited" ;; esac
		;;
		desc_max_upload_speed) case $LANG in
			de) o="erlaubte Geschwindkeit bei ausgehendem Datenverkehr, <i>leer</i> meint unbegrenzt" ;;
			en) o="allowed speed for outgoing data transmission, <i>empty</i> means unlimited" ;; esac
		;;
		desc_max_data_volume) case $LANG in
			de) o="erlaubter Rahmen der gesamten &uuml;bertragenen Datenmenge, Up- &amp; Download zusammengerechnet, <i>leer</i> meint unbegrenzt" ;;
			en) o="allowed amount of the hole data volume, up- &amp; download together, <i>empty</i> means unlimited" ;; esac
		;;
		desc_validity_period) case $LANG in
			de) o="nach dem Abrechnungsmodell erlaubter Zeitrahmen, <i>leer</i> meint unbegrenzt" ;;
			en) o="allowed time-window according to the time-model, <i>empty</i> means unlimited" ;; esac
		;;
		desc_timemodel) case $LANG in
			de) o="die Zeit l&auml;uft, wenn sich ein Benutzer das erste Mal einbucht: soll dann die tats&auml;chliche (benutzte) Online-Zeit berechnet werden oder l&auml;uft die Zeit auch weiter, wenn der Benutzer nichts (vergangene) im Netz macht?" ;;
			en) o="the time is running after the first user-login: should we take the real (used) online-time into account or does the time runs, even when the user doesn't do anything (passed) in the net?" ;; esac
		;;
		desc_autogenerate) case $LANG in
			de) o="wenn Logins f&uuml;r dieses Profil zur Neige gehen, sollen automatisch neue erzeugt werden? (Versand per E-Mail/PDF)" ;;
			en) o="if logins for this profile are running out of supplies, auto-generate new ones? (send via email/PDF)" ;; esac
		;;
		desc_comment) case $LANG in
			de) o="wenn gew&uuml;nscht, ein ausf&uuml;hrlicher Kommentar" ;;
			en) o="if wished, a detailed explanation" ;; esac
		;;
		desc_shortname) case $LANG in
			de) o='einfacher, kurzer Name (z.B. "2-Stunden-Tickets"). Wenn mit "zimmer" oder "wohnung" beginnend, ergibt sich daraus spaeter der Benutzername. "zimmer 107" wird dann zu Benutzername 107.' ;;
			en) o='simple, short name (e.g. "2-hour-tickets"). When beginning with "room", it will be used later for the username. E.g. "room 107" leads to username 107.' ;; esac
		;;
		eg_1dayticket) case $LANG in
			de) o="z.B. Tagesticket" ;;
			en) o="e.g. 1-day-ticket" ;; esac
		;;
		overall) case $LANG in
			de) o="insgesamt" ;;
			en) o="overall" ;; esac
		;;
		eg_username) case $LANG in
			de) o="z.B. Benutzername" ;;
			en) o="e.g. username" ;; esac
		;;
		show_devices) case $LANG in
			de) o="Ger&auml;te anzeigen" ;;
			en) o="show devices" ;; esac
		;;
		find) case $LANG in
			de) o="finden" ;;
			en) o="find" ;; esac
		;;
		searchpattern) case $LANG in
			de) o="Suchmuster" ;;
			en) o="searchpattern" ;; esac
		;;
		the_newest) case $LANG in
			de) o="die neuesten" ;;
			en) o="the newest" ;; esac
		;;
		show) case $LANG in
			de) o="anzeigen" ;;
			en) o="show" ;; esac
		;;
		delete) case $LANG in
			de) o="l&ouml;schen" ;;
			en) o="delete" ;; esac
		;;
		edit) case $LANG in
			de) o="bearbeiten" ;;
			en) o="edit" ;; esac
		;;
		login_create) case $LANG in
			de) o="Login anlegen" ;;
			en) o="create login" ;; esac
		;;
		login_edit) case $LANG in
			de) o="Login bearbeiten" ;;
			en) o="edit login" ;; esac
		;;
		name) case $LANG in
			de) o="Name" ;;
			en) o="name" ;; esac
		;;
		comment) case $LANG in
			de) o="Kommentar" ;;
			en) o="comment" ;; esac
		;;
		autocreate) case $LANG in
			de) o="automatisches Erzeugen" ;;
			en) o="automatic creation" ;; esac
		;;
		accounting_model) case $LANG in
			de) o="Abrechnungsmodell" ;;
			en) o="accounting model" ;; esac
		;;
		validity_period) case $LANG in
			de) o="G&uuml;ltigkeitsdauer" ;;
			en) o="validity period" ;; esac
		;;
		max_data_volume) case $LANG in
			de) o="maximales Datenvolumen" ;;
			en) o="maximum data volume" ;; esac
		;;
		max_upload_speed) case $LANG in
			de) o="maximale Upload-Geschwindigkeit" ;;
			en) o="maximum upload speed" ;; esac
		;;
		max_download_speed) case $LANG in
			de) o="maximale Download-Geschwindigkeit" ;;
			en) o="maximum download speed" ;; esac
		;;
		youth_protection) case $LANG in
			de) o="Jugendschutzfilter" ;;
			en) o="youth protection" ;; esac
		;;
		adblocker) case $LANG in
			de) o="Werbefilter" ;;
			en) o="advertisement blocker" ;; esac
		;;
		url_landingpage) case $LANG in
			de) o="Internetadresse der Landeseite" ;;
			en) o="URL of landing page" ;; esac
		;;
		selling_price) case $LANG in
			de) o="Verkaufspreis" ;;
			en) o="selling price" ;; esac
		;;
		parameter) case $LANG in
			de) o="Parameter" ;;
			en) o="parameter" ;; esac
		;;
		value) case $LANG in
			de) o="Wert" ;;
			en) o="value" ;; esac
		;;
		explanation) case $LANG in
			de) o="Erl&auml;uterung" ;;
			en) o="explanation" ;; esac
		;;
		please_wait_for_db) case $LANG in
			de) o='Das System hat gerade neu gestartet - bitte warten Sie bis der Datenbankserver wieder aktiv ist.' ;;
			en) o='The system has restarted just now - please wait till the database-server is active again.' ;; esac
		;;
		make_login_first) case $LANG in
			de) o="zuerst muss ein Login angelegt werden" ;;
			en) o="at first you have to create a login" ;; esac
		;;
		make_profile_first) case $LANG in
			de) o="zuerst muss ein Profil angelegt werden" ;;
			en) o="at first you have to create a profile" ;; esac
		;;
		new_devices) case $LANG in
			de) o="neue Ger&auml;te" ;;
			en) o="new devices" ;; esac
		;;
		new_logins) case $LANG in
			de) o="neue Logins" ;;
			en) o="new logins" ;; esac
		;;
		new_profile) case $LANG in
			de) o="neues Profil" ;;
			en) o="new profile" ;; esac
		;;
		profile) case $LANG in
			de) o="Profil" ;;
			en) o="profile" ;; esac
		;;
		create) case $LANG in
			de) o="erstellen" ;;
			en) o="create" ;; esac
		;;
		download) case $LANG in
			de) o="runterladen" ;;
			en) o="download" ;; esac
		;;
		upload) case $LANG in
			de) o="hochladen" ;;
			en) o="upload" ;; esac
		;;
		config_export) case $LANG in
			de) o="Konfiguration exportieren" ;;
			en) o="export configuration" ;; esac
		;;
		config_import) case $LANG in
			de) o="Konfiguration importieren" ;;
			en) o="import configuration" ;; esac
		;;
		html_config_management) case $LANG in
			de) o="<b><big>E</big>instellungen</b> verwalten" ;;
			en) o="<b><big>C</big>onfiguration</b> management" ;; esac
		;;
		html_manage_devices) case $LANG in
			de) o="<b><big>G</big>er&auml;te</b> verwalten" ;;
			en) o="<b><big>D</big>evice</b> management" ;; esac
		;;
		html_manage_profiles) case $LANG in
			de) o="<b><big>P</big>rofile</b> verwalten" ;;
			en) o="<b><big>P</big>rofile</b> management" ;; esac
		;;
		html_manage_logins) case $LANG in
			de) o="<b><big>L</big>ogins</b> verwalten" ;;
			en) o="<b><big>L</big>ogin</b> management" ;; esac
		;;
		main_menu) case $LANG in
			de) o="Hauptmen&uuml;" ;;
			en) o="main menu" ;; esac
		;;
		wishing_a_nice_stay) case $LANG in
			de) o="Wir wuenschen einen angenehmen Aufenthalt" ;;
			en) o="we wish you a nice stay" ;; esac
		;;
		your_username_and_password) case $LANG in
			de) o="Ihr Benutzername/Passwort" ;;
			en) o="your username/password" ;; esac
		;;
		your_credentials) case $LANG in
			de) o="Ihre Zugangsdaten" ;;
			en) o="your credentials" ;; esac
		;;
		profile_edit) case $LANG in
			de) o="Profil bearbeiten" ;;
			en) o="profile edit" ;; esac
		;;
		wifi_system) case $LANG in
			de) o="WLAN-System" ;;
			en) o="WiFi-system" ;; esac
		;;
		rights_management) case $LANG in
			de) o="Rechteverwaltung" ;;
			en) o="rights-management" ;; esac
		;;
		needs_admin_interaction)
			local adminphone="03643/544384"
			local errorcode="${REMOTE_ADDR:-noremote}/$LANADR/$( _net dev2mac $LANDEV )"
			local append="&nbsp;${adminphone}&nbsp;&minus;&nbsp;[${errorcode}]"

				case $LANG in
			de) o="Dieser Zugangspunkt hat ein technisches Problem und ben&ouml;tigt administrative Hilfe<br><br>Telefon:$append" ;;
			en) o="this accesspoint has technical problems and needs administrative help<br><br>Phone:$append" ;;
			ru) o="this accesspoint has technical problems and needs administrative help<br><br>Phone:$append" ;;
			da) o="this accesspoint has technical problems and needs administrative help<br><br>Phone:$append" ;;		# fixme!
			ja) o="this accesspoint has technical problems and needs administrative help<br><br>Phone:$append" ;;
			fr) o="this accesspoint has technical problems and needs administrative help<br><br>Phone:$append" ;; esac
		;;
		no_internet_allowed) case $LANG in
			de) o="Dieser Login darf kein Internet nutzen." ;;
			en) o="this PC is not allowed for internet." ;;
		;;
		password_was_send) case $LANG in
			de) o="die Logindaten wurden per SMS auf Ihr Mobiltelefon gesandt" ;;
			en) o="the credentials were send to your mobile phone" ;;
			ru) o="the credentials were send to your mobile phone" ;;	# fixme
			da) o="the credentials were send to your mobile phone" ;;	# fixme
			ja) o="the credentials were send to your mobile phone" ;;	# fixme
			fr) o="les pouvoirs ont &eacute;t&eacute; envoy&eacute; &agrave; votre t&eacute;l&eacute;phone mobile" ;; esac
		;;
		wrong_mobile_number) case $LANG in
			de) o="Diese Mobilfunknummer scheint nicht g&uuml;tig zu sein" ;;
			en) o="this mobile number seems to be not valid" ;;
			ru) o="this mobile number seems to be not valid" ;;	# fixme
			da) o="this mobile number seems to be not valid" ;;	# fixme
			ja) o="this mobile number seems to be not valid" ;;	# fixme
			fr) o="this mobile number seems to be not valid" ;; esac	# fixme
		;;
		mobile_number) case $LANG in
			de) o="Ihre Mobilfunknummer" ;;
			en) o="your mobile number" ;;
			ru) o="your mobile number" ;;	# fixme
			da) o="your mobile number" ;;	# fixme
			ja) o="your mobile number" ;;	# fixme
			fr) o="votre num&eacute;ro de mobile" ;; esac
		;;
		mobile_number_howto) case $LANG in
			de) o="z.B. +49 123 98765432" ;;
			en) o="e.g. +44 123 98765432" ;;
			ru) o="e.g. +007 123 98765432" ;;	# fixme
			da) o="e.g. +45 123 98765432" ;;	# fixme
			ja) o="e.g. +81 123 98765432" ;;	# fixme
			fr) o="ex. +33 123 98765432" ;; esac
		;;
		site_logo) case $LANG in
			de) o="Firmenzeichen" ;;
			en) o="Logo" ;;
			ru) o="&#1051;&#1086;&#1075;&#1086;&#1090;&#1080;&#1087;" ;;
			da) o="Logo" ;;
			ja) o="&#12525;&#12468;" ;;
			fr) o="Logo" ;; esac
		;;
		internetaccess) case $LANG in
			de) o="Internetzugang" ;;
			en) o="Internet access" ;;
			ru) o="&#1044;&#1086;&#1089;&#1090;&#1091;&#1087; &#1074; &#1048;&#1085;&#1090;&#1077;&#1088;&#1085;&#1077;&#1090;" ;;
			da) o="Internetadgang" ;;
			ja) o="&#12452;&#12531;&#12479;&#12540;&#12493;&#12483;&#12488;&#12450;&#12463;&#12475;&#12473;" ;;
			fr) o="Acc&egrave;s Internet" ;; esac
		;;
		username) case $LANG in
			de) o="Benutzername" ;;
			en) o="Username" ;;
			ru) o="&#1048;&#1084;&#1103; &#1087;&#1086;&#1083;&#1100;&#1079;&#1086;&#1074;&#1072;&#1090;&#1077;&#1083;&#1103;" ;;
			da) o="Brugernavn" ;;
			ja) o="&#12518;&#12540;&#12470;&#12540;&#21517;" ;;
			fr) o="Nom d'utilisateur" ;; esac
		;;
		roomnumber) case $LANG in
			de) o="Wohnungsnummer" ;;
			en) o="flat number" ;;
			ru) o="&#1085;&#1086;&#1084;&#1077;&#1088;&#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1099;" ;;
			da) o="flat number" ;;			# fixme!
			ja) o="flat number" ;;			# fixme!
			fr) o="flat number" ;;  esac		# fixme!
		;;
		bookingcode) case $LANG in
			de) o="Buchungsnummer" ;;
			en) o="booking code" ;;
			ru) o="&#1082;&#1086;&#1076;&#1073;&#1088;&#1086;&#1085;&#1080;&#1088;&#1086;&#1074;&#1072;&#1085;&#1080;&#1103;" ;;
			da) o="booking code" ;;			# fixme!
			ja) o="booking code" ;;			# fixme!
			fr) o="booking code" ;; esac		# fixme!
		;;
		password) case $LANG in
			de) o="Passwort" ;;
			en) o="Password" ;;
			ru) o="&#1055;&#1072;&#1088;&#1086;&#1083;&#1100;" ;;
			da) o="Adgangskode" ;;
			ja) o="&#12497;&#12473;&#12527;&#12540;&#12489;" ;;
			fr) o="Mot de passe" ;; esac
		;;
		accept_terms1) case $LANG in
			de) o="Ich akzeptiere die" ;;
			en) o="I accept the" ;;
			ru) o="&#1071; &#1087;&#1088;&#1080;&#1085;&#1080;&#1084;&#1072;&#1102;" ;;
			da) o="Jeg accepterer" ;;
			ja) o="&#31169;&#12399;&#21033;&#29992;&#35215;&#32004;&#12395;" ;;
			fr) o="J'accepte les" ;; esac
		;;
		accept_terms2) case $LANG in
			de) o="Nutzungsbedingungen" ;;
			en) o="Terms of Use" ;;
			ru) o="&#1059;&#1089;&#1083;&#1086;&#1074;&#1080;&#1103; &#1080;&#1089;&#1087;&#1086;&#1083;&#1100;&#1079;&#1086;&#1074;&#1072;&#1085;&#1080;&#1103;" ;;
			da) o="Vilk&aring;r for brug" ;;
			ja) o="&#21516;&#24847;&#12377;&#12427;" ;;
			fr) o="Conditions d'utilisation" ;; esac
		;;
		tip_contract) case $LANG in
			de) o="ausf&uuml;hrliche Informationen zu den Vertragsbedingungen" ;;
			en) o="detailed information to contractual" ;;
			ru) o="&#1055;&#1086;&#1076;&#1088;&#1086;&#1073;&#1085;&#1091;&#1102; &#1080;&#1085;&#1092;&#1086;&#1088;&#1084;&#1072;&#1094;&#1080;&#1102; &#1087;&#1086; &#1082;&#1086;&#1085;&#1090;&#1088;&#1072;&#1082;&#1090;&#1072;&#1084;" ;;
			da) o="detaljerede oplysninger om betingelserne for anvendelse" ;;
			ja) o="&#22865;&#32004;&#26465;&#20214;&#12398;&#35443;&#32048;&#12395;&#12388;&#12356;&#12390;&#12399;" ;;
			fr) o="&eacute;tendue des informations contractuelles" ;; esac
		;;
		wrong_logindata) case $LANG in
			de) o="Bitte pr&uuml;fen Sie ihre Eingabe und achten Sie auf die Gro&szlig;- bzw. Kleinschreibung" ;;
			en) o="Please check your entry and pay attention to upper / lower case" ;;
			ru) o="&#1087;&#1088;&#1086;&#1074;&#1077;&#1088;&#1100;&#1090;&#1077; &#1080;&#1084;&#1103; &#1080; &#1086;&#1073;&#1088;&#1072;&#1090;&#1080;&#1090;&#1077; &#1074;&#1085;&#1080;&#1084;&#1072;&#1085;&#1080;&#1077; &#1085;&#1072; &#1074;&#1077;&#1088;&#1093;&#1085;&#1080;&#1081; / &#1085;&#1080;&#1078;&#1085;&#1080;&#1081; &#1088;&#1077;&#1075;&#1080;&#1089;&#1090;&#1088;" ;;
			da) o="Tjek venligst din indtastning, og v&aelig;re opm&aelig;rksomme p&aring; store / sm&aring; bogstaver" ;;
			ja) o="&#12354;&#12394;&#12383;&#12398;&#12456;&#12531;&#12488;&#12522;&#12434;&#12481;&#12455;&#12483;&#12463;&#12375;&#12390;&#12289;&#22823;&#25991;&#23383;&#12392;&#23567;&#25991;&#23383;&#12395;&#27880;&#24847;&#12375;&#12390;&#12367;&#12384;&#12373;&#12356;" ;;
			fr) o="S'il vous pla&icirc;t v&eacute;rifier votre inscription et de pr&ecirc;ter attention aux majuscules / minuscules" ;; esac
		;;
		wrong_bookingcode_spbansin) case $LANG in
			de) o="Der Buchungscode muss in der Form xxxx-xxxx eingegeben werden" ;;
			en) o="the bookingcode must be entered like xxxx-xxxx" ;;
			ru) o="the bookingcode must be entered like xxxx-xxxx" ;;	# fixme!
			da) o="the bookingcode must be entered like xxxx-xxxx" ;;	# fixme!
			ja) o="the bookingcode must be entered like xxxx-xxxx" ;;	# fixme!
			fr) o="the bookingcode must be entered like xxxx-xxxx" ;; esac	# fixme!
		;;
		wrong_room_number) case $LANG in
			de) o="Diese Wohnung ist f&uuml;r die Nutzung nicht freigeschaltet" ;;
			en) o="this suite is not authorized for using this service" ;;
			ru) o="this suite is not authorized for using this service" ;;		# fixme!
			da) o="this suite is not authorized for using this service" ;;		# fixme!
			ja) o="this suite is not authorized for using this service" ;;		# fixme!
			fr) o="this suite is not authorized for using this service" ;; esac	# fixme!
		;;
		accept_rules) case $LANG in
			de) o="bitte akzeptieren Sie die Nutzungsbedingungen" ;;
			en) o="please accept the Terms of Use" ;;
			ru) o="&#1087;&#1088;&#1080;&#1084;&#1080;&#1090;&#1077; &#1059;&#1089;&#1083;&#1086;&#1074;&#1080;&#1103; &#1080;&#1089;&#1087;&#1086;&#1083;&#1100;&#1079;&#1086;&#1074;&#1072;&#1085;&#1080;&#1103;" ;;
			da) o="Venligst acceptere Vilk&aring;r for brug" ;;
			ja) o="&#12372;&#21033;&#29992;&#35215;&#32004;&#12395;&#21516;&#24847;" ;;
			fr) o="s'il vous pla&icirc;t accepter les Conditions d'utilisation" ;; esac
		;;
		inet_broken) case $LANG in
			de) o="Netzwerkfehler entdeckt, bitte benutzen Sie einen anderen Zugangspunkt." ;;
			en) o="Error in network detected, please use another accesspoint." ;;
			ru) o="&#1054;&#1096;&#1080;&#1073;&#1082;&#1072; &#1074; &#1089;&#1077;&#1090;&#1100; &#1086;&#1073;&#1085;&#1072;&#1088;&#1091;&#1078;&#1077;&#1085;&#1072;, &#1087;&#1086;&#1078;&#1072;&#1083;&#1091;&#1081;&#1089;&#1090;&#1072;, &#1080;&#1089;&#1087;&#1086;&#1083;&#1100;&#1079;&#1091;&#1081;&#1090;&#1077; &#1076;&#1088;&#1091;&#1075;&#1086;&#1081; &#1090;&#1086;&#1095;&#1082;&#1080; &#1076;&#1086;&#1089;&#1090;&#1091;&#1087;&#1072;." ;;
			da) o="Fejl i net opdaget, skal du bruge et andet accesspoint." ;;
			ja) o="&#12493;&#12483;&#12488;&#12527;&#12540;&#12463;&#12456;&#12521;&#12540;&#12364;&#12289;&#21029;&#12398;&#12450;&#12463;&#12475;&#12473;&#12509;&#12452;&#12531;&#12488;&#12434;&#20351;&#29992;&#12375;&#12390;&#12367;&#12384;&#12373;&#12356;&#26908;&#20986;" ;;
			fr) o="Erreur de reseau apparu, veuillez utiliser un autre point d' access." ;; esac
		;;
		in_my_lang) case $LANG in
			de) o="diese Seite in deutsch anzeigen" ;;
			en) o="show this page in english" ;;
			ru) o="&#1054;&#1090;&#1082;&#1088;&#1099;&#1090;&#1100; &#1101;&#1090;&#1086;&#1090; &#1089;&#1072;&#1081;&#1090; &#1085;&#1072; &#1088;&#1091;&#1089;&#1089;&#1082;&#1086;&#1084; &#1103;&#1079;&#1099;&#1082;&#1077;" ;;
			da) o="vis denne side p&aring; dansk" ;;
			ja) o="&#12398;&#12506;&#12540;&#12472;&#12398;&#26085;&#26412;&#35486;&#29256;" ;;
			fr) o="afficher cette page en anglais" ;; esac
		;;
		other_languages) case $LANG in
			de) o="andere Sprachen anzeigen" ;;
			en) o="show other languages" ;;
			ru) o="&#1055;&#1086;&#1082;&#1072;&#1079;&#1072;&#1090;&#1100; &#1076;&#1088;&#1091;&#1075;&#1080;&#1077; &#1071;&#1079;&#1099;&#1082;&#1080;" ;;
			da) o="vis andre sprog" ;;
			ja) o="&#34920;&#31034;&#20182;&#12398;&#35328;&#35486;" ;;
			fr) o="voir les autres langues" ;; esac
		;;
		langname) case $LANG in
			de) o="deutsch" ;;
			en) o="english" ;;
			ru) o="&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;" ;;
			da) o="dansk" ;;
			ja) o="&#26085;&#26412;&#35486;" ;;
			fr) o="fran&ccedil;ais" ;; esac
		;;
		login) case $LANG in
			de) o="Anmelden" ;;
			en) o="Login" ;;
			ru) o="&#1042;&#1086;&#1081;&#1090;&#1080;" ;;
			da) o="Log ind" ;;
			ja) o="&#30331;&#37682;" ;;
			fr) o="Connexion" ;; esac
		;;
	esac

	case "$context" in
		filename|html)
			_sanitizer run "$( _i18n html2plain "$o" )" alphanum
		;;
		*)
			printf '%s' "$o"
		;;
	esac
}

_i18n_html2plain()
{
	local in="$1"

	echo "$in" | sed -e 's/\&Uuml;/Ue/g' \
			-e 's/\&uuml;/ue/g'
}
