#!/bin/sh

_links_firmware_url_get()		# ARG1:	stable|beta|testing|empty
{					#	stable|beta|testing	<crc>			# .. (fetching crc)
					#	version_installed				# fixme! move to _firmware()
					#	version_current		<stable|beta|testing>	# ..
					#	version_current_main	<stable|beta|testing>	# ..
	local COMMAND="$1"		#	tarball|tarball_hash
	local KEYWORD="$2"		#	olsr_whitelist

	[ -z "$KEYWORD" ] && {
		case "$COMMAND" in
			stable|beta|testing)
				KEYWORD="$COMMAND"	# fixme! is a workaround for bad API 8-)
			;;
		esac
	}

	local UPDATEMODE="$( _firmware updatemode "$KEYWORD" override )"
	local BASE="$( uci get system.@fwupdate[0].url )"	# http://intercity-vpn.de/firmware
	local ARCHITECTURE="$( _system architecture )"
	BASE="${BASE:-http://intercity-vpn.de/firmware}"

	case "$COMMAND" in
		olsr_whitelist)
			echo -n "$( uci get system.@monitoring[0].url )/whitelist/"
		;;
		tarball)
			echo -n "$BASE/$ARCHITECTURE/images/$UPDATEMODE/tarball.tgz?host=$HOSTNAME"
		;;
		tarball_hash)
			local i=0
			local CRC

			[ "$UPDATEMODE" = "0" ] && i=100

			while [ -z "$CRC" -a $i -lt 100 ]; do {
				CRC="$( _wget do "$BASE/$ARCHITECTURE/images/$UPDATEMODE/info.txt" | fgrep "FILE: 'tarball.tgz'" | cut -d' ' -f2 )"
				sleep 5
				i=$(( $i + 1 ))
			} done

			echo -n "${CRC:=0}"
		;;
		version_current*)
			local OUTPUT

			OUTPUT="$( _wget do "$BASE/$ARCHITECTURE/images/$UPDATEMODE/info.txt" | head -n1 )"
			[ -n "$OUTPUT" ] && {
				local GENERATED VERSION KERNEL MAINTAINER VERSION_MAIN
				eval $OUTPUT
			}

			if [ "$COMMAND" = "version_current_main" ]; then
				echo -n "${VERSION_MAIN:=1.6.37}"
			else
				echo -n "${VERSION:=000000}"
			fi
		;;
		version_installed)
			echo -n "${FFF_PLUS_VERSION:=000000}"
		;;
		*)
			local FILEWISH dir= usecase=

			if usecase="$( _firmware get_usecase )"; then
				# e.g. http://intercity-vpn.de/firmware/ar71xx/images/testing/usecase/18c5d9ba35511b0b03491993b9507089/TP-LINK%20TL-WR1043ND.bin
				# see copy_firmware_files() in build.sh
				#
				# [symlink]
				# /var/www/firmware/ar71xx/images/testing/usecase/
				#	18c5d9ba35511b0b03491993b9507089/TP-LINK TL-WR1043ND.bin
				# [symlink]
				# /var/www/firmware/ar71xx/images/testing/usecase/
				#	Standard,VDS,kalua/TP-LINK TL-WR1043ND.bin
				# [realfile]
				# /var/www/firmware/ar71xx/images/testing/usecase/
				#	Standard,VDS,kalua/TP-LINK TL-WR1043ND.openwrt=r43102_kernel=_option=Standard,debug,VDS,kalua@3731799_rootfs=squash_image=sysupgrade.bin

				dir="usecase/$( _firmware get_usecase 'hash' )/"
				FILEWISH="$HARDWARE.bin"
			else
				FILEWISH="$HARDWARE.sysupgrade.bin"
				FILEWISH="$( echo "$FILEWISH" | sed 's|/|:|g' )"
			fi

			# very special: slashes are not allowed in filename
			FILEWISH="$( echo "$FILEWISH" | sed 's|/|:|g' )"

			case "$COMMAND" in
				crc)
					local i=0
					local GENERATED VERSION KERNEL MAINTAINER CRC url

					[ "$UPDATEMODE" = "0" ] && i=100

					url="$BASE/$ARCHITECTURE/images/$UPDATEMODE/info.txt"
# if pattern/filename matches, get 2nd word:
# NEW:
# CRC[md5]: 6128dc961fb0369df5ae79dc7a0654db  SIZE[byte]: 999999  BLOCKS[64k]: 49  FILE: 'La Fonera 2.0N.bin'  USECASE: b1cc2a438170a6fff4d08b08da4030af = Standard,LuCIfull,VDS,kalua  REV: r45678
# OLD:
# CRC[md5]: 6128dc961fb0369df5ae79dc7a0654db  SIZE[byte]: 999999  BLOCKS[64k]: 49  FILE: 'La Fonera 2.0N.bin'

					get_crc()
					{
						local url="$1"
						local usecase="$2"

						_wget do "$url" |
						 while read LINE; do {
							case "$LINE" in
								*"'${FILEWISH}'${usecase:+  USECASE: }${usecase}${usecase:+ = }"*)
									echo "$LINE" | cut -d' ' -f2
									return 111
								;;
								"# END")
									echo "0"
									return 111
								;;
							esac
						} done

						test $? -eq 111
					}

					while [ $i -lt 100 ]; do {
						if get_crc "$url" "$usecase"; then
							break
						else
							_log sleep "firmware_getcrc_run_${i}_outof_100" 10 step 1
							i=$(( $i + 1 ))
						fi
					} done
				;;
				*)
					echo -n "$BASE/$ARCHITECTURE/images/$UPDATEMODE/${dir}$( _sanitizer do "$FILEWISH" urlvalue )"
				;;
			esac
		;;
	esac
}
