#!/bin/sh

_linklocal_detect()
{
	:

	# this should run every minute and
	# detect all changes of
	# - arp-cache
	# - wifi-assoclist
	# - olsr-neighs / routing-proto-neighs
	# - dhcp-lease-changes
	# and produce some lists of this to easy work with
}

_linklocal_wifi_users()
{
	local WIFI_DEV="$1"
	local WIFIASSOC="$( _wifi assoclist $WIFI_DEV )"
	local DHCPLEASES="$( _net dhcp_lease_filename )"
	local MAC
	local I=0

	[ ! -e "$DHCPLEASES" ] && return 1

	while read -r LINE; do {
		set $LINE
		MAC="$2"

		echo "$WIFIASSOC" | grep -q -i "${MAC:-unset}" && {
			echo $MAC
			I=$(( I + 1 ))
		}
	} done <$DHCPLEASES

	[ $I -eq 0 ] && return 1
	return 0
}
