#!/bin/sh

_list_contains_element()
{
	local list="$1"
	local element="$2"

	case " $list " in		# e.g. ' A B C '
		*" $element "*)		#        ' B '
			return 0
		;;
		*)
			return 1
		;;
	esac
}

_list_uniq()
{
	local list="$1"
	local obj

	for obj in $list; do {
		echo "$obj"
	} done | sort -u
}

_list_count_elements()
{
	local list="$1"
	local i=0 obj

	for obj in $list; do i=$(( i + 1 )); done

	echo $i
}

_list_remove_element()
{
	local list="$1"
	local id_remove="$2"	# number or string
	local is_is_string="$3"	# keyword 'string'
	local obj
	local i=0

	if [ -z "$is_is_string" ]; then
		for obj in $list; do {
			i=$(( i + 1 ))
			[ $i -eq $id_remove ] || echo "$obj"
		} done
	else
		for obj in $list; do {
			i=$(( i + 1 ))
			[ "$obj" = "$id_remove" ] || echo "$obj"
		} done
	fi
}

_list_shuffle()		# needs ~4 sec for 100 elements
{
	local funcname='list_shuffle'
	local list="$1"
	local option="$2"	# <empty> or 'get_first_random'
	local obj i roll
	local list_size="$( _list count_elements "$list" )"

	while [ -n "$list" ]; do {
		i=0
		roll="$( _math random_integer 1 $list_size )"

		for obj in $list; do {
			i=$(( i + 1 ))
			[ $i -eq $roll ] && {
				echo "$obj"
				list="$( _list remove_element "$list" $i )"
				list_size=$(( list_size - 1 ))

				if [ "$option" = 'get_first_random' ]; then
					return 0
				else
					break
				fi
			}
		} done
	} done
}

_list_random_element()
{
	local list="$1"
	local obj

	_list shuffle "$list" get_first_random
}
