#!/bin/sh

_list_contains_element()
{
	local list="$1"
	local element="$2"

	case " $list " in		# e.g. ' A B C '
		*" $element "*)		#        ' B '
			return 0
		;;
		*)
			return 1
		;;
	esac
}

_list_uniq()
{
	local list="$1"
	local obj

	for obj in $list; do {
		echo "$obj"
	} done | sort -u
}

_list_count_elements()
{
	local list="$1"
	local i=0 obj

	for obj in $list; do i=$(( i + 1 )); done

	echo $i
}

_list_remove_element()
{
	local list="$1"
	local id_remove="$2"	# number or string
	local obj
	local i=0

	for obj in $list; do {
		i=$(( i + 1 ))
		[ "$i" = "$id_remove" -o "$obj" = "$id_remove" ] || echo "$obj"
	} done
}

_list_shuffle()
{
	local list="$1"
	local option="$2"	# <empty> or 'get_first_random'
    local list_size=$(_list count_elements "$list")

	[ "$list_size" = 1 ] && {
		echo "$list"
		return 0
	}

	_log do list_shuffle daemon debug "sorting list with $list_size elements"
	_stopwatch start "list_shuffle_$list_size"

        
	[ "$option" = 'get_first_random' ] && {
	        list=$(echo "$list" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -s ' ' '\n' | shuf | head -n1)
        } || {
            list=$(echo "$list" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -s ' ' '\n' | shuf | tr '\n' ' ')
	}
        echo "$list" 

	_stopwatch stop "list_shuffle_$list_size" quiet
}

_list_random_element()
{
	local list="$1"
	local obj

	_list shuffle "$list" get_first_random
}
