#!/bin/sh

_list_uniq()
{
	local list="$1"
	local obj

	for obj in $list; do {
		echo "$obj"
	} done | sort | uniq
}

_list_count_elements()
{
	local list="$1"
	local i=0 obj

	for obj in $list; do i=$(( $i + 1 )); done

	echo $i
}

_list_remove_element()
{
	local list="$1"
	local id_remove="$2"	# number or string
	local obj
	local i=0

	for obj in $list; do {
		i=$(( $i + 1 ))
		[ "$i" = "$id_remove" -o "$obj" = "$id_remove" ] || echo "$obj"
	} done
}

_list_shuffle()
{
	local list="$1"
	local list_size="$( _list count_elements "$list" )"
	local sorted=0
	local obj i

	[ "$list_size" = 1 ] && {
		echo "$list"
		return 0
	}

	_log do list_shuffle daemon debug "sorting list with $list_size elements"
	_stopwatch start "list_shuffle_$list_size"

	while [ $sorted -ne $list_size ]; do {

		i=0
		for obj in $list; do {
			i=$(( $i + 1 ))

			[ "$( _math random_integer 1 $( _list count_elements "$list" ) )" = "1" ] && {
				echo "$obj"
				sorted=$(( $sorted + 1 ))
				list="$( _list remove_element "$list" "$i" )"
				break
			}
		} done
	} done

	_stopwatch stop "list_shuffle_$list_size" quiet
}

_list_random_element()
{
	local list="$1"
	local obj

	for obj in $( _list shuffle "$list" ); do break; done
	echo "$obj"
}
