#!/bin/sh

_net_ping_getlatency()
{
	local server="$1"	# e.g. <ip> or <host>
	local pings="${2:-3}"

	# round-trip min/avg/max = 24.638/24.638/24.638 ms	// busybox
	# rtt min/avg/max/mdev = 33.415/33.415/33.415/0.000 ms	// debian
	set -- $( ping -q -c${pings} -W1 "$server" 2>/dev/null | tail -n1 )

	# bad return on error
	test -n "$4" &&	{
		# round-trip min/avg/max = 15.887/24.931/42.406 ms
		# -> 15.887/24.931/42.406 -> 15 887 24 931 42 406
		local oldIFS="$IFS"; IFS=[/.]; set -- $4; IFS="$oldIFS"

		# output 'average' round trip time: 24.931 -> 24
		echo "$3"
	}
}

_net_refresh_dnshosts ()
{
	local pid="$( _system get_first_pid dnsmasq )"

	[ -n "$pid" ] && {
		kill -SIGUSR1 $pid		# logging stats
		kill -HUP $pid			# reread e.g. /etc/hosts + /etc/ethers + /var/run/hosts_olsr
	}
}

_net_dhcp_lease_filename()
{
	local file

	if   [ -e /tmp/dhcp.leases ]; then		# openwrt

		file="/tmp/dhcp.leases"

	elif [ -e /var/run/dhcp.leases ]; then		# freifunk-firmware

		file="/var/run/dhcp.leases"
	else
		file="$( uci -q get dhcp.@dnsmasq[0].leasefile )"
	fi

	[ -z "$file" ] && {
		file="/tmp/fake_dhcp_lease_file"
		touch "$file"
	}

	echo "$file"
}

_net_mac2vendor()
{
	local oui="$1"				# ab12cd | AB12CD | 1122334455AA | 11-22-33-44-55-aa | 11:22:33:44:55:AA
	local option="$2"			# e.g. 'short'
	local url="http://84.38.67.43/oui"	# see /api.txt

	if   [ ${#oui} -eq 6 -o ${#oui} -eq 12 ]; then
		:
	elif [ ${#oui} -eq 17 ]; then
		oui=${oui//:/}
		oui=${oui//-/}
		[ ${#oui} -eq 12 ] || return 1
	else
		[ ${#oui} -eq 0 ] && return 1
		oui="$( _sanitizer do "$oui" mac hex lowercase length:6 )"
		[ ${#oui} -eq 6 ] || return 1
	fi

	case "${oui:1:1}" in
		*2|*3|*6|*7|*a|*b|*e|*f)
			echo "locally_administered"
		;;
		*)
			local cache="/tmp/oui/$oui"
			[ -e "$cache" ] || {
				mkdir -p "/tmp/oui"
				url="$url/${oui:0:2}/${oui:2:2}/${oui:4:2}"
				_wget do "$url" 5 >"$cache" 2>/dev/null
			}

			if [ "$option" = "short" ]; then
				head -n1 "$cache"
			else
				cat "$cache"
			fi
		;;
	esac
}

_net_ip4_is_private ()		# RFC-1918
{
	case "$1" in 192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[0-1].*|169.254.*|10.*|127.*) return 0 ;; esac
	return 1
}

_net_ip2dns ()
{
	local IP="$1"
	local OLSR

	if   [ -e /var/etc/hosts ]; then
		OLSR="/var/etc/hosts"			# freifunk-firmware
	elif [ -e /var/run/hosts_olsr ]; then
		OLSR="/var/run/hosts_olsr"		# openwrt
	fi

	[ -n "$OLSR" ] && {
		fgrep -q "$IP	" $OLSR && {
			sed -n "/$IP	/{s/^.*	\([a-zA-Z0-9\._-]*\)	.*/\1/p;q}" $OLSR
			return 0
		}
	}

	nslookup $IP | sed -n "s/^Name:[^a-zA-Z0-9]*\(.*\)/\1/p"
}

_net_ip2mac()		# ofcourse this works only for local IP's, but: maybe we want to "guess" using /etc/ethers...?
{
	local get_ip="$1"
	local line ip mac

	while read line; do {

		set ${line:-unset}
		ip="$1"
		mac="$4"

		[ "$ip" = "$get_ip" ] && {
			_sanitizer do "$mac" lowercase >"/tmp/IP2MAC_${get_ip}"
			cat "/tmp/IP2MAC_${get_ip}"
			return 0
		}

	} done </proc/net/arp

	[ -e "/tmp/IP2MAC_${get_ip}" ] && {
		cat "/tmp/IP2MAC_${get_ip}"
	}
}

_net_dns2ip ()
{
	local line ip go

	nslookup "$1" |
	 while read line; do {
		case "$line" in
			Name*)
				go=1
			;;
			Address*)
				[ -z "$go" ] && continue

				ip="${line#*: }"	# e.g. 'Address 1: 2a02:2e0:3fe:100::8 redirector.heise.de'

				case "$ip" in
					*:*)
						continue	# for now we omit ipv6
					;;
					" "*)
						ip="${ip#* }"
						ip="${ip#* }"
						ip="${ip#* }"
					;;
				esac

				ip="${ip% *}"		# e.g. 'Address 1: 84.38.67.43'
							# e.g. 'Address 2: 193.99.144.80 redirector.heise.de'
							# e.g. 'Address:    193.99.144.80'	// spaces on kernel 2.4
				echo "$ip"
			;;
		esac
	} done
}

_net_dev2ip()		# only first ip
{
	local dev="$1"
	local option="$2"	# "ip"|"mask"
	local type="$3"		# "cidr"
	local line ip_with_mask key

	line="$( ip -oneline -f inet address show dev $dev )"

	set ${line:-is_empty}

	case "$3" in
		inet)
			key=$5

			case "$key" in
				brd|scope)
					# e.g.:
					# 6: wlan0    inet 10.63.10.1/8 brd 10.255.255.255 scope global wlan0
					# 7: wlan0-1    inet 10.63.10.1/32 scope global wlan0-1
					ip_with_mask="$4"
				;;
				*)
					# e.g.:
					# 8: ppp0 inet 84.183.156.159 peer 217.0.116.17/32 scope global ppp0
					ip_with_mask="$6"
				;;
			esac
		;;
		*)
			return 1
		;;
	esac

	case "$option" in
		mask)
			case "$type" in
				cidr)
					echo $ip_with_mask | cut -d'/' -f2
				;;
				*)
					_net cidr2mask "$( echo $ip_with_mask | cut -d'/' -f2 )"
				;;
			esac
		;;
		*)
			echo $ip_with_mask | cut -d'/' -f1
		;;
	esac

	return
}

_net_dev2mac ()
{
	ip -o link show $1 | sed -n 's/^.*ether \(..:..:..:..:..:..\) .*/\1/p;q'
}

_net_devtype2symbol ()
{
	case $1 in
		tunnel) echo -n '=' ;;
	 	  wifi) echo -n '~' ;;
		     *) echo -n "-" ;;
	esac
}

_net_dev_type ()		# OUT1: string, "wifi/tunnel/wire"
{
	local DEV="$1"
	local OPTION="$2"	# short
	local OUT
	
	if   _net dev_is_wifi $DEV ; then
		OUT="wifi"
	elif _net dev_is_tuntap $DEV ; then
		OUT="tunnel"
	else
		OUT="wire"
	fi
	
	[ "$OPTION" = "short" ] && {
		OUT="$( _net devtype2symbol )"
	}
	
	echo -n "$OUT"
}

_net_dev_is_wifi ()
{
	grep -q "^.*$1:" /proc/net/wireless && return 0
	return 1
}

_net_dev_is_tuntap ()
{
	local KEYWORD="$( echo $1 | sed -n 's/^\([a-z]*\)[0-9]*/\1/p' )"
	
	[ "$KEYWORD" = "tun" ] && return 0
	[ "$KEYWORD" = "tap" ] && return 0
	return 1
}

_net_ip2dev()		# outputs real devname like 'br0' or 'wlan0-1'
{
	ip -oneline route get $1 | sed -n 's/^.* dev \([a-zA-Z0-9@\.-]*\)[^a-z]*src .*/\1/p'
}

_net_local_inet_offer ()		# SENS: check if default-route is local
{					# OUT1: string, false|wan|lan|pppoe
	local MODE="false"		# RC: true = inetoffer, false = no inetoffer
	local FUNC="net_local_inet_offer"
	local PHYDEV=0
	local METRIC=0
	local D=0
	local N=0
	local trash
	local wan_proto="$( uci -q get network.wan.proto )"

	[ "$wan_proto" = "pppoe" ] && {
		_log do $FUNC daemon info "early_boot_estimation: pppoe"
		echo "pppoe"
		return 0
	}

	[ -e /tmp/NETPARAM ] || {
		local WAN_GATEWAY="$( uci -q get network.wan.gateway )"
		[ -n "$WAN_GATEWAY" ] && {
			if [ "$WAN_GATEWAY" = "0.0.0.0" ]; then
				_nvram set wan_gateway 
				_nvram set commit "config-mistake, unsetting wan-gateway which was '$WAN_GATEWAY'"
			else
				[ "$wan_proto" = "pppoe" ] && {
					_log do $FUNC daemon info "early_boot_estimation: pppoe"
					echo "pppoe"
					return 0			# fixme!
				}
			
				_log do $FUNC daemon info "early_boot_estimation: wan"
				echo "wan"
				return 0
			fi
		}

		[ -n "$( uci -q get network.lan.gateway )" ] && {
			_log do $FUNC daemon info "early_boot_estimation: lan"
			echo "lan"
			return 0
		}

		/etc/init.d/S52vpnc_fff+ check && {
			_log do $FUNC daemon info "early_boot_estimation: tun"
			echo "tun"
			return 0
		}

		# fixme! wan-dhcp?

		_log do $FUNC daemon info "early_boot_estimation: false"
		echo "false"
		return 1
	}

	local LAN_GATEWAY="$( uci -q get network.lan.gateway )"
	[ -n "$LAN_GATEWAY" ] && {
		[ -z "$( ip route list exact 0.0.0.0/0 via $LAN_GATEWAY )" ] && {
			[ "$LAN_GATEWAY" != "0.0.0.0" ] && {
				_log do $FUNC daemon info "alien_gateway '$LAN_GATEWAY': lan"
				echo "lan"
				return 0
			}
		}
	}

	# only look for the first default-route
	# some examples:
	#
	# default via 192.168.1.1 dev vlan1		-> wan-offer|wan_gateway
	# default via 191.255.255.1 dev venet0		-> root-server
	# default via 217.0.116.253 dev ppp0		-> pppoe
	# default dev tun0  scope link			-> vpnc
	# default via 10.63.52.36 dev br0 		-> lan-offer|lan-gateway
	# default via 10.63.99.33 dev eth0.1  metric 2 onlink		-> since ~git29366 "onlink"
	# default via 192.168.101.112 dev eth0.1  src 192.168.101.222	-> lan-offer via alias-interface
	# # default via 192.168.1.1 dev eth1  proto static ->841nd

	eval $( ip route list exact 0.0.0.0/0 | head -n1 |
		while read N N D N PHYDEV METRIC N trash; do {	# we must eval it, otherwise		// fixme! look for 'table all'?
			echo PHYDEV=$PHYDEV			# the vars from subprocess are
			echo METRIC=$METRIC			# not known
			echo N=$N
			echo D=$D				# fixme! better use 'eval $( ip route list exact 0.0.0.0/0 | sed 'xyz' )'
		} done
	)

	[ "$METRIC" = "src" ] && METRIC=			# lan-offer via alias-interface
	[ "$N" = static ] && METRIC=

	if [ -z "$METRIC" ]; then				# found no metric = local inet-offer

		_log do $FUNC daemon debug "PHYDEV: '$PHYDEV' METRIC: '$METRIC' N: '$N' D: '$D'"

		if [ -z "${PHYDEV}${METRIC}${N}" ]; then	# ip route list exact 0.0.0.0/0 -> "default via eth0" or similar

			[ "$LAN_GATEWAY" = "0.0.0.0" ] && {	# fixme! move to early-boot-estimation
				
				_nvram set lan_gateway 
				_nvram set commit "config-mistake, unsetting lan-gateway which was '$LAN_GATEWAY'"
				
				ip route delete default via $D
			}
		else
			if   [ "$PHYDEV" = "$WANDEV" ]; then
				MODE="wan"
			elif [ "$PHYDEV" = "$LANDEV" ]; then
				MODE="lan"
			elif [ "$PHYDEV" = "$WIFIDEV" ]; then
				MODE="wifi"
			else
				MODE="pppoe"	# && WANDEV=ppp0          # fixme! this is not exact!
			fi
			
			[ "$PHYDEV" = "link" ] && {
				if   echo $D | grep -q "^tun[0-9]*" ; then
					MODE=tun
				elif echo $D | grep -q "^tap[0-9]*" ; then
					MODE=tap
				else
					MODE="$D"				# e.g. tun0 / vpnc
				fi
			}
			
			_log do $FUNC daemon info "found local default-gateway over device '$PHYDEV' = '$MODE'"
		fi
	else
		if [ $N -eq 0 ]; then
			_log do $FUNC daemon info "no local default-gateway, no default-gateway, no internet 8-("
		else
			_log do $FUNC daemon info "no local default-gateway found, only $N hops away 8-)"
		fi
	fi

	echo $MODE

	[ "$MODE" = "false" ] && return 1	
	return 0
}

_net_inet_seems_stable ()					# fixme! also check path to gateway (add wireless costs/hops)
{								# fixme! apply these checks regulary
	local FILE="/tmp/GATEWAY_CHECK_RECENT_COSTINT_ONLY"	# fixme! test dns also?
	local FUNC="inet_seems_stable"				# fixme! use dnsfaker if unstable/unfake if stable
	local max_cost="50000"					# fixme! till we found a better way to guess

	_olsr uptime is_short || {
		[ -z "$( ip route list exact 0.0.0.0/0 table main )" ] && {
			_log do $FUNC daemon alert "unstable inet, no default route in main-table"
			return 1
		}
	}

	[ -e "$FILE" ] && {
		read COST_INT <$FILE

		[ "$COST_INT" 2>/dev/null -gt $max_cost ] && {
			_log do $FUNC daemon alert "unstable inet1, cost_int: '$COST_INT' > $max_cost"
			return 1
		}
		
		[ "$COST_INT" = "0" -a "$COST" != "1.00" ] && {
			_log do $FUNC daemon alert "unstable inet2, cost_int: '$COST_INT'"
			return 1
		}
	}

	return 0
}

_net_mac2ip ()		# SENS: get client-IP from different sources
{
	local mac="$1"
	local funcname="mac2ip"

	[ -z "$mac" ] && return 1

	_sanitizer include

	local MAC="$( _sanitizer do "${mac:-unset_mac}" lowercase )"
	local IP=
	local HOSTNAME=
	local COUNT=

	try_1()		# is filled during _netfiler_user_add() (macs are lowercase)
	{
		if [ -e "/tmp/MAC2IP_$MAC" ]; then
			read IP <"/tmp/MAC2IP_$MAC"
		else
			[ -e "/tmp/NETFILTER/MAC2IP/$MAC" ] && {
				read IP <"/tmp/NETFILTER/MAC2IP/$MAC"
			}
		fi
	}

	try_2()		# arp-cache (macs are lowercase)
	{
		local mac ip line

		while read line; do {
			set $line
			ip="$1"
			mac="$( _sanitizer do "$4" lowercase )"

			[ "$MAC" = "$mac" ] && {
				IP="$ip"
				return
			}

		} done </proc/net/arp
	}

	try_3()		# DHCP-leases (macs are lowercase)
	{
		local leasefile="$( _net dhcp_lease_filename )"

		[ -e "$leasefile" ] && {
			IP="$( sed -e "/$MAC/!d" -ne 's/^.* ..:..:..:..:..:.. \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\) .*/\1/p' "$leasefile" )"
		}
	}

	try_4()		# /etc/ethers -> /etc/local.hosts (macs are lowercase)
	{
		HOSTNAME="$( sed -n "s/^$MAC \(.*\)/\1/p" /etc/ethers 2>/dev/null )"
		[ -n "$HOSTNAME" ] && IP="$( sed -n "/$HOSTNAME/s/^\([0-9\.]*\) ${HOSTNAME}.*/\1/p" /etc/local.hosts )"
	}

	for COUNT in 1 2 3 4 ; do {

		try_${COUNT}

		[ -n "$IP" ] && {
			echo "$MAC" >/tmp/IP2MAC_$IP
			echo "$IP"
			return 0
		}
	} done

	_log do $funcname daemon info "could not get ip for mac $MAC"
	return 1
}


_net_mac2dev ()
{
	local get_mac="$1"
	local mac dev dummy

	_sanitizer include

	while read dummy dummy dummy mac dummy dev; do {
		mac="$( _sanitizer do "$mac" lowercase )"

		[ "$get_mac" = "$mac" ] && {
			echo $dev
			return
		}

	} done </proc/net/arp
}

_net_mac2media()
{
	local MAC="$1"				# ARG1: (string) mac-address
	local SHORT="$2"			# ARG2: (string) keyword "short" (optional)
	local OUT=0				# OUT1: (string) wifi,wire OR ~,-
	local DEV="$( _net mac2dev $MAC )"

	  if [ "$DEV" = "$WIFIDEV" ]; then
	  	OUT=wifi
	elif uci -q get system.@ethers[0].wifi | grep -qi $MAC ; then
		OUT=wifi
	elif grep -sq ^"$( _sanitizer do "$( _net mac2ip $MAC )" escape_dots );" /tmp/CLIENTS_WIFI ; then
		OUT=wifi
	else
		OUT=wire		# fixme! this can also be guessed!
	fi

	[ -n "$SHORT" ] && OUT="$( _net devtype2symbol $DEV )"

	echo -n "$OUT"
}

_net_mask2cidr ()
{
	local o

	case $1 in
		255.255.255.254) o=31 ;;
		255.255.255.252) o=30 ;;
		255.255.255.248) o=29 ;;
		255.255.255.240) o=28 ;;
		255.255.255.224) o=27 ;;
		255.255.255.192) o=26 ;;
		255.255.255.128) o=25 ;;
		255.255.255.0) o=24 ;;
		255.255.254.0) o=23 ;;
		255.255.252.0) o=22 ;;
		255.255.248.0) o=21 ;;
		255.255.240.0) o=20 ;;
		255.255.224.0) o=19 ;;
		255.255.192.0) o=18 ;;
		255.255.128.0) o=17 ;;
		255.255.0.0) o=16 ;;
		255.254.0.0) o=15 ;;
		255.252.0.0) o=14 ;;
		255.248.0.0) o=13 ;;
		255.240.0.0) o=12 ;;
		255.224.0.0) o=11 ;;
		255.192.0.0) o=10 ;;
		255.128.0.0) o=9 ;;
		255.0.0.0) o=8 ;;
		254.0.0.0) o=7 ;;
		252.0.0.0) o=6 ;;
		248.0.0.0) o=5 ;;
		240.0.0.0) o=4 ;;
		224.0.0.0) o=3 ;;
		192.0.0.0) o=2 ;;
		128.0.0.0) o=1 ;;
		*) o=32 ;;
	esac

	echo -n $o
}

_net_cidr2mask ()		# OUT1: string
{
	local o
	
	case $1 in
		31) o=255.255.255.254 ;;
		30) o=255.255.255.252 ;;
		29) o=255.255.255.248 ;;
		28) o=255.255.255.240 ;;
		27) o=255.255.255.224 ;;
		26) o=255.255.255.192 ;;
		25) o=255.255.255.128 ;;
		24) o=255.255.255.0 ;;
		23) o=255.255.254.0 ;;
		22) o=255.255.252.0 ;;
		21) o=255.255.248.0 ;;
		20) o=255.255.240.0 ;;
		19) o=255.255.224.0 ;;
		18) o=255.255.192.0 ;;
		17) o=255.255.128.0 ;;
		16) o=255.255.0.0 ;;
		15) o=255.254.0.0 ;;
		14) o=255.252.0.0 ;;
		13) o=255.248.0.0 ;;
		12) o=255.240.0.0 ;;
		11) o=255.224.0.0 ;;
		10) o=255.192.0.0 ;;
		 9) o=255.128.0.0 ;;
		 8) o=255.0.0.0 ;;
		 7) o=254.0.0.0 ;;
		 6) o=252.0.0.0 ;;
		 5) o=248.0.0.0 ;;
		 4) o=240.0.0.0 ;;
		 3) o=224.0.0.0 ;;
		 2) o=192.0.0.0 ;;
		 1) o=128.0.0.0 ;;
		 *) o=255.255.255.255 ;;
	esac
	
	echo -n $o
}
