#!/bin/sh

_phone_config_book ()
{
	uci get sms.@sms[0].phonebook
}

_phone_book_show ()
{
	local PHONEBOOK="$( _phone config_book )"
	local SEARCH="${1:-=}"

	echo "$PHONEBOOK" | sed -e 's/;/\n/g' -e 's/=/ = /g' | grep -i "$SEARCH"
}

_phone_book_name2number ()
{
	local DEST="$1"					# ARG1: string (peter or 0177/2821234 or several comma-separated numbers)
	local OUT old_ifs number list_numbers		# OUT1: string (number or keyword "invalid")
	local PHONEBOOK="$( _phone config_book )"	# klaus=0177/2821234;peter=0179/1234567;...

	[ -z "$DEST" ] && {				# output hole phonebook

		local oldifs="$IFS"
		IFS=";"
		for DEST in $PHONEBOOK; do {
			echo $DEST
		} done
		IFS="$oldifs"

		return 1
	}

	if echo "$PHONEBOOK" | grep -q "${DEST}=" ; then	# is in phonebook, convert NAME to NUMBER
		OUT="$( echo "$PHONEBOOK" | sed 's/[^0-9a-zA-Z;=]//g' | sed "s/.*$DEST=\([0-9]*\).*/\1/" )"
	else
		OUT="$DEST"					# not in phonebook
	fi

	case "$OUT" in
		*","*)
			old_ifs="$IFS"
			IFS=","

			for number in $DEST; do {
				list_numbers="${list_numbers}${list_numbers:+,}$( _sanitizer run "$number" numeric )"
			} done

			IFS="$old_ifs"
			OUT="$list_numbers"
		;;
		*)
			OUT="$( _sanitizer run "$OUT" numeric )"
		;;
	esac

	if [ -z "$OUT" ] || [ -z "$DEST" ]; then
		echo "invalid"
		return 1
	fi

	echo "$OUT"
}

_phone_number2name ()
{
	local NUMBER="$1"				# e.g. 03643/43410
	local LIST_API="dasoertliche goyellow"
	local API CALLER_NAME CALLER_DETAILS

	for API in $LIST_API; do {

		eval "$( _phone number2name_$API "$( _sanitizer run "$NUMBER" numeric )" )"

		echo "API: $API"
		echo "NAME: $CALLER_NAME"
		echo "DETAILS: $CALLER_DETAILS"
		echo "#"
	} done
}

_phone_number2name_dasoertliche ()	# fixme! b0rken
{
	wget -qO - "http://www1.dasoertliche.de/?form_name=search_inv&ph=${1}" |
	 sed -ne "s/^.*onmouseover=\"\"  >\(.*\)<\/a>.*/CALLER_NAME='\1';/p" \
	      -e "s/^[^a-zA-Z0-9]*\([a-zA-Z0-9].*\)<br\/>/CALLER_DETAILS='\1';/p" |
	  sed -e 's/&nbsp;/ /g' -e 's/nbsp;/ /g'
}

_phone_number2name_goyellow ()		# fixme! b0rken
{
	wget -qO - "http://www.goyellow.de/schnellsuche/?LIP=simpleSearch&MDN=${1}&LOC=" |
	 sed -ne "s/^.*title=\"Detailinformationen.*);\">\(.*\)<\/a>/CALLER_NAME='\1'/p" \
	      -e "s/^<p class=\"address\">\(.*\)<\/p>/CALLER_DETAILS='\1'/p"
}
