#!/bin/sh

_roaming_debug()
{
	local file="$TMPDIR/roaming_debug"
	local line line2

	tail -n 100  "$file"
	tail -n 1 -f "$file" | while read -r line; do {
		line2="$( sort -n "$file" | tail -n1 )"

		if [ "$line2" = "$line" ]; then
			echo "$line"
		else
			echo "$line"
			echo "$line2"
		fi
	} done
}
