#!/bin/sh

_ssh_key_public_fingerprint_get()	# output differs, wether its a SHA1 or MD5 hash
{
	local option="$1"		# keywords: 'retry' or 'keyfilename' or <empty>
	local me='ssh_key_public_fingerprint_get'
	local file_openwrt1='/etc/dropbear/dropbear_dss_host_key'
	local file_openwrt2='/etc/dropbear/dropbear_rsa_host_key'	# since r46814
	local file_debian='/etc/ssh/ssh_host_rsa_key'
	local nop file

	[ "$option" = 'keyfilename' ] && nop=':'

	if   [ -e "$file_openwrt2" ]; then	# try modern first
		file="$file_openwrt2"
		$nop dropbearkey -y -f "$file" | fgrep 'Fingerprint:' | cut -d' ' -f3
	elif [ -e "$file_openwrt1" ]; then
		file="$file_openwrt1"
		$nop dropbearkey -y -f "$file" | fgrep 'Fingerprint:' | cut -d' ' -f3
	elif [ -e "$file_debian" ]; then
		file="$file_debian"
		$nop ssh-keygen -l -f "$file" | cut -d' ' -f2
	else
		[ -z "$option" ] && {
			_ssh sanitize_and_cleanup_keys && _$me 'retry'
		}
	fi

	[ -n "$file" -a "$option" = 'keyfilename' ] && echo "$file"
}

_ssh_start()
{
	/etc/init.d/dropbear start
}

_ssh_stop()
{
	killall dropbear
	sleep 3
	local pid="$( _system get_first_pid dropbear )"
	[ -n "$pid" ] && kill -9 $pid
}

_ssh_regen_keys()
{
	local funcname='ssh_regen_keys'
	local file1='/etc/dropbear/dropbear_dss_host_key'
	local file2='/etc/dropbear/dropbear_rsa_host_key'
	local file

	_log it $funcname daemon info '[START]'

	for file in $file1 $file.pub $file2 $file2.pub; do {
		[ -e "$file" ] && rm "$file"
	} done

	_ssh start

	[ -e "/tmp/$funcname" ] && rm "/tmp/$funcname"
	while true; do {
		[ -e "$file1" ] && break
		[ -e "$file2" ] && break
		_watch counter "/tmp/$funcname" increment 1 max 100 || return 0
		sleep 1
	} done

	_ssh sanitize_and_cleanup_keys

	_log it $funcname daemon info '[READY]'
}

_ssh_generate_and_store_private_dss_key ()
{
	local DSSFILE="/etc/dropbear/dropbear_dss_host_key"

	dropbearkey -t dss -f "$DSSFILE"

	_nvram set ff_dsskey $( _file convert_bin2hex "$DSSFILE" )
	_nvram set commit "set new dropbearkey_dsskey"
}

_ssh_sanitize_and_cleanup_keys()
{
	local funcname='ssh_sanitize_and_cleanup_keys'
	local DSSFILE="/etc/dropbear/dropbear_dss_host_key"		# if no dropbear is in firmware and we install it,
	local DSSKEY="$( _nvram get 'ff_dsskey' )"			# the key in nvram is not respected
	local TEMP="/tmp/DSSKEY"
	local file

	pubfile_ok()
	{
		[ -e '/usr/bin/dropbearkey' ] || return 0		# simulate OK
		[ -e "${DSSFILE}.pub" ] || return 1
		[ $( _file size "${DSSFILE}.pub" ) -eq 0 ] && return 1

		return 0
	}

	pubfile_ok || {
		_log it $funcname daemon info "writing ${DSSFILE}.pub"

		if [ -e '/etc/dropbear/dropbear_rsa_host_key' ]; then
			file='/etc/dropbear/dropbear_rsa_host_key'	# since r46814 - TODO!
		else
			file='/etc/dropbear/dropbear_dss_host_key'
		fi

		dropbearkey -y -f "$file" | grep ^'ssh-' >"${DSSFILE}.pub"
		chmod 0600 "${DSSFILE}.pub"
	}

	if [ -L $HOME/.ssh ]; then
		:
	else
		rm -fR $HOME/.ssh
		ln -s /etc/dropbear $HOME/.ssh
	fi
}
