#!/bin/sh

_stopwatch_start()
{
	local job="${1:-unset}"
	local keyword="$2"		# e.g. global
	local up rest file

	if [ "$keyword" = "global" ]; then
		file="/tmp/STOPWATCH_${job}"
	else
		file="/tmp/STOPWATCH_${job}_$$"
	fi

	read up rest </proc/uptime
	echo "${up%.*}${up#*.}" >$file
}

_stopwatch_seconds2humanreadable()
{
	local integer="$1"
	local humanreadable min sec hours days

	min=$(( $integer / 60 ))
	sec=$(( $integer % 60 ))

	if   [ $min -gt 1440 ]; then
		days=$(( $min / 1440 ))
		min=$(( $min % 1440 ))
		hours=$(( $min / 60 ))
		min=$(( $min % 60 ))
		humanreadable="${days}d ${hours}h ${min}min ${sec}sec"
	elif [ $min -gt 60 ]; then
		hours=$(( $min / 60 ))
		min=$(( $min % 60 ))
		humanreadable="${hours}h ${min}min ${sec}sec"
	elif [ $min -gt 0 ]; then
		humanreadable="${min}min ${sec}sec"
	else
		humanreadable="${sec}sec"
	fi

	echo "$humanreadable"
}

_stopwatch_stop()		# OUT1: centyseconds = seconds/100
{
	local FUNC="stopwatch_stop"
	local CONTEXT="${1:-unset}"
	local KEYWORD="$2"				# e.g. quiet|global|nolog|speed
	local object_count="$3"				# e.g. 32
	local object_type="$4"				# e.g. tickets

	local up rest DIFF humanreadable FILE logprio
	local START END OUT INTEGER REST message speed

	read up rest </proc/uptime

	if [ "$KEYWORD" = "global" ]; then
		logprio="alert"
		FILE="/tmp/STOPWATCH_${CONTEXT}"
	else
		logprio="info"
		FILE="/tmp/STOPWATCH_${CONTEXT}_$$"
	fi

	[ ! -e "$FILE" ] && {
		_log do $FUNC daemon debug "timefile '$FILE' not found - abort"
		return 1
	}

	read START <$FILE
	rm $FILE
	END="${up%.*}${up#*.}"

	OUT="$(( $END - $START ))"
	REST="$(( $OUT % 100 ))"
	[ $REST -lt 10 ] && REST="0$REST"
	INTEGER="$(( $OUT / 100 ))"

	[ $INTEGER -gt 60 ] && {
		humanreadable="$( _stopwatch seconds2humanreadable $INTEGER )"
		humanreadable=" (${humanreadable})"
	}

	[ -n "$object_type" -a -n "$object_count" ] && {
		# 32 tickets / 12.12sec -> 3200 / 1212 = 2.64
		speed="$(( ${object_count}00 / $OUT )).$(( ${object_count}00 % $OUT ))"
		message=" ($speed $object_type/sec)"
	}

	[ "$KEYWORD" = 'speed' ] && echo "$speed" && return 0
	[ "$KEYWORD" = 'nolog' ] || _log do $FUNC daemon $logprio "task '$CONTEXT' lasts $INTEGER.$REST seconds${humanreadable}${message}"
	[ "$KEYWORD" = 'quiet' ] || echo "$OUT"
}
