#!/bin/sh

CACHE='/tmp/weblogin_cached_for_overload'
STAGE2='true'

case "$QUERY_STRING" in
	'REDIRECTED=1'*)
	;;
	'LOGOUT=1'*)
		. /tmp/loader
		_weblogin html_logoutpage
		STAGE2=
	;;
	*)
		case "${WANADR%.*}" in
			"${REMOTE_ADDR%.*}")
				# ugly: if somebody somehow comes from wired, local WANNET - rewrite IP's
				sed "s/$ANYADR/$WANADR/g" "$CACHE" 2>/dev/null && STAGE2=
			;;
			*)
				cat "$CACHE" 2>/dev/null && STAGE2=
			;;
		esac
	;;
esac

case "$STAGE2" in
	'true')
		. /tmp/loader
		[ -e "$CACHE" ] || _weblogin loginpage_build_cache "$CACHE"
		. /www/cgi-bin-welcome_stage2
	;;
esac
