#!/bin/sh
. /tmp/loader

if [ "$REQUEST_METHOD" = "GET" ] && [ -n "$QUERY_STRING" ]; then

	eval $( _http query_string_sanitize )

	GUI=0
	_tool htmlout_head
	
	NODE="$( _ipsystem do $REMOTE_ADDR  )"
	TIME="$( _system date unixtime      )"
	DATE="$( _system date humanreadable )"

	cat >>/tmp/ARCHIV_TRAFFIC <<EOF
NODE=$NODE TIME=$TIME DATE=$DATE MAC=$MAC NAME=$NAME REG=$REG MEDIA=$MEDIA TRAFF_RECENT=$TRAFF_RECENT TRAFF_TODAY=$TRAFF_TODAY TRAFF_ALL=$TRAFF_ALL
EOF
	tail -n 250 "/tmp/ARCHIV_TRAFFIC"     >"/tmp/ARCHIV_TRAFFIC_temp"
	mv          "/tmp/ARCHIV_TRAFFIC_temp" "/tmp/ARCHIV_TRAFFIC"
	
	echo "OK"
	
	_tool htmlout_foot
else	
	GUI=1
	_tool htmlout_head
	
	echo "<pre>"
	cat /tmp/ARCHIV_TRAFFIC
	echo "</pre>"
	
	_tool htmlout_foot
fi
