#!/bin/sh

. /etc/functions_base_fff+ && func_need vars_old old tool http

eval $(func_http_sanitize_query_string)

fkt_print_html_header

echo "<pre>"
echo "Modus: \"$SOURCE\""
echo

/etc/init.d/S01firmware_update_fff+ forcecheck nopause forcemode $SOURCE

cat <<EOF

Der Router wird nun neugestartet und die Firmware installiert. Sollten Fehler aufgetreten sein, bitte den
"Zurueck" oder "Seite erneut laden"-Knopf des Internet-Browsers benutzen.

Wenn alles ok ist - einfach ca. 60 Minuten warten. Es geht alles automatisch.
</pre>
EOF

fkt_print_html_footer
