#!/bin/sh

. /etc/functions_base_fff+ && func_need old vars_old http nvram log webconfig

fkt_print_html_pre
eval $(_http query_string_sanitize)

if [ "$REQUEST_METHOD" = "POST" ]; then			# do this, if submit-button was pressed		(POST-method)

	if [ "$gui" = "user" ]; then			# USER-Menu (rights-management)
		fkt_formular_gui_user_ready_print_html
	else						# CONFIG-Menu after "profile" was selected
		func_config_process_form_select_profile
	fi
else 							# do this, if ONLY formular is called 		(GET-method)
	case "$gui" in
		user)
			fkt_formular_gui_user_build_vars
			fkt_formular_gui_user_build_lang
			fkt_formular_gui_user_print_html
		;;
		*)
			func_need profile_user
			func_config_print_form_select_profile
		;;
	esac
fi

fkt_print_html_post
