#!/bin/sh

export DATE="19.Dez.2008";SCRIPT=${0#/rom}
export TITLE="Verwaltung - Telnet"
. ${SCRIPT%/*}/cgi-bin-pre.sh

if pidof telnetd >/dev/null; then
	echo "Telnet-Dienst ist schon aktiv"
	exit
else
	echo "Telnet-Dienst wurde gestartet"
	telnetd
fi

. ${SCRIPT%/*}/cgi-bin-post.sh
