#!/bin/sh
. /tmp/loader

# fixme! neuerzeugen von profil, aber altes als vorlage nehmen
# fixme! profil neu erzeugen, dann landeseite aus letzen profil nehmen als vorlage

_log do userdb daemon info "query: '$QUERY_STRING'"

eval $( _http query_string_sanitize )

AMP="&amp;"
BG_0="lightblue"
BG_A="#FAEBD7"
BG_B="#DCDCDC"
ARROW="<b>&rarr;</b>"

_db include

[ -n "$FORM_THEME_NAME" ] && {
	_nvram set fff_weblogin_usernametheme "$FORM_THEME_NAME"		# fixme! we need a way to forward this cleaner
}

if [ -n "$FORM_ACTION_LOGIN_DEL_CHECKED" -o -n "$FORM_ACTION_LOGIN_DEL_RANGE" ]; then

	FORM_ACTION="login_del"

	[ -n "$FORM_CB" ] && {
		LIST_FORM_CHECKBOX="$( _http query_string_group2list FORM_CB_ )"
	}
	
	[ -z "$LIST_FORM_CHECKBOX" ] && {
		LIST_FORM_CHECKBOX="$( _db user login list $FORM_RANGE_METHOD $FORM_RANGE_KEYWORD )"
	}

	_log do login_del_specific daemon info "list: '$LIST_FORM_CHECKBOX'"
	for FORM_ID in $LIST_FORM_CHECKBOX; do {
		_db user login del "$FORM_ID"
	} done
	
	FORM_ACTION="login_show"
fi

if [ -n "$FORM_ACTION_LOGIN_PRINT_CHECKED" -o -n "$FORM_ACTION_LOGIN_PRINT_RANGE" -o -n "$FORM_ACTION_LOGIN_PRINT_RANGE_MARKER" -o -n "$FORM_ACTION_LOGIN_PRINT_CHECKED_MARKER" ]; then

	FORM_ACTION="login_show"

	_log do gui_print_tickets daemon info "[init]" 
	
	[ -n "$FORM_CB" ] && {
		LIST_FORM_CHECKBOX="$( _http query_string_group2list FORM_CB_ )"
	}
	
	[ -z "$LIST_FORM_CHECKBOX" ] && {
		LIST_FORM_CHECKBOX="$( _db user login list $FORM_RANGE_METHOD $FORM_RANGE_KEYWORD )"
	}

	N=0; for I in $LIST_FORM_CHECKBOX; do N=$(( $N + 1 )); done 		# count tickets
	for LOGIN_ID in $LIST_FORM_CHECKBOX; do break; done			# fetch first ticket
	eval $( _db user login show $LOGIN_ID "PROFILE_ID" )			# used_profile_id
	eval $( _db user profile show $PROFILE_ID "NAME" )

	output_mimetype ()
	{
		_log do gui_print_tickets daemon info "filename: '$FILENAME' list: '$LIST_FORM_CHECKBOX'"
		_http header_mimetype_output "$1" "$FILENAME"
	}

	if [ -n "$FORM_ACTION_LOGIN_PRINT_CHECKED" -o -n "$FORM_ACTION_LOGIN_PRINT_RANGE" ]; then

		FILENAME="$( _pdf filename overview "$N" "$NAME" )"
		output_mimetype "application/pdf"

		_pdf output_a4digest "$LIST_FORM_CHECKBOX"		# uebersicht
	else
		FILENAME="$( _pdf filename labels "$N" "$NAME" )"
		output_mimetype "application/pdf"

		_pdf output_a4marker "$LIST_FORM_CHECKBOX"		# labels/etiketten
	fi

	_log do gui_print_tickets daemon info "[done]"
	exit	
fi

case "$FORM_ACTION" in
	profile_del)
		_db user profile del "$FORM_ID"
		FORM_ACTION=
	;;
	login_del)
		_db user login del "$FORM_ID"
		FORM_ACTION=login_show
	;;
esac


_http header_mimetype_output "text/html"

cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<html><head><title>WLAN-System: Rechteverwaltung</title>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=ISO-8859-15">
<META HTTP-EQUIV='cache-control' CONTENT='no-cache'></head><body bgcolor='white'>
EOF


case "$FORM_ACTION" in
	profile_add|profile_update)
		echo "<h3> Rechteverwaltung $ARROW <a href='?FORM_ACTION='>Hauptmen&uuml;</a> $ARROW Profil bearbeiten </h3>"

		SUBMIT_BUTTON_TEXT="Profil anlegen"
		
		case "$FORM_ACTION" in
			profile_update)

				[ -n "$FORM_NAME" ] && {

					case "$FORM_MAX_TIME_UNIT" in		# default/internal: 'minutes'
						 hours)	FORM_MAX_TIME="$(( $FORM_MAX_TIME * 60 ))" ;;
						  days)	FORM_MAX_TIME="$(( $FORM_MAX_TIME * 1440 ))" ;;
						months) FORM_MAX_TIME="$(( $FORM_MAX_TIME * 43200 ))" ;;
					esac

					case "$FORM_MAX_TRAFFIC_UNIT" in	# default/internal: 'kilobytes'
						mb) FORM_MAX_TRAFFIC="$(( $FORM_MAX_TRAFFIC * 1024 ))" ;;
						gb) FORM_MAX_TRAFFIC="$(( $FORM_MAX_TRAFFIC * 1024 * 1024 ))" ;;
					esac

					case "$FORM_MAX_SPEED_DOWN_UNIT" in	# default/internal: 'kilobytes'
						mb) FORM_MAX_SPEED_DOWN="$(( $FORM_MAX_SPEED_DOWN * 1024 ))" ;;
					esac

					case "$FORM_MAX_SPEED_UP_UNIT" in	# default/internal: 'kilobytes'
						mb) FORM_MAX_SPEED_UP="$(( $FORM_MAX_SPEED_UP * 1024 ))" ;;
					esac

					_db user profile update "$FORM_ID" "$FORM_NAME" "$FORM_COMMENT" "$FORM_AUTOGENERATE" "$FORM_TIME_MODEL" "$FORM_MAX_TIME" "$FORM_MAX_TRAFFIC" "$FORM_MAX_SPEED_UP" "$FORM_MAX_SPEED_DOWN" "$FORM_LANDING_URL" "$FORM_COST" "$FORM_CURRENCY"
				}			
			
				SUBMIT_BUTTON_TEXT="Profil aktualisieren"
			;;
			profile_add)
				_db user profile add "z.b. Tagesticket"				# create new and...
				for FORM_ID in $( _db user profile list ); do :; done		# fetch last ID
			;;
		esac	

		eval $( _db user profile show $FORM_ID )

		echo "<form action='' method='get'>"						# currency is coded like ISO-4217
		echo "<input type='hidden' name='FORM_ACTION' value='profile_update'>"
		echo "<input name='FORM_ID' type='hidden' value='$ID'>"
		echo "<table cellspacing='1' cellpadding='1' border='0'>"
		echo "<tr bgcolor='$BG_0'><td><b>Parameter</b></td><td><b>Wert</b></td><td><b>Erl&auml;uterung</b></td></tr>"
		echo "<tr bgcolor='$BG_B'><td>Name</td><td><input name='FORM_NAME' type='text' size='32' value='$NAME'></td><td>einfacher, kurzer Name (z.b. \"2-Stunden-Tickets\")</td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Kommentar</td><td><input name='FORM_COMMENT' type='text' size='32' value='$COMMENT'></td><td>wenn n&ouml;tig, ausf&uuml;hrlicher Kommentar</td></tr>"
		echo "<tr bgcolor='$BG_B'><td>Automatisches erzeugen</td><td><input name='FORM_AUTOGENERATE' type='radio' value='1' $( test "$AUTOGENERATE" = "1" && echo checked )>ja<br><input name='FORM_AUTOGENERATE' type='radio' value='0' $( test "${AUTOGENERATE:-0}" = "0" && echo checked )>nein</td><td>wenn Logins f&uuml;r dieses Profil zur Neige gehen, sollen automatisch neue erzeugt werden?</td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Abrechnungsmodell</td><td><input name='FORM_TIME_MODEL' type='radio' value='1' $( test "$TIME_MODEL" = "1" && echo checked )>vergangene&nbsp;Zeit<br><input name='FORM_TIME_MODEL' type='radio' value='0' $( test "${TIME_MODEL:-0}" = "0" && echo checked )>benutzte&nbsp;Zeit</td><td>die Zeit l&auml;uft, wenn sich ein Benutzer das erste mal einbucht. Soll die tats&auml;chliche Online-Zeit berechnet werden oder l&auml;uft die Zeit auch weiter, wenn der Benutzer nichts im Netz macht?</td></tr>"
		echo "<tr bgcolor='$BG_B'><td>G&uuml;ltigkeitsdauer</td><td nowrap><input name='FORM_MAX_TIME' type='text' size='10' value='$MAX_TIME'><select size='1' name='FORM_MAX_TIME_UNIT'><option value='minutes' selected>Minuten</option><option value='hours'>Stunden</option><option value='days'>Tage</option><option value='months'>Monate</option></select></td><td>nach dem Abrechnungsmodell erlaubter Zeitrahmen, <i>leer</i> meint unbegrenzt</td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Maximales Datenvolumen</td><td nowrap><input name='FORM_MAX_TRAFFIC' type='text' size='10' value='$MAX_TRAFFIC'><select size='1' name='FORM_MAX_TRAFFIC_UNIT'><option value='kb' selected>Kilobyte</option><option value='mb'>Megabyte</option><option value='gb'>Gigabyte</option></select></td><td>erlaubter Rahmen der gesamten &uuml;bertragenen Datenmenge, Up- ${AMP} Download zusammengerechnet, <i>leer</i> meint unbegrenzt</td></td></tr>"
		echo "<tr bgcolor='$BG_B'><td>Maximale Upload-Geschwindigkeit</td><td nowrap><input name='FORM_MAX_SPEED_UP' type='text' size='10' value='$MAX_SPEED_UP'><select size='1' name='FORM_MAX_SPEED_UP_UNIT'><option value='kb' selected>Kilobyte/s</option><option value='mb'>Megabyte/s</option></select></td><td>erlaubte Geschwindkeit bei ausgehendem Datenverkehr, <i>leer</i> meint unbegrenzt</td></td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Maximale Download-Geschwindigkeit</td><td nowrap><input name='FORM_MAX_SPEED_DOWN' type='text' size='10' value='$MAX_SPEED_DOWN'><select size='1' name='FORM_MAX_SPEED_DOWN_UNIT'><option value='kb' selected>Kilobyte/s</option><option value='mb'>Megabyte/s</option></select></td><td>erlaubte Geschwindkeit bei eintreffendem Datenverkehr, <i>leer</i> meint unbegrenzt</td></td></tr>"
		echo "<tr bgcolor='$BG_B'><td>Internetadresse der Landeseite</td><td><input name='FORM_LANDING_URL' type='text' size='32' value='$LANDING_URL'></td><td>auf diese Seite wird der Benutzer geleitet, nachdem er sein Passwort eingegeben hat, z.b. https://www.google.com</td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Verkaufspreis</td><td nowrap><input name='FORM_COST' type='text' size='10' value='$COST'><select size='1' name='FORM_CURRENCY'><option value='EUR' $( test "$CURRENCY" = "EUR" && echo selected )>EUR - Euro</option><option value='USD' $( test "$CURRENCY" = "USD" && echo selected )>USD - US-Dollar</option><option value='VND' $( test "$CURRENCY" = "VND" && echo selected )>VND - &#272;&#7891;ng</option></select></td><td>f&uuml;r die Buchhaltung bzw. revisionssichere Protokollierung</td></tr>"
		echo "<tr bgcolor='$BG_0'><td colspan='2' align='center' valign='middle'><p><input type='submit' name='' value='$SUBMIT_BUTTON_TEXT'></p></td><td>&nbsp;</td></tr>"
		echo "</table></form>"

		[ "$FORM_ACTION" = "profile_update" -a -n "$FORM_AUTOGENERATE" ] && {
			echo "<p><i>Hinweis:</i>&nbsp;Profil wurde gespeichert</p>"
		}

		echo "</html>"
	;;
	login_add|login_update)
		echo "<h3> Rechteverwaltung $ARROW <a href='?FORM_ACTION='>Hauptmen&uuml;</a> $ARROW Login bearbeiten </h3>"

		SUBMIT_BUTTON_TEXT="Login anlegen"

		case "$FORM_ACTION" in
			login_add)
				_db user login add							# create new and...
				for FORM_ID in $( _db user login list ); do :; done			# fetch last ID
			;;
			login_update)

				SUBMIT_BUTTON_TEXT="Login aktualisieren"		# fixme! honour FORM_THEME_NAME? see beginning for a hack

				helper_update ()
				{
					_db user login update "$FORM_ID" "$FORM_PROFILE_ID" "$FORM_COMMENT" "$FORM_USERNAME" "$FORM_PASSWORD" "$FORM_DEVICE_QUANTITY" "$FORM_INSTALLED"
				}
			
				case "${FORM_DUPLICATE_NO:-1}" in
					1)
						helper_update
					;;
					*)
						FORM_USERNAME=		# does not make sense to have many tickets
						FORM_PASSWORD=		# with same values, this enforces random()
					
						helper_update
						while [ $FORM_DUPLICATE_NO -ne 1 ]; do {			# not 0 because one ticket is created yet at this point

							FORM_DUPLICATE_NO="$(( $FORM_DUPLICATE_NO - 1 ))"

							_db user login add
							for FORM_ID in $( _db user login list ); do :; done	# fetch last ID
							helper_update
						} done
					;;
				esac

				_scheduler add ". /tmp/loader; _db; _db user login index_gen"		# fixme! move to _db()
			;;
		esac

		profile_selector ()
		{
			local ID NAME COMMENT
			
			echo "<select name='FORM_PROFILE_ID' size='1'>"
			
			for ID in $( _db user profile list ); do {
				eval "$( _db user profile show $ID "NAME COMMENT" )"
				echo "<option value='$ID'"
				test "$FORM_PROFILE_ID" = "$ID" && echo -n "selected"
				echo ">${NAME}: ${COMMENT}</option>"
			} done
		
			echo "</select>"
		}

		theme_selector ()
		{
			local THEME NAME COMMENT
			[ -z "$FORM_THEME_NAME" ] && FORM_THEME_NAME="$( nvram get fff_weblogin_usernametheme )"
			echo "<select name='FORM_THEME_NAME' size='1'>"

			for THEME in $( _random_username themes ); do {
				echo "<option value='$THEME'"
				[ "$FORM_THEME_NAME" = "$THEME" ] && echo -n "selected"
				echo ">$( _random_username themeinfo "$THEME" )</option>"
			} done

			echo "</select>"
		}

		eval $( _db user login show $FORM_ID )

		echo "<form action='' method='get'>"
		echo "<input type='hidden' name='FORM_ACTION' value='login_update'>"
		echo "<input name='FORM_ID' type='hidden' value='$ID'>"
		echo "<input name='FORM_INSTALLED' type='hidden' value='$( _system date unixtime )'>"

		case "$FORM_ACTION" in
			login_add) ;;
				*) echo "<input name='FORM_DUPLICATE_NO' type='hidden' value='1'>" ;;
		esac

		echo "<table cellspacing='1' cellpadding='1' border='0'>"
		echo "<tr bgcolor='$BG_0'><td>Parameter</td><td>Wert</td><td>Erl&auml;uterung</td></tr>"
		
		echo "<tr bgcolor='$BG_A'><td>Profil</td><td>"
		profile_selector
		echo "</td><td>welches Profil soll Grundlage f&uuml;r diesen Login werden?</td></tr>"
		
		echo "<tr bgcolor='$BG_B'><td>Kommentar</td><td><input name='FORM_COMMENT' type='text' value='$COMMENT'></td><td>falls n&ouml;tig Notizen zum Nutzer oder Ereignis</td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Benutzername</td><td><input name='FORM_USERNAME' type='text' value='$USERNAME'></td><td>ein einfach zu schreibender Loginname, <i>leer</i> lassen f&uuml;r automatische Generierung mit dem Namensraum: $( theme_selector )</td></tr>"
		echo "<tr bgcolor='$BG_B'><td>Passwort</td><td><input name='FORM_PASSWORD' type='text' value='$PASSWORD'></td><td>Zahlenkombination (empfohlen), <i>leer</i> lassen f&uuml;r automatische Generierung</td></tr>"
		echo "<tr bgcolor='$BG_A'><td>Ger&auml;teanzahl</td><td><input name='FORM_DEVICE_QUANTITY' type='text' value='$DEVICE_QUANTITY'></td><td>wieviel unterschiedliche Ger&auml;te d&uuml;rfen diesen Login benutzen? <i>leer</i> lassen bedeutet unbegrenzt</td></tr>"

		[ "$FORM_ACTION" = "login_add" ] && {
			echo "<tr bgcolor='$BG_B'><td>Anzahl der Kopien</td><td><select name='FORM_DUPLICATE_NO' size='1'><option value='1'>1</option><option value='3'>3</option><option value='5'>5</option><option value='10'>10</option><option value='15'>15</option><option value='32'>32</option></select></td><td>soll eine gr&ouml;&szlig;ere Anzahl der gleichen Ticketart angelegt werden? Benutzername und Passwort werden dann in jedem Fall automatisch generiert</td></tr>"
		}
		
		echo "<tr bgcolor='$BG_0'><td colspan='2' align='center' valign='middle'><p><input type='submit' name='' value='$SUBMIT_BUTTON_TEXT'></p></td><td>&nbsp;</td></tr>"
		echo "</table></form>"

		[ "$FORM_ACTION" = "login_update" ] && {
			echo "<p><i>Hinweis:</i>&nbsp;Logindaten wurden gespeichert</p>"
		}

		echo "</html>"
	;;
	login_show)
		echo "<h3> Rechteverwaltung $ARROW <a href='?FORM_ACTION='>Hauptmen&uuml;</a> $ARROW <a href='?FORM_ACTION=login_show'>Login &Uuml;bersicht</a> </h3>"
		echo "<form action='' method='get'>"

		# fixme! erstellungszeit menschenlesbar, "vor 5 minuten"?
		# fixme! wie leichtes auswaehlen einer gruppe? (32 auswaehlen?)

		case "$FORM_RANGE_METHOD" in
			last)
				echo "<input type='hidden' name='FORM_RANGE_METHOD'  value='$FORM_RANGE_METHOD'>"
				echo "<input type='hidden' name='FORM_RANGE_KEYWORD' value='$FORM_RANGE_KEYWORD'>"
				echo "<p><i>Hinweis:</i> Es werden nur die letzten $FORM_RANGE_KEYWORD Logins angezeigt</p>"
				LIST_ID="$( _db user login list last $FORM_RANGE_KEYWORD )"
			;;
			*)
				LIST_ID="$( _db user login list )"
			;;
		esac

		echo "<table cellspacing='1' cellpadding='1' border='0'>"
		echo "<input type='hidden' name='SESSION_TIMESTAMP' value='$( _system date unixtime )'>"	# prevents cached PDF-download
		echo "<tr bgcolor='$BG_0'><td><small>Wahl</small><input type='hidden' name='FORM_CB' value='0'></td><td>&nbsp;Profil&nbsp;</td><td>&nbsp;Kommentar&nbsp;</td><td>&nbsp;Benutzername&nbsp;</td><td>&nbsp;Passwort&nbsp;</td><td>&nbsp;Ger&auml;tezahl&nbsp;</td><td>&nbsp;Erstellungszeit&nbsp;</td><td>&nbsp;Aktion&nbsp;</td></tr>"

		local MY_ID

		for MY_ID in $LIST_ID; do {

			PROFILE_ID=
			eval "$( _db user login show $MY_ID )"
			if [ -z "$PROFILE_ID" ]; then
				continue
			else
				eval "$( _db user profile show $PROFILE_ID "NAME" )"
			fi

			case "$BGCOLOR" in
				"$BG_A") BGCOLOR="$BG_B" ;;
				      *) BGCOLOR="$BG_A" ;;
			esac

			cat <<EOF
<tr bgcolor='$BGCOLOR'>
<td align='center'><input type='checkbox' ID='login${MY_ID}' name='FORM_CB_${MY_ID}' value='1'></td>
<td><label for='login${MY_ID}'>&nbsp;${NAME}</label></td>
<td><label for='login${MY_ID}'>&nbsp;${COMMENT:--}</label></td>
<td><label for='login${MY_ID}'>&nbsp;$USERNAME</label></td>
<td align='center'><label for='login${MY_ID}'>$PASSWORD</label></td>
<td align='center'><label for='login${MY_ID}'>${DEVICE_QUANTITY:-unbegrenzt}</label></td>
<td nowrap><label for='login${MY_ID}'>$( _system date unixtime2date $INSTALLED )</label></td>
<td>&nbsp;<a href='?FORM_ACTION=login_del${AMP}FORM_ID=${MY_ID}'>l&ouml;schen</a>&nbsp;|&nbsp;<a 
href='?FORM_ACTION=login_update${AMP}FORM_ID=${MY_ID}${AMP}FORM_PROFILE_ID=$PROFILE_ID${AMP}FORM_COMMENT=$COMMENT${AMP}FORM_USERNAME=$USERNAME${AMP}FORM_PASSWORD=$PASSWORD${AMP}FORM_DEVICE_QUANTITY=$DEVICE_QUANTITY${AMP}FORM_INSTALLED=$INSTALLED'>bearbeiten</a></td>
</tr>
EOF

		} done

		echo -n "<tr bgcolor='$BG_0'><td colspan='5' nowrap align='right'>"
		echo -n "<p>&nbsp;Ausgew&auml;hlte Logins&nbsp;"
		echo -n "<input type='submit' name='FORM_ACTION_LOGIN_DEL_CHECKED' value='l&ouml;schen'>&nbsp;oder&nbsp;"
		echo -n "<input type='submit' name='FORM_ACTION_LOGIN_PRINT_CHECKED' value='&Uuml;bersicht (PDF)'>&nbsp;oder&nbsp;"
		echo -n "<input type='submit' name='FORM_ACTION_LOGIN_PRINT_CHECKED_MARKER' value='Etiketten (PDF)'></p>"
		echo -n "<p>&nbsp;Alle angezeigten Logins&nbsp;"
		echo -n "<input type='submit' name='FORM_ACTION_LOGIN_DEL_RANGE' value='l&ouml;schen'>&nbsp;oder&nbsp;"
		echo -n "<input type='submit' name='FORM_ACTION_LOGIN_PRINT_RANGE' value='&Uuml;bersicht (PDF)'>&nbsp;oder&nbsp;"
		echo -n "<input type='submit' name='FORM_ACTION_LOGIN_PRINT_RANGE_MARKER' value='Etiketten (PDF)'></p>"
		echo -n "</td><td colspan='5'></td></tr>"
		echo -n "</table></form></html>"
	;;
	*)
		cat <<EOF
<h3>Rechteverwaltung $ARROW <a href='?FORM_ACTION='>Hauptmen&uuml;</a></h3>
<!-- <p> -->
<ul>
	<li><b><big>P</big>rofile</b> verwalten:
	<ul>
		<li>neues Profil <a href='?FORM_ACTION=profile_add'>erstellen</a></li>
EOF
		
		LIST_PROFILES="$( _db user profile list )"

		[ -n "$LIST_PROFILES" ] && {
			echo "<li>Profile bearbeiten:<ul>"

			for ID in $LIST_PROFILES; do {
				eval "$( _db user profile show $ID "NAME COMMENT" )"
				echo "<li><a href='?FORM_ACTION=profile_update${AMP}FORM_ID=${ID}'>bearbeiten</a> | "
				echo "<a href='?FORM_ACTION=profile_del${AMP}FORM_ID=${ID}'>l&ouml;schen</a>&nbsp;-&nbsp;$NAME$( test -n "$COMMENT" && echo "&nbsp;('$COMMENT')" )</li>"

				# fixme! only show 'del', if no deps (login|devices)

			} done

			echo "</ul></li>"
		}	
		
		cat <<EOF
	</ul></li>
</ul>
<ul>
	<li><b><big>L</big>ogins</b> verwalten:
	<ul>
EOF
		if [ -n "$LIST_PROFILES" ]; then
			echo "<li>neue Logins <a href='?FORM_ACTION=login_add'>erstellen</a></li>"
		else
			echo "<li>neue Logins <s>erstellen</s> (zuerst muss ein Profil angelegt werden)</li>"
		fi

		LIST_LOGINS="$( _db user login list )"

		[ -n "$LIST_LOGINS" ] && {
		
			LIST_LOGINS_COUNT="$( _db user login list | wc -l )"
			LIST_LOGINS_COUNT="$(( $LIST_LOGINS_COUNT + 0 ))"
			
			echo "<li>Logins <a href='?FORM_ACTION=login_show${AMP}FORM_RANGE_METHOD=all'>anzeigen&nbsp;($LIST_LOGINS_COUNT St&uuml;ck)</a>"

			[ $LIST_LOGINS_COUNT -gt 10 ] && {
				echo "<ul>"			# fehlendes <li>?
				echo "<li><a href='?FORM_ACTION=login_show${AMP}FORM_RANGE_METHOD=last${AMP}FORM_RANGE_KEYWORD=5'>die neuesten 5</a>,&nbsp;"
				echo "<a href='?FORM_ACTION=login_show${AMP}FORM_RANGE_METHOD=last${AMP}FORM_RANGE_KEYWORD=10'>10</a>,&nbsp;"
				echo "<a href='?FORM_ACTION=login_show${AMP}FORM_RANGE_METHOD=last${AMP}FORM_RANGE_KEYWORD=15'>15</a>,&nbsp;"
				echo "<a href='?FORM_ACTION=login_show${AMP}FORM_RANGE_METHOD=last${AMP}FORM_RANGE_KEYWORD=32'>32</a>"
				echo "</li></ul>"
			}

			echo "</li>"
		}

		cat <<EOF
</ul></li>
<li><br><b><big>G</big>er&auml;te</b> verwalten:
	<ul>
EOF
		LISTE_DEVICES="$( _db user device list )"
		
		if [ -n "$LIST_LOGINS" ]; then
			echo "<li>neue Ger&auml;te <a href='?FORM_ACTION=device_add'>eintragen</a></li>"
		else
			echo "<li>neue Ger&auml;te <s>eintragen</s> (zuerst muss ein Login angelegt werden)</li>"
		fi
		
		[ -n "$LISTE_DEVICES" ] && {
			echo "<li>Ger&auml;te anzeigen</li>"
		}

		cat <<EOF
	</ul></li></ul>
EOF
	;;
esac

echo "</body></html>"
